### ISSUE TITLE
Source:tell never resets for streaming Sources when the source loops

### ISSUE THREAD

**Issue by slime73** [love2d/love#1089]
**[Original report](https://bitbucket.org/rude/love/issue/1084) by Alex Szpakowski (Bitbucket: [slime73](https://bitbucket.org/slime73), GitHub: [slime73](https://github.com/slime73)).**

----------------------------------------

If a streaming Source with the looping property set to true loops, Source:tell doesn't reset back to 0. It does with static sources, however.

**Comment by NyakoFox** [comment]
Apparently this also happens when seeking close to the end. This is very noticeable with something like a seek bar.
