### ISSUE TITLE
Android Home Button Doesn't Close LOVE Application

### ISSUE THREAD

**Issue by slime73** [love2d/love#1168]
**[Original report](https://bitbucket.org/rude/love/issue/1163) by Ryan Hughes (Bitbucket: [r-hughes](https://bitbucket.org/r-hughes), ).**

----------------------------------------

I'm using a Samsung Galaxy Core 2 (SM-G386W) with Android 4.4.2.

When I run my application and hit the home button, the game seems to close, however trying to start it again causes the phone to freeze or the application to start improperly (music plays but I remain on the home screen... I can only close to application by going into the device settings and manually triggering a force quit).

**Comment by MikuAuahDark** [comment]
Looking at #1141, I don't think this is an issue. Please let us know if issue still persist.
