### ISSUE TITLE
love.window.isDropping

### ISSUE THREAD

**Issue by slime73** [love2d/love#1346]
**[Original report](https://bitbucket.org/rude/love/issue/1341) by hahawoo (Bitbucket: [hahawoo](https://bitbucket.org/hahawoo), GitHub: [hahawoo](https://github.com/hahawoo)).**

----------------------------------------

I think it would be nice if there was a function which returned whether the user is dragging a file/directory over the window but hasn't released the mouse button yet, so a "drop file here!" message could display or something.

Briefly looking at the SDL docs, I guess this would mean setting some internal value when SDL_DROPBEGIN and SDL_DROPFILE happen (if those events do what I assume they do).

**Comment by slime73** [comment]
Callbacks are added in 8d37303.

**Comment by slime73** [comment]
The desired functionality here actually isn't possible yet, until SDL adds it: https://github.com/libsdl-org/SDL/issues/5292

**Comment by EngineerSmith** [comment]
For love 11.4, I've created a basic library https://github.com/EngineerSmith/isdropping to get a similar behaviour - but isn't perfect with the issue of not having a SDL event for it. Adding this comment here if anyone needs a solution around this for now
