### ISSUE TITLE
Incorrect screen position set when exiting fullscreen mode

### ISSUE THREAD

**Issue by slime73** [love2d/love#1426]
**[Original report](https://bitbucket.org/rude/love/issue/1421) by Blake Wyatt (Bitbucket: [Blake Wyatt](https://bitbucket.org/Blake Wyatt), ).**

----------------------------------------

When using
```
#!lua
love.window.setMode(400, 400, {x=200, y=200, display=1, fullscreen=true})
```
and then toggling fullscreen, the window will go back to the right dimensions, but not the right screen position.

I've attached a small example program.  Just open it up, it will start in fullscreen mode, and then press any key to switch to windowed mode.  It will spawn the window in the center of the screen, not (200, 200) like it should.

**Comment by slime73** [comment]
[screen_position_bug.love.zip](https://github.com/love2d/love/files/4238667/screen_position_bug.love.zip)

**Comment by nabakin** [comment]
Hi, I'm the original poster on Bitbucket. This is my Github account.
