### ISSUE TITLE
Not optimized for smartphone with screen 18:9

### ISSUE THREAD

**Issue by slime73** [love2d/love#1428]
**[Original report](https://bitbucket.org/rude/love/issue/1423) by Maosentis (Bitbucket: [Maosentis](https://bitbucket.org/Maosentis), ).**

----------------------------------------

**Comment by MikuAuahDark** [comment]
This could be related to phones with notch. As 11.3 now includes notch area as their drawing area, I don't think this is an issue anymore.

Closes.
