### ISSUE TITLE
Can't cross-build for Linux without Objective C++ toolchain

### ISSUE THREAD

**Issue by slime73** [love2d/love#1436]
**[Original report](https://bitbucket.org/rude/love/issue/1431) by IoriBranford (Bitbucket: [IoriBranford](https://bitbucket.org/IoriBranford), GitHub: [IoriBranford](https://github.com/IoriBranford)).**

----------------------------------------

I'm cross-building LOVE for armhf (Raspberry Pi) using Buildroot with Linaro 2017.11 toolchain.

Everything compiles OK, but when linking to make the executable, it wants to use the Objective C++ compiler even though I'm not building OSX or iOS and can't find any use of Obj-C++ code in the build. Linaro provides only C/C++ binaries, so in my case it falls back to the host machine's Obj-C++ which is not armhf, and thus the cross-build breaks.

From src/Makefile.in - note OBJCXX when it should be CXX:

```Makefile
love_LINK = $(LIBTOOL) $(AM_V_lt) $(love_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(OBJCXXLD) $(AM_OBJCXXFLAGS) $(OBJCXXFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@

love$(EXEEXT): $(love_OBJECTS) $(love_DEPENDENCIES) $(EXTRA_love_DEPENDENCIES) 
	@rm -f love$(EXEEXT)
	$(AM_V_OBJCXXLD)$(love_LINK) $(love_OBJECTS) $(love_LDADD) $(LIBS)
```

**Comment by anna9191** [comment]
Very nice information you share with us. Thanks for this.
[gmail sign up](http://tuts-plus.com/gmail-sign-up/)
[hotmail email login](https://sites.google.com/site/hotmailemailloginmsn/)

**Comment by slime73** [comment]
I believe this is no longer an issue in love 12 now, with its CMake build system for Linux.
