### ISSUE TITLE
Handle Windows audio playback device switching

### ISSUE THREAD

**Issue by slime73** [love2d/love#1474]
**[Original report](https://bitbucket.org/rude/love/issue/1469) by Maurice (Bitbucket: [Stabyourself](https://bitbucket.org/Stabyourself), GitHub: [Stabyourself](https://github.com/Stabyourself)).**

----------------------------------------

In Windows you can switch between different audio devices, such as HDMI devices and the built in motherboard output. If you switch the device while LÖVE is running, it will not actually change to the new device, instead continuing on the previous one.

It would be nice if LÖVE could switch, as it seems to be the default behavior for any other popular program I tested, like VLC, Chrome and Spotify.

**Comment by MikuAuahDark** [comment]
This has been implemented in #1805.
