### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by slime73** [love2d/love#1482]
**[Original report](https://bitbucket.org/rude/love/issue/1477) by 林博仁 (Bitbucket: [brlin](https://bitbucket.org/brlin), GitHub: [brlin](https://github.com/brlin)).**

----------------------------------------

Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/love-brlin), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):

    # Install the snap
    sudo snap install love

    # Allow the snap to access the joystick devices
    sudo snap connect love:joystick

    # Allow the snap to access files under /media or /mnt
    sudo snap connect love:removable-media

    # Launch the game
    love game-to-test.love

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://git.launchpad.net/love-snap/tree/snap/snapcraft.yaml), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by MikuAuahDark** [comment]
I think AppImage are sufficient for amost all Linux distros. AFAIK Snaps are Ubuntu-specific so it's misleading to say "Snaps are universal **Linux** packages".

**Comment by Lin-Buo-Ren** [comment]
> AFAIK Snaps are Ubuntu-specific so it's misleading to say "Snaps are universal Linux packages".

Snaps can be installed on numerous GNU/Linux distributions that features a recent Linux kernel and systemd, refer [Installing snapd | Snapcraft documentation](https://snapcraft.io/docs/installing-snapd) for more info.

> provides Ubuntu ppa for LOVE

One of the features of snaps is to distribute multiple version of the application simultaneously via the use of [tracks](https://snapcraft.io/docs/channels#heading--tracks), this allows (for example) LOVE to ship version 10 and 11 at the same time for game compatibility, etc.

**Comment by MikuAuahDark** [comment]
Alright I stand corrected of Snap being Ubuntu-only.

I wonder if this is the current recipe https://git.launchpad.net/love-snap/tree/snap/snapcraft.yaml? Since that looks outdated to me (still targets Mercurial repository instead of this GitHub repository).

I'd suggest to disable `libgme` to keep LOVE feature parity with other platforms.

**Comment by bartbes** [comment]
Love-linux-builder (currently off the internet because of the bitbucket purge) provides a way to make snaps from the same binaries used for the appimages. It's not exactly using proper snap tooling, but the last time I tried (years ago), it did work.

**Comment by MikuAuahDark** [comment]
After reevaluating this issue, are Snaps really needed? There's recent change on how we'll package AppImages from now to pull all the library dependencies from their upstream sources, which usually way more up-to-date and I think that's sufficient.

**Comment by slime73** [comment]
I think I agree - if someone wants to make their own package of love I'm not gonna stop them, but since love already has AppImages I don't see much of a need to add extra official packages supported by us that are similar to it.
