### ISSUE TITLE
crc32

### ISSUE THREAD

**Issue by slime73** [love2d/love#1519]
**[Original report](https://bitbucket.org/rude/love/issue/1514) by itraykov (Bitbucket: [itraykov](https://bitbucket.org/itraykov), GitHub: [itraykov](https://github.com/itraykov)).**

----------------------------------------

Would be nice to have native support for crc32 in love.math.

I need it for the following lib so we can build ZIP/LOVE files:

[https://love2d.org/forums/viewtopic.php?f=5&t=86893](https://love2d.org/forums/viewtopic.php?f=5&t=86893&p=229613#p229613)

**Comment by MikuAuahDark** [comment]
After further discussion, we probably don't want CRC32 functionality in LOVE for few reasons:
* CRC32 can be implemented in pure Lua without too much performance hit, unlike cryptographic hash functions.
* There are many different CRC32 polynomials and different ways to handle the input/output values.
