### ISSUE TITLE
App fails to load audio module if using third party audio software

### ISSUE THREAD

**Issue by slime73** [love2d/love#1529]
**[Original report](https://bitbucket.org/rude/love/issue/1524) by Morda (Bitbucket: [Morda](https://bitbucket.org/Morda), GitHub: [Morda](https://github.com/Morda)).**

----------------------------------------

I’m using VoiceMeeter Banana for some tricky audio routing. When it’s launched, LOVE can’t initialize it’s audio module. Console gave me this error:

AL lib: \(EE\) ALCwasapiPlayback\_resetProxy: Failed to initialize audio client: 0x8889000a  
Could not create context.

Also, if you launch VoiceMeeter after strarting the LOVE app it silently shuts down the audio module and prints this in console:

AL lib: \(EE\) ALCwasapiPlayback\_mixerProc: Failed to get padding: 0x88890004

Is this something that should be fixed on your side?

**Comment by anna9191** [comment]
I really wanted to send a small word to say thanks to you for the fantastic points you are writing on this site.
[gmail sign up](https://sites.google.com/site/tipstologin/gmail-sign-up)
[hotmail login](https://sites.google.com/site/hotmailloginmsn/)

**Comment by MikuAuahDark** [comment]
If the other app is taking exclusive access of the audio hardware then I don't think there's LOVE (or OpenAL-soft) can do.
