### ISSUE TITLE
Blank screen when backgrounding the Play Store 11.3 app and starting it again on Android 10.

### ISSUE THREAD

**Issue by slime73** [love2d/love#1532]
**[Original report](https://bitbucket.org/rude/love/issue/1527) by Michael Franz (Bitbucket: [mishafranz](https://bitbucket.org/mishafranz), ).**

----------------------------------------

Hi,

I just downloaded 11.3 sources tar.gz and built with Android Studio without issues.

Then I put a script into assets folder and it seems to work more or less as expected.

However when I switch away from the app \(put it to the background\) and then start the app again, the app shows blank screen instead of resume.

If I go back to the app on the background it resumes without issues.

To be sure there is no issue with the way I built the app, I tested the same with the app from the play store: installed the app, downloaded the script, found the .love file with the file browser and opened with Love for Android. The script worked. I put the app on the background and started the app again - blank screen.

Thanks,

Michael.

**Comment by MikuAuahDark** [comment]
I think this is resolved already.
