### ISSUE TITLE
some problems when compile love 0.9.2 version

### ISSUE THREAD

**Issue by slime73** [love2d/love#1542]
**[Original report](https://bitbucket.org/rude/love/issue/1537) by sagax sagax (Bitbucket: [sagax](https://bitbucket.org/sagax), GitHub: [sagax](https://github.com/sagax)).**

----------------------------------------

I try to compile love 0.9.2 version, because some games require this version of love. But compile don’t success.

[link to errors](https://susepaste.org/35747067)

[glew info](https://susepaste.org/20097458)

[glxinfo](https://susepaste.org/96148415)

OS - Linux 5.4.7-1-default x86\_64

Distro - openSUSE Tumbleweed

SDL - 2.0.10

how to configure before make

```shell
CPPFLAGS='-I/usr/include/GL/' ./configure --prefix=$HOME/programs/love-0.9.2 --with-lua=lua5.1 --with-luaversion=5.1
```

‌

**Comment by anna9191** [comment]
This is a very interesting post and all the details are in this post are awesome.
[hotmail login](http://hotmailblog.com/hotmail-login/)

**Comment by slime73** [comment]
This should work for most Linux systems: https://github.com/pfirsich/love-appimages/blob/master/fix_0_9_2.patch
