### ISSUE TITLE
feature request: love.data.encode('json')

### ISSUE THREAD

**Issue by slime73** [love2d/love#1548]
**[Original report](https://bitbucket.org/rude/love/issue/1543) by Kyle McLamb (Bitbucket: [Alloyed](https://bitbucket.org/Alloyed), GitHub: [Alloyed](https://github.com/Alloyed)).**

----------------------------------------

Implementation strategy: add lua-cjson as a library. add an encode/decode format that uses json.encode and json.decode with sane defaults.

rationale: lua-cjson is several times faster then the pure lua variants. For large payloads ala gltf it’s very worth it. Baking it into love.data lets us also take data objects, saving us the step of loading the full json into string memory.

‌

**Comment by raidho36** [comment]
JSON is trivial enough to be efficiently implemented in plain Lua (and so there are tons of Lua modules for JSON handling) and does not warrant implementing it in the framework.

**Comment by MikuAuahDark** [comment]
I don't think we need JSON encoding function because there are many edge cases that users may expect and may result in users shipping their own JSON library for their needs anyway.

The edge cases I mention are:
* Should it outputs pure ASCII or should it allows UTF-8 strings?
* If we support pretty printing, how it should pretty print? There are many combinations of spacing/tabs, position of braces, etc.

For simple JSON encoding without pretty printing, rxi/json is sufficient. For basic pretty printing, jf-JSON is okay. If they want performance, then the user should know that pure Lua implementation won't be sufficient.

**Comment by mtdowling** [comment]
Builtin JSON encoding and decoding would still be a big improvement for Love2D IMO. Open questions like how UTF8 are handled and if/how to pretty print seem straightforward to figure out.

The pitch for including JSON in love2d is that most tools export data as JSON and few export as Lua. HTTP APIs also commonly use JSON, so JSON support in love2d would compose nicely with the client being added. Finally, builtin JSON handling makes it easier for library authors targeting Love2d to automatically have access to a JSON parser without needing to rely on a user land implementation (which implies either using things like LuaRocks to manage dependencies or every library that requires JSON has to bundle their own duplicate copy of a JSON parser). Other Lua game engines in the same space as Love2d provide JSON support, for example https://defold.com/ref/stable/json-lua/

**Comment by MikuAuahDark** [comment]
> Open questions like how UTF8 are handled and if/how to pretty print seem straightforward to figure out.

Simple JSON decoder and encoder like [rxi/json](https://github.com/rxi/json.lua) already handles UTF-8 pretty well. There's no issue with it. The only downside with rxi's is lack of pretty-printing.

If accessibility is a concern, rxi's and [dkjson](https://dkolf.de/dkjson-lua/) is single-file that can be just dropped in any user projects. This doesn't require LuaRocks (and our community discourage its uses). The performance concern still exist but unless you're loading very large JSON while the game is running, there's no need to worry about performance.
