### ISSUE TITLE
Destroying a fixture before applying impulse drastically changes results

### ISSUE THREAD

**Issue by slime73** [love2d/love#1549]
**[Original report](https://bitbucket.org/rude/love/issue/1544) by Antoine Gersant (Bitbucket: [antoinegersant](https://bitbucket.org/antoinegersant), ).**

----------------------------------------

This took a while to track down. In the game I am working on, this bug manifested itself by making knockback animations behave very differently depending on whether the associated animation has hitbox data associated with it.

Anyways, here is a minimal repro of the bug. Create two bodies, each with a fixture. Then delete one of the fixtures and apply a linear impulse to both bodies. I would expect both bodies to behave the same but one of them travels much further.

A few notes:

* Still happens if the fixtures are sensors \(my original use case\)
* Oddly enough, the body whose fixture is not getting destroyed is the one behaving differently from a similar test case where no fixtures are created/destroyed at all
* Destroying the fixture after emitting the impulse causes both bodies to travel the longer distance
* Waiting several frames between destroying the fixture and applying the impulse does not work around the issue
* Setting density on the fixtures or mass on the bodies doesn’t work around the issue
* All testing was done on Windows

To see the bug in action, run the attached main.lua and press space. Press space again to reset to the initial state.

I also attached a video of the repro.

‌

Any help would be welcome, hopefully this isn’t me misunderstanding how the physics API works!

‌

‌

**Comment by agersant** [comment]
Thanks for migrating the issue from Bitbucket. Here are the attached files from the original issue (repro code + video).
[destroy-fixtures.zip](https://github.com/love2d/love/files/4234144/destroy-fixtures.zip)

**Comment by agersant** [comment]
Investigating this a bit further, I did find a workaround.

Passing a density of 0 as the last argument to `createFixture()` makes this work as intended. Calling `setDensity(0)` immediately after creating the fixtures still reproduces the bug.

**Comment by ImagicTheCat** [comment]
Tested it, it's not really a bug, but a Box2D behavior. When adding/removing fixtures, the mass (and center/inertia) of the body can change, you can check that with `body:getMassData()`.

I found a reference in the doc: https://box2d.org/documentation/classb2_body.html#a58a641fedf8a81e1e26d09ec00a22fe2
> Note that creating or destroying fixtures can also alter the mass.

**Comment by slime73** [comment]
I added notes saying as much to the wiki's newFixture and Fixture:destroy pages.
