### ISSUE TITLE
Text:add error gives incorrect argument number

### ISSUE THREAD

**Issue by theRealsteveRoll** [love2d/love#1557]
When you use the `Text:add` variant which accepts a table with colored text:
If the format of the color table is incorrect, something like this:
```lua
text:add({nil, "some text"})
```
This error is given:
```
bad argument #3 to 'add' (string expected, got nil)
```
It says "bad argument #&#x2060;3", but the color table is actually the first argument.
And, if you add any parameters after the color table (`x`, `y`, `angle` etc.), the incorrect argument will be incremented. So if you do this:
```lua
text:add({nil, "some text"}, 100, 200)
```
You'll get this error:
```
bad argument #5 to 'add' (string expected, got nil)
```

**Comment by MikuAuahDark** [comment]
This is caused by Lua C API confuses the table index vs. argument. LOVE only uses `luaL_check*` functions for it and it generates "bad argument #n" error based on index passed at those functions. Here's slime's quote from Discord

> Lua’s C APIs output somewhat confusing error messages for things that are part of a table argument, because they only know about the value’s stack index number, and not anything about which table the value resides in
