### ISSUE TITLE
Use LuaJIT with "full" Lua 5.2 compatibility

### ISSUE THREAD

**Issue by tobiasvl** [love2d/love#1562]
(I know this won't happen any time soon, until this is the case for most Linux distros' LuaJIT packages.)

It'd be really nice if LÖVE's LuaJIT could be compiled with `-DLUAJIT_ENABLE_LUA52COMPAT` for [extra features](https://luajit.org/extensions.html), especially features like the metamethods `__len`, `__pairs` and `__ipairs`.

**Comment by MikuAuahDark** [comment]
For Windows, recompiling LuaJIT (using VS2013) with such flags and replacing the LOVE-bundled lua51.dll should be sufficient.

**Comment by MikuAuahDark** [comment]
Based on feedback from users and discussion in Discord, I don't think we'll be enabling this for our official builds. Mainly because Linux package managers tend not to have LuaJIT with this compile-time feature enabled.

I'll be closing this, but we're open to discussion on enabling this.
