### ISSUE TITLE
attempt to call global index value

### ISSUE THREAD

**Issue by beyzaperifles** [love2d/love#1565]
Hi! I'm learning lua programming. I get this error: Error

main.lua:25: attempt to call global 'spawnPlatform' (a nil value)

Traceback

main.lua:25: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

I can't fix it. Please help me, i can't show any progress right now.

**Comment by MikuAuahDark** [comment]
Hello, this issue tracker is meant for problems with built-in LOVE functions, not for Lua help.

If you need help with your code, consider joining our [Discord server](https://discord.gg/rhUets9) and ask in our #support channel, thank you.

**Comment by zorggn** [comment]
Alternatively you can also visit the forums at https://love2d.org/forums/ , although you will need to register to post there.
