### ISSUE TITLE
Love.graphics only either takes 255 or 0

### ISSUE THREAD

**Issue by Steago47** [love2d/love#1566]
Any love.graphics function that accepts color such as `love.graphics.setColor` or love.graphics.clear only renders a color attribute either at its `255` value or at its `0` value. this means that `love.graphics.clear(255,255,255,255)` or `love.graphics.clear(1,1,1,255)` fills the background with the same color, 100% white. the same thing happens with the `love.graphics.setColor` for objects such as shapes or writing.

**Comment by slime73** [comment]
[As of love 11](https://love2d.org/wiki/11.0#Other_changes), any love function which takes color arguments uses 0-1 instead of 0-255.
