### ISSUE TITLE
Unable to launch on Mac osstatus error 99999

### ISSUE THREAD

**Issue by Bastczuak** [love2d/love#1568]
I've downloaded the latest love binary for Mac from your website and after executing it I always get the osstatus error 99999. I already tried to fix it by typing the command `sudo cp /var/db/.SystemPolicy-default /var/db/SystemPolicy`. But this does not solve it. I'm using MacOS 10.14.6.

**Comment by slime73** [comment]
As far as I can tell this is a local issue on your system rather than a problem with LÖVE's code. If redownloading the app doesn't work I'd suggest looking at what other people have said online about the same issue with other apps.

**Comment by Bastczuak** [comment]
I'm out of ideas, google didn't help either. Redowloaded it with 4 different browsers.

**Comment by zorggn** [comment]
Found these with google, have you tried them?
http://hints.macworld.com/article.php?story=20130803041717457
https://discussions.apple.com/thread/8463852 (same as above basically, but "official" apple forums or whatever :3)

**Comment by Bastczuak** [comment]
@zorggn I already tried this. Maybe even the default db is corrupted.
