### ISSUE TITLE
Outdated link on website

### ISSUE THREAD

**Issue by Zireael07** [love2d/love#1569]
Hi guys,
letting you know that the link on the main page of Love2D points to the bitbucket repo...?

**Comment by zorggn** [comment]
To expand on this, while the one in the top-right row of the wiki/forum/bugs buttons have been re-pointed to github, the main page still says "The source can be found on Bitbucket." with the link pointing there, under the Open Source section.

**Comment by bartbes** [comment]
I just fixed 2 references to bitbucket, the only remaining one is the link for "older versions", which I guess is still accurate.
