### ISSUE TITLE
Hard crash with current HEAD on windows 10 / MSVC 2019

### ISSUE THREAD

**Issue by ettiernu** [love2d/love#1570]
12.0-development
Reverting SHA 23bc1a7aaebcd4a4e061dae1e217f75f6607e76c solves the issue.
Impacts 32 as well 64 bit builds.

Apologies for lack of proper "git etiquette". Can't seem to find a way to label this as 12.0 relevant.

**Comment by slime73** [comment]
Is there a specific bit of code which crashes for you - i.e. do you have a .love file or main.lua code which can reproduce it? Or does the no-game screen crash as well?

What GPU do you have?

**Comment by ettiernu** [comment]
Its during initialization and even the "no game" screen will crash it.

**Comment by pfirsich** [comment]
I tried it on Windows 10 with a 2070 Super (latest drivers) and with this artifact: https://github.com/love2d/love/actions/runs/56328817 (the latest from 12.0-development) I also get a segmentation fault when starting love.exe without any arguments.

**Comment by slime73** [comment]
Fixed, thanks!
