### ISSUE TITLE
Blue Screen Error

### ISSUE THREAD

**Issue by PipoTime** [love2d/love#1571]
Error

main.lua:5: Could not open file whale.png. Does not exist.

Traceback

[C]: in function 'newImage'
main.lua:5: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by MikuAuahDark** [comment]
Redirect any Lua errors to [forums](https://love2d.org/forums) or [Discord](https://discord.gg/rhUets9)
