### ISSUE TITLE
Port to Chromebook 'linux native or crouton environment

### ISSUE THREAD

**Issue by timoc** [love2d/love#1572]
Hi,

I am setting up this for an arm chromebook, I will have to do a local cross compile. 

It would be great if this was available in one or more of the available chromeos linux chroot arm repositories. 

It is buildable in the Chromeos Linux Beta (chroot system) using the ubuntu/debian instructions here:
https://love2d.org/wiki/Building_L%C3%96VE

it is also buildable for the crouton chroot, with a little bit more work figuring out dependencies, using the same process.

**Comment by slime73** [comment]
> It would be great if this was available in one or more of the available chromeos linux chroot arm repositories.

I'm not familiar with that ecosystem, but typically it's up to the maintainers of a specific linux repository to make something available in that repository. Have you contacted the people involved with that repository?
