### ISSUE TITLE
Don’t know what to do. I am very inexperienced. I don’t know how to start

### ISSUE THREAD

**Issue by Razer953** [love2d/love#1574]

**Comment by Razer953** [comment]
Help!

**Comment by jiaaro** [comment]
@Razer953 this isn't really the place to ask for help, but I'd recommend this for getting started:

https://sheepolution.com/learn/book/0

**Comment by MikuAuahDark** [comment]
* Check the Wiki: https://love2d.org/wiki/Getting_Started
* Join the Discord server: https://discord.gg/rhUets9
