### ISSUE TITLE
love isnt installing in mac 

### ISSUE THREAD

**Issue by idksana** [love2d/love#1575]
"“love” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
Chrome downloaded this file today at 5:09 PM from love2d.org"

I tried to open the terminal and enter the code from 'getting started' and it doesn't do anything

**Comment by mvandervoord** [comment]
If you go to `settings` (the gear icon on your task bar) and then select the one marked `security` after you try to run `love`, there will be a message on the `general` tab that says something about not being able to run `love`. There's a button that allows you to run it anyway. You'll only have to do this the first time.

**Comment by slime73** [comment]
An alternative to going through the Settings app is to just right click the love app in Finder and click Open from the dialog menu. There'll be a popup to allow it to launch when you do that, and after that double clicking or other methods of opening it will work fine.
