### ISSUE TITLE
Allow pushing a function into a Channel via the use of string.dump?

### ISSUE THREAD

**Issue by icylavah** [love2d/love#1576]
[From Lua 5.1 reference manual:](https://www.lua.org/manual/5.1/manual.html#pdf-string.dump)
`string.dump (function)`
> Returns a string containing a binary representation of the given function, so that a later `loadstring` on this string returns a copy of the function. `function` must be a Lua function **without upvalues**.

I tried this in 11.3 - turned a function into a string using `string.dump`, passed it to a channel, took it out of the channel on a different thread, used loadstring to turn it back into a function... and it works! 

So it would be nice if I wouldn't have to do these shenanigans and love would just do it automatically. Of course it's not ideal since you can't reference upvalues (I haven't tried this, but I assume you just end up referencing a global instead). Still, it's better to have it half working than not to support passing in functions at all, I think.

**Comment by zorggn** [comment]
It wouldn't reference a global, it'd try to reference something that the thread's own lua state quite possibly won't have.

That combined with the no upvalues warning limits things quite much... still, as you found out, dumping simpler functions into strings will probably work, but imho it'd be too many restrictions to outright claim that functions can be passed through Channels, much less implement them like that.

Löve also can't check for you if your dumped function contains anything that would look like a global/upval ref or not, so it can't error either before you try to send the function. (as far as i know, anyway; note i'm not talking about the eventual call in the other thread; not sure whether that'd just safely error or actually cause a segfault or something)

And besides, you'd probably not gain any significant speedups either by it being done by löve on the C++ side, but that one's just a guess.

Half working already works by manually dumping it yourself and sending it as a string, implementation would do the same thing anyway, and might give users some false assumptions regarding this... i'd vote no on this, but of course, it's just my 50 cents.

**Comment by icylavah** [comment]
@zorggn Ok so I tried referencing an upvalue. It appears that doing that simply results in a nil value, no errors or anything (it doesn't matter if you define a local or global of the same name before calling loadstring to recreate the function). Referencing a global will result in the global of the calling thread. It's probably best to prepend `_G.` to each global variable you reference if you want to make sure you don't accidentally reference an upvalue (or just be really careful about it). Referencing the function's arguments is valid and they shadow upvalues, so if you only use the function arguments, you're safe. (Tested these on Ubuntu 20.04, idk about other OSs)

Anyway, the reason for this request is not for performance but rather for convenience. Yes I can do it manually, but if this was an included feature I wouldn't have to bother with that, and since there isn't currently any implementation for passing in functions, you might as well use this. Plus, I potentially have to add extra logic to figure out if an incoming value is just a regular string or if it's actually supposed to be a function. And yeah it's only partially working, but tables are only partially working too (they can't include functions or userdata), but they are supported nevertheless (and before version 11 you couldn't even pass in nested tables).

I do see your point on users misunderstanding this feature though. One solution I see is to add some global flag for whether to allow passing in functions or not. So for example you could have something like `love.thread.setAllowFunctions(boolean)`, and have it be false by default. And then on this function's wiki you can warn users of the downfalls of this feature.

You know, the more I think about it, the more useless this feature seems xD

**Comment by slime73** [comment]
I feel like function serialization is a higher level feature than the rest of the `Channel` APIs - especially since the costs and problems with using it wouldn't be very obvious. 

On the surface I like the idea of having a higher level job system / thread pool API in love.thread which could work with Pure functions, but that would be a separate design with its own set of challenges, and if it used Channels to pass those pure functions around, it would only be as an implementation detail and could just use string.dump to do so.
