### ISSUE TITLE
DBUS: Arguments to dbus_message_new_method_call() were incorrect

### ISSUE THREAD

**Issue by fabiopolancoe** [love2d/love#1583]
Hi, it's my first time using LÖVE2D. I installed it in my Ubuntu MATE i386 computer with the `apt install` command. When I issued the `love` command, got this output:
```
fabio@Fabio-PC:~$ love
dbus[20340]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

```
I thought it wasn't the correct command, so I went to ZeroBrane Studio (which hast built-in compatibility with LÖVE2D) and ran the script in Love2D mode, but I got the same error.
```
Program starting as '"/usr/bin/love" "/home/fabio/luacon-master" -debug'.
Program 'love' started in '/home/fabio/luacon-master' (pid: 19811).
dbus[19811]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Program completed in 2.46 seconds (pid: 19811).
```
I don't know if there's anything that I am doing bad, it would be great to have your help, i think that Love2D is awesome.

**Comment by MikuAuahDark** [comment]
Quick Google search show me this https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1775067 and this sounds like problem with SDL.

Can you try to update libsdl2-2.0-0 with `sudo apt install libsdl2-2.0-0`?

**Comment by fabiopolancoe** [comment]
Thanks @MikuAuahDark, but it don't worked 😞

**Comment by MikuAuahDark** [comment]
Then it looks like problem with SDL and there's nothing LOVE can do.
