### ISSUE TITLE
Canvas mipmaps freeze

### ISSUE THREAD

**Issue by Luke100000** [love2d/love#1585]
Updating Canvas mipmaps (Either when manually updating via generateMipmaps() or by using "auto" mode and then switching canvas) freezes the game for around 2 sec, then continues, but will not update the window content.
lg.setMode() or fullscreen toggle wont fix it again.

Happens on an Intel UHD 620, love2d 11.3, up to date Windows 10.

Image mipmaps work properly.

Following code shows a timer freezing after space being hit on affected systems:
```
local canvas = love.graphics.newCanvas(256, 256, {mipmaps = "manual"})

function love.draw()
	love.graphics.print(love.timer.getTime())
end

function love.keypressed(key)
	if key == "space" then
		canvas:generateMipmaps()
	end
end
```

**Comment by MikuAuahDark** [comment]
Are you happen to be in 26.20.100.7985 driver? Since I'm just affected by this bug recently. I have Visual Studio lying around so I can directly test patches. One thing to note is this bug is specific to 11.3, current 12.0-development branch (as of writing) doesn't have this problem.

On unrelated note, tou'll see something is logged to the event viewer when it hangs, which probably indicate the whole graphics stack hangs or something.

**Comment by Luke100000** [comment]
25.20.100.6446, I am unable to update the driver.
I can confirm the event, Display driver igfx stopped working and recovered.

**Comment by slime73** [comment]
One thing to test - just to help confirm what's causing the issue - would be to add a `nb_mips = 1;` line here: https://github.com/love2d/love/blob/master/src/modules/graphics/opengl/Canvas.cpp#L58

**Comment by MikuAuahDark** [comment]
The problem disappear when I add that line. I also tried to experiment with `nb_mips = nb_mips > 2 ? 2 : nb_mips;` instead and no crashes. However as soon as I change `2` to `3`, it crashes.

**Comment by slime73** [comment]
I just pushed this change – I'm not positive whether it'll fix the issue or not though, so testing would be appreciated: https://github.com/love2d/love/commit/4f730e930be0f7e814cadb4ac103e2457533ce2b

**Comment by MikuAuahDark** [comment]
It did not fix the issue.

**Comment by slime73** [comment]
I hate driver bugs...
