### ISSUE TITLE
Keyboard input types

### ISSUE THREAD

**Issue by Aiq0** [love2d/love#1586]
It would be great, if it will be possible to set keyboard layout on mobile devices such as "text" for normal entering text, "number" for entering numbers, "none" for disable,...
It could be something like `love.keyboard.setTextInput(inputType, x, y, w, h)` instead of current `love.keyboard.setTextInput(enabled, x, y, w, h)`

**Comment by MikuAuahDark** [comment]
If SDL added this feature, I'll happily add it. But sadly, SDL doesn't support this feature.
