### ISSUE TITLE
Love2D not opening in Ubuntu 20.04

### ISSUE THREAD

**Issue by paxth** [love2d/love#1587]
I downloaded love an it's not opening. I checked to make sure it was downloaded by typing `love --version` and it showed the version of love, which is LOVE 11.3

When I run the application it's not running and when i run it using dedicated graphics card, a window pops up and closes within a second.

Any idea what's causing it?

**Comment by slime73** [comment]
Is this the same issue you're talking about, or is it a separate problem? https://love2d.org/forums/viewtopic.php?f=3&t=88944
