### ISSUE TITLE
love: error while loading shared libraries:

### ISSUE THREAD

**Issue by paxth** [love2d/love#1589]
So Love for my ubuuntu 20.04 isn't working. I need love to work on my assignments and projects. When i downloaded the latest version  of love, it worked fine from terminal when i typed `love` or `love --version`  but i couldn't run my lua files through that. It showed me this error:
![image](https://user-images.githubusercontent.com/63995679/84677551-801d4a80-af4c-11ea-8fb1-466ccc6ff63c.png)

Then i read a guide that i need to downgrade love to make it work for lua files, so i followed this guide:
https://davcri.github.io/posts/cs50-install-love2d-on-linux/

But now when i type `love` in terminal it shows me this:

love: error while loading shared libraries: liblove.so.0: cannot open shared object file: No such file or directory

Can anyone please help me with this

**Comment by paxth** [comment]
I'm sorry if this has been asked before but I've tried a lot and couldn't find a solution so came here

**Comment by slime73** [comment]
Did you install `liblove` as well as `love`, like the guide showed?
```
sudo dpkg -i liblove0_0.10.2ppa1_amd64.deb
```

**Comment by paxth** [comment]
> Did you install `liblove` as well as `love`, like the guide showed?
> 
> ```
> sudo dpkg -i liblove0_0.10.2ppa1_amd64.deb
> ```

Yeah i did everything. But it keeps on saying the same thing

**Comment by MikuAuahDark** [comment]
Can you confirm `liblove.so.0` available in `/usr/lib/x86_64-linux-gnu`? If yes, try to flush the ldconfig cache with `sudo ldconfig`.

Also please put the output of `/lib64/ld*.so* --list $(which love)`

**Comment by paxth** [comment]
> Can you confirm `liblove.so.0` available in `/usr/lib/x86_64-linux-gnu`? If yes, try to flush the ldconfig cache with `sudo ldconfig`.
> 
> Also please put the output of `/lib64/ld*.so* --list $(which love)`

well i can neither find `liblove.so.0` not ca I open the ld*.so* . But it does exist

what do i do now? Sorry if i seem like such a rookie

**Comment by MikuAuahDark** [comment]
You sure the liblove is installed as slime said right? In this case it's better to compile from source or get AppImage at https://github.com/pfirsich/love-appimages/releases
