### ISSUE TITLE
request: love should be able to launch a file

### ISSUE THREAD

**Issue by radgeRayden** [love2d/love#1591]
It would be convenient to be able to specify a custom entry point instead of a directory containing a `main.lua` file. This could be implemented as a command-line flag, or simply by passing a path finishing in `.lua` (and/or dropping a lua file into the nogame screen).

**Comment by Alloyed** [comment]
what would the source directory be in that case? the directory the entry point is in? the current directory? manually specified?

**Comment by radgeRayden** [comment]
Normally if we're thinking of a 'script' it would make the most sense to use the working directory, but since it's a game that could depend on other files and such it might be better to use the directory the file is in. 
I can see a use case for the former, but for my use case - sketching quick ideas in a single file - it doesn't really matter.

**Comment by slime73** [comment]
This is implemented in commit da1271e.
