### ISSUE TITLE
Readable depth buffer with gamma correction (LOVE stops responding).

### ISSUE THREAD

**Issue by rozenmad** [love2d/love#1592]
LOVE 11.3 stops responding when i'm creating readable canvas with any depth formats with enabled gamma correction in conf.lua. It happens only on IntelHD 3000.
Example:
```lua
function love.load(args)
	depth_c = love.graphics.newCanvas(nil, nil, {format = 'depth24', readable = true})
end

function love.draw()
end

function love.update(dt)
end
```

**Comment by slime73** [comment]
Just to make sure I'm not making any wrong assumptions about the issue - it works without freezing when `t.gammacorrect` is not set to true in conf.lua?

**Comment by rozenmad** [comment]
> 
> 
> Just to make sure I'm not making any wrong assumptions about the issue - it works without freezing when `t.gammacorrect` is not set to true in conf.lua?

Yes, it works without gamma correction.

**Comment by slime73** [comment]
I put in a potential workaround, but I don't have the ability to test on that hardware right now - you could try grabbing a windows zip once the CI system builds them.

**Comment by rozenmad** [comment]
Now LOVE starts, but when it's using the depth buffer with gammacorrect = true there's only black screen (only on IntelHD3000).
Example:
```lua
function love.load()
    depth_c = love.graphics.newCanvas(nil, nil, {format = 'depth24', readable = true})
    color_c = love.graphics.newCanvas(nil, nil)
    img = love.graphics.newImage("test.png")
end
function love.draw()
    love.graphics.setCanvas({color_c, depthstencil = depth_c})
    love.graphics.draw(img)
    love.graphics.setCanvas()

    love.graphics.draw(color_c)
end
```

There is another strange thing on IntelHD3000 (without using the depth buffer), gamma correction works like this:
<details>
<summary>Gamma Correction Tests Image</summary>

![test](https://user-images.githubusercontent.com/7805174/87253508-7bcd4a00-c484-11ea-9a2d-4ee4f864502d.png)

</details>

**Comment by slime73** [comment]
It seems like sRGB (gamma correction) support is completely broken on the Intel HD 3000 driver you're using. What OS are you testing with? Are you using the most recent graphics driver available for that GPU? Also, what's the output of `print(love.graphics.getRendererInfo())` on that system?

**Comment by rozenmad** [comment]
OpenGL  3.1.0 - Build 9.17.10.4459      Intel   Intel(R) HD Graphics 3000
OS - Windows 10
Yes, the latest drivers for this GPU are dated 2016.

**Comment by slime73** [comment]
Unfortunately I'm not sure what else can be done on LÖVE's side other than detecting that GPU and driver version combination and deactivating gamma correction support. I have a vague memory of it working on the HD 3000 on Windows at some point in the past, but that may have been a different driver version and different OS version.

**Comment by MikuAuahDark** [comment]
Regarding the gammacorrect test image, I think I remember being able to reproduce that "darkening" image in HD Graphics 3000 with my old GL2.1-only laptop which only has Intel HD Graphics (not 3000 nor 4000). My guess is gammacorrect is completely broken for Intel drivers prior OpenGL 3.3.
