### ISSUE TITLE
SailfishOS support 

### ISSUE THREAD

**Issue by savegame** [love2d/love#1593]
[SailfishOS](https://sailfishos.org/) - its cool linux based mobile OS! And it need more native applications and game engines, and games of course ! ) 
Now i start working with SailfishOS prot of this engine =) 
Its already work nice ( little modified SDL GL initialization) 
In my fork of Love Engine in sailfish branch i working with port. Later will add build instructions ( just need SailfishSDK and my [repo](https://sailfish.openrepos.net/sashikknox/personal/main) with luajit, libmodplug packages, and add -DSAILFISHOS to CXXFLAGS )  

What is done for now: 
- just build engine properly for SailfishOS ( in sailfish SDL2 return driver name as GLESv3, but really sailfish support GLESv2 for now, and it need hardcode when initialize SDL2 GL context )
- build dependencies for Love2D (LuaJIT, libmodplug)

What need to do: 
- sailfish do not rotate users EGL context, it need done in users client application (in love now we can do it inside our app, with love.graphics.rotate and some other manipulations with ) (can be fixed inside lua scripts in every projects (simple), or maybe modify C++ render pipeline in Love2D for Sailfish (not so simple) )
- need add pulseaudio implementation of sound in  Love2D ( becauss OpenAL work not properly now ) (not really simple, but simple)
- need add some SDL2 trick for rotating screen in device (its simple)
- no gyroscope, accelerometer events (not simple)
- Gamepad SDL2 implementation not work in Sailfish, need rewrite it directly to libinput events handling (it simple)
- disable screen blanking ( need dbus message handling and sending to mce )
- pause application cycle and sound when application is not maximized (can be done in script in any project, but better do it inside C++ code, or do it as additional option in any Love Application (when application developer whant to make his app work in background) )

P.S. later i'll add PR to repo ;-)

**Comment by MikuAuahDark** [comment]
Here's my thoughts:

> sailfish do not rotate users EGL context, it need done in users client application

This is bit unfortunate. Normally screen gets rotated because user changed their screen orientation.

> need add pulseaudio implementation of sound in Love2D ( becauss OpenAL work not properly now )

LOVE uses [OpenAL-soft](https://github.com/kcat/openal-soft/tree/openal-soft-1.19.1) in Windows, Linux, macOS, and Android. I checked and OpenAL-soft has PulseAudio backend. If you fail to compile OpenAL-soft then you may consider reporting upstream.

> no gyroscope, accelerometer events

This is completely optional. LOVE in mobile expose accelerometer as joystick controller which tells SDL to do so. https://github.com/love2d/love/blob/cd6bbc129953f3efb5f0a6fa4c0a897c5d4513bf/src/modules/love/love.cpp#L570-L575

> pause application cycle and sound when application is not maximized

All LOVE apps doesn't have to run in background as it's meant for games in mind. My suggestion is to send `love.focus(false)` event prior pausing the whole application.

**Comment by savegame** [comment]
@MikuAuahDark,  i have *little* question : 
**did LOVE have some settings for allowed orientation on target device ( if user want use only landscape orientation on device, and don't want receive messages when orientation is portrait )?** or its setting only in *.plist and AndroidManifest.xml files for target platform? In sailfish, this can be sett only in code. 
Now, for changing content orientation in SailfishOS ( [link to code](https://github.com/savegame/love/blob/539cebe6acebd3e9bc9a233b80839e1d158c7b77/src/modules/event/sdl/Event.cpp#L379) ), i use: 
```c
SDL_SetHintWithPriority(SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION, txt2, SDL_HINT_OVERRIDE) 
/* where txt2 can be
"landscape" 
"inverted-landscape" -- equal "landscapeflipped" 
"portrait"
"inverted-portrait"  -- equal "portraitflipped"
*/
```
SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION - do not rotate render context, its just tell  to SailfishOS  current application orientation (for using right gestures from edge of screen). 
With lua, i add global canvas and set it as render target, before start drawing. After drawing is end, i just draw canvas with right position and rotation ( for current display orientation ). 
```lua
-- main canvas
local main_canvas = nil
local prev_canvas = nil
-- begin draw function (emty initialized)
local begin_draw = function () end
-- implement 2 versions of begin draw
local set_canvas = function ()
    if love.graphics.getCanvas() ~= main_canvas then
       prev_canvas = love.graphics.getCanvas()
    end
    love.graphics.setCanvas( main_canvas )
    love.graphics.clear() -- if we want cleared backbuffer
end

local create_canvas = function ()
   main_canvas = nil
    local w = lg_getWidth() -- explanation of lg_getWidth is below
    local h = lg_getHeight()  -- explanation of lg_getHeight is below
    if  love.window.getDisplayOrientation()  == "landscape" or  love.window.getDisplayOrientation()  == "landscapeflipped" then
        w = lg_getHeight()
        h = lg_getWidth()
    end
    main_canvas = love.graphics.newCanvas(w,h)
    print("Canvas was recreated to "..w.."x"..h)
    set_canvas()
    begin_draw = set_canvas
end
-- if canvas is  empty, create it
if main_canvas == nil then
    begin_draw = set_canvas
else
    begin_draw = set_canvas
end
-- render buffer should be renewed in
function love.displayrotated(index, orientation)
    --[[ 
    here code, if we change from any portrait orientation to landscape, we should recreate main_canvas,
    just set  begin_draw = set_canvas
    --]]
end
-- and use it like this
function love.draw()
    begin_draw
    -- draw here all we want 
    end_draw -- final render
end
```
I replace `love.graphics.getWidth` and `love.graphics.getHeight` with my implementation (where i swapping screens width and  height for landscape), 
```lua
-- first store real functions
local lg_getWidth = love.graphics.getWidth
local lg_getHeight = love.graphics.getHeight
-- then write own implementation 
love.graphics.getWidth = function ()
    if  love.window.getDisplayOrientation() == "landscape"
        or  love.window.getDisplayOrientation() == "landscapeflipped" then
        return lg_getHeight()
    end
    return lg_getWidth()
end

 love.graphics.getHeight = function ()
    if  love.window.getDisplayOrientation() == "portrait"
        or love.window.getDisplayOrientation() == "portraitflipped" then
        return lg_getHeight()
    end
    return lg_getWidth()
end
```
and add some functions for right interpolation of touch and mouse coordinates in different orientations.
```lua
local function xy(x,y) 
    if love.window.getDisplayOrientation() == "portrait" then
        return x,y
    elseif love.window.getDisplayOrientation() == "portraitflipped" then
        return lg_getWidth() - x,lg_getHeight() - y
    elseif love.window.getDisplayOrientation() == "landscape" then
        return y, lg_getWidth() - x
    elseif love.window.getDisplayOrientation() == "landscapeflipped" then
        return lg_getHeight() - y, x
    end
    return y,x
end
```
 With this hacks, i already successfully run few LOVE project on device with landscape orientation. 
I want add this hacks to main code of LOVE ( in C++, only if defined LOVE_SAILFISH macro ): 
- in Events code, for computing right `x,y` for mouse and touch events
- in Graphics (don't know where, i don't search for it now, it would be great if you tell me where main love drawing function is implemented)

**Comment by MikuAuahDark** [comment]
I don't know much about iOS, but in Android, at least the [love-android](https://github.com/love2d/love-android) master branch, user can freely rotate screen orientation if `t.window.resizable` is set to true. Furthermore, user can select between landscape or portait orientation using `love.window.setMode` alone by specifying landscape or portait screen dimensions, respectively.

**Comment by savegame** [comment]
this little bit tricky, but i understand you, I'll try to do the same in sailfishos: if window `width` more than `height`: this landscape , else portrait ;-)

**Comment by MikuAuahDark** [comment]
Note that those mechanism I mentioned before is handled by SDL, not LOVE. So you may consider submitting patches to SDL too instead of working it around in LOVE code.

**Comment by savegame** [comment]
Oh, ok, need look in to SDL sources for understanding - is it work in QtWayland (in SailfishOS) or not ... (but seems is not)
And how about this:
> in Graphics (don't know where, i don't search for it now, it would be great if you tell me where main love drawing function is implemented)

where is in love src situated main draw function ( if it has something like this ), or need modify wrap functions, where call callback for `love.draw` ?
what is the best way to add render buffer globally in LOVE (for SailfishOS platform only, ofcourse ) ?

**Comment by MikuAuahDark** [comment]
LOVE rendering is implemented in `src/modules/graphics` and `src/modules/graphics/opengl` for the OpenGL rendering backend. Note that Metal rendering is also planned in 12.0 so most likely your patches will break, which is why I recommends work with SDL instead like in iOS and Android.

You can modify `love.run` at `src/scripts/boot.lua`, but that's not portable because `love.run` can be replaced by user, tailored for their game requirements.

For the global render buffer, there's #1106 which gets open, so there's no way to add global render buffer to LOVE yet.

**Comment by savegame** [comment]
> most likely your patches will break 

i want add global buffer only for SAILFISHOS (LOVE_SAILFISH macro) platform, it not touch other code, it would be compiled only in Sailfish, it should not brake anything

**Comment by slime73** [comment]
A fork with Sailfish support is a cool thing to have, but I think it's unlikely a PR with those changes will be merged into the main love repository - it puts the burden of maintaining that code on us (people who don't use that OS at all and can't provide real support or keep it working when the codebase changes) for a system that doesn't have widespread use.

Even when bits of code are surrounded by #defines, it would make us choose between potentially breaking support for the OS or holding the rest of the codebase back, whenever we want to change something in an area with those defines. And in that situation, personally I'd choose the former option every time, which kind of defeats the purpose of having support for that OS in the main repository.

**Comment by slime73** [comment]
The [forums](https://love2d.org/forums/index.php) might be a good avenue to post updates about this port.
