### ISSUE TITLE
Using `BezierCurve:render` gives core dumped error

### ISSUE THREAD

**Issue by flamendless** [love2d/love#1597]
Using this code
```lua
local insert = table.insert
local random = love.math.random

local generate_path = function(x, y, n, offset)
	local offset = offset or 8
	local points = {x, y}
	local prev_x = x
	local prev_y = y

	for i = 1, n do
		local px = random(prev_x + -offset, prev_x + offset)
		local py = random(prev_y + -offset, prev_y + offset)
		prev_x = px
		prev_y = py
		insert(points, px)
		insert(points, py)
	end
	insert(points, x)
	insert(points, y)

	return love.math.newBezierCurve(unpack(points))
end

local obj = {}
function love.load()
	for i = 1, 10 do
		local x = random(300, 600)
		local y = random(300, 600)
		local path = generate_path(x, y, 32, 8)
		local o = {
			x = x,
			y = y,
			path = path
		}
		insert(obj, o)
	end
end

function love.draw()
	love.graphics.setColor(1, 0, 0, 0.5)

	--ERROR when in draw function
	for i = 1, #obj do
		local o = obj[i]
		love.graphics.line(o.path:render())
	end
end
```
it gives error like `munmap_chunk(): invalid pointer` and `free(): invalid next size (normal)`

**Comment by MikuAuahDark** [comment]
Just to make sure it's not problem with `love.graphics.line` which I think is fixed in 96b8d29a5c94e7b2f5670276f04834860b0f44bd, do you compile LOVE from source and using the master branch?

**Comment by flamendless** [comment]
I'm only using the binary provided in the AUR

**Comment by MikuAuahDark** [comment]
I think that's out of date since that `love.graphics.line` fix come
recently.

Pada tanggal Min, 12 Jul 2020 14.43, Brandon Blanker Lim-it <
notifications@github.com> menulis:

**Comment by flamendless** [comment]
I cant compile from source right now coz of limited bandwidth and data as well. 

The drawing of `BezierCurve` is not needed in my project so I can just not use it.

**Comment by slime73** [comment]
I've tested the code locally with some internal debug logs added and https://github.com/love2d/love/commit/96b8d29a5c94e7b2f5670276f04834860b0f44bd should fix it.
