### ISSUE TITLE
Low-level (GL) buffer objects API.

### ISSUE THREAD

**Issue by ImagicTheCat** [love2d/love#1598]
Is a low-level API for buffer objects like UBO or SSBO something that could be expected from future LÖVE versions ? I saw some issues around the subject, but mostly about mesh. Beyond meshes, it could also be used for advanced stuff like voxels or simulation and avoiding a high-level API for every use case.

I suppose it also depends on what OpenGL version is aimed by LÖVE.

**Comment by slime73** [comment]
> Is a low-level API for buffer objects like UBO or SSBO something that could be expected from future LÖVE versions ?

Yes: https://github.com/love2d/love/compare/12.0-development...slime73:GraphicsBuffer

The first versions of that API might only support one or two different types of buffers (e.g. maybe just vertex and index buffers to start), but the goal is to extend it to support SSBOs and maybe UBOs in the future as well.

**Comment by ImagicTheCat** [comment]
Nice.

**Comment by slime73** [comment]
That branch has just merged into the 12.0-development branch. Buffer types aside from vertex and index buffers will come a bit later.

**Comment by ImagicTheCat** [comment]
Is there a rough documentation of the current experimental buffer API ?

**Comment by slime73** [comment]
There isn't any formal documentation yet but I have some sample code that uses a texel buffer: https://gist.github.com/slime73/ce82920a5cd697b251f0227375588178

**Comment by slime73** [comment]
Yes, the current function prototype for setArrayData is: `Buffer:setArrayData(data [, startindex] [, count])`. `startindex` is 1-based.

**Comment by ImagicTheCat** [comment]
Yes, but this index is for the write/dst offset, not the read/src offset.

**Comment by slime73** [comment]
Ah, sorry, you're right - it would be useful to have a source index or offset parameter.

**Comment by slime73** [comment]
The API now has that, as well as support for vertex, index, texel, and shader storage buffers. The latter two are read-only in vertex/pixel shaders. I don't intend to add shader write support for those except in compute shaders.
