### ISSUE TITLE
No objects rendering

### ISSUE THREAD

**Issue by xxkfqz** [love2d/love#1601]
I built Love from source on Gentoo x86_64 and I get this when I run it without specifying any directory:
![Screenshot_20200801_134945](https://user-images.githubusercontent.com/52203435/89098157-694c8d80-d3fe-11ea-87d5-479cc6e5a682.png)

Some images are drawn in [mari0](https://github.com/Stabyourself/mari0):
![Screenshot_20200801_140241](https://user-images.githubusercontent.com/52203435/89098314-de6c9280-d3ff-11ea-81f5-139b3d8afdb3.png)
![Screenshot_20200801_140307](https://user-images.githubusercontent.com/52203435/89098315-df052900-d3ff-11ea-83ec-241a213248be.png)

At first I thought the problem was with libsdl2, mesa or graphics card drivers (AMD Radeon 5500XT with open-source drivers), but C programs (like [this](https://github.com/xyproto/sdl2-examples/blob/master/c11/main.c)) draw images just fine, as does prboom-plus.

Prebuilded Love from Ubuntu *.deb package on my system doesn't works too.

I also compiled Love on my Asus Eee PC 1001HA with Intel HD graphics and there it works as should.

**Comment by slime73** [comment]
The titlebar in the first screenshot shows LÖVE 11.1 - can you try 11.3, and if that doesn't work maybe also the latest code from github?

**Comment by xxkfqz** [comment]
@slime73 I tried the version from commit 5f4d2f3323ca81678fb674d9117c5c78c30f3007. Everything is working!
