### ISSUE TITLE
love.graphics.newVolumeImage() and mipmaps

### ISSUE THREAD

**Issue by Luke100000** [love2d/love#1602]
```lua
love.graphics.newVolumeImage({
    {m[1], m[1], m[1], m[1], m[1], m[1], m[1], m[1]},
    {m[2], m[2], m[2], m[2]},
    {m[3], m[3]},
    {m[4]},
})
```
m is an array with 4 rgba8 imageData, 8px, 4px, 2px, 1px.
The result should be a volume image, 8x8x8px, with 3 additional mipmapping levels.
The format of the input table equals the instruction on the löve wiki.
Throws error "bad argument #6 to 'newVolumeImage' (ImageData expected, got nil)" where #6 equals the number of args I pass. If I pass 50 random args its #57

ArrayImage, with its slightly different input table, works fine.

**Comment by slime73** [comment]
Thanks for the easy repro!
