### ISSUE TITLE
Make gl_PointSize writable in vertex shader

### ISSUE THREAD

**Issue by elemel** [love2d/love#1603]
Have you considered making `gl_PointSize` writable in the vertex shader? Right now I can only set a global point size with `love.graphics.setPointSize` before drawing a point mesh. I managed to make it writable per vertex by patching the LÖVE source with `glEnable(GL_PROGRAM_POINT_SIZE);` in `src/modules/graphics/opengl/Graphics.cpp`.

**Comment by slime73** [comment]
What do you plan to use variable-sized points for? I've always considered regular sprites a lot more useful (especially considering differences in implementations of point clipping etc. across different graphics drivers).

**Comment by elemel** [comment]
Experimenting with different surface representations generated from CSG models. Points seem potentially cheaper than sprites/disks if you want to draw a lot of them. Probably can't make a good case for adding support for it currently, and I don't have enough experience with the compatibility/portability concerns that you mention. Just wanted to ask since it looked like it was almost available in vanilla LÖVE.

**Comment by elemel** [comment]
Read up a little on point clipping... Kind of surprised and disappointed that OpenGL requires points to be clipped by center rather than bounds.

https://www.khronos.org/opengl/wiki/Vertex_Post-Processing#Clipping

Also found this hack that should be sufficient for my current needs:

https://love2d.org/forums/viewtopic.php?f=4&t=83986&p=212835#p212829

```lua
ffi.cdef([[
    typedef void (* PFNGLENABLEPROC) (int cap);
    void *SDL_GL_GetProcAddress(const char *proc);
  ]])  
  ffi.cast("PFNGLENABLEPROC",ffi.C.SDL_GL_GetProcAddress("glEnable"))(0x0B71)
```

**Comment by slime73** [comment]
694d448 adds this functionality
