### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by elguoshiy** [love2d/love#1604]
I got an issue where the AI is overlapping each other, I am making a game where if you get a cell, you'll multiply and the other cells are AI.
![image](https://user-images.githubusercontent.com/61806028/89411767-dd987100-d71d-11ea-8f39-1cf27645cfb0.png)
The red is me , the blue is the AI, when we both stop we don't overlap.
![image](https://user-images.githubusercontent.com/61806028/89412554-361c3e00-d71f-11ea-864a-b4c533dd74e2.png)

We two AI are spawned they both overlap each other.
Here is my code for player.lua:

playerBots = {}
player = {}
player.x = 60
player.y = 60
player.w = 55
player.h = 55
player.speed = 400
player.size = 55

function PlayerUpdate(dt)
  if love.keyboard.isDown('w') and player.y > 0 + player.size then
player.y = player.y  - player.speed * dt
end

if love.keyboard.isDown('s') and player.y < love.graphics.getHeight() - player.size  then
player.y = player.y  + player.speed * dt
end

if love.keyboard.isDown('a') and player.x > 0 + player.size then
player.x = player.x  - player.speed * dt
end

if love.keyboard.isDown('d') and player.x < love.graphics.getWidth() - player.size  then
player.x = player.x  + player.speed * dt
end

for i, pb in ipairs(playerBots) do
  pb.x = pb.x + math.cos(player_playerBot_angle(pb)) * pb.speed * dt
  pb.y = pb.y + math.sin(player_playerBot_angle(pb)) * pb.speed * dt
end

for i, pb in ipairs(playerBots) do
if DistanceBetween(player.x, pb.x, player.y, pb.y) < 60 then
  pb.speed = 0
else
  pb.speed = 250
end

end

end

function player_playerBot_angle(playerBot)
return math.atan2(player.y - playerBot.y, player.x - playerBot.x)
end

function DistanceBetween(x1,x2,y1,y2)
return math.sqrt((x2 - x1)^2 + (y2 - y1)^2)
end

function PlayerSpawn()
playerBot = {}
playerBot.x = player.x - 10
playerBot.y = player.y - 10
playerBot.speed = 250
playerBot.size = player.size

table.insert(playerBots, playerBot)
end

**Comment by LavenderTheGreat** [comment]
Heya, this might be more of a problem with your code by the looks of things rather than with LOVE itself, so I recommend you ask it in the Discord [here](https://discord.gg/gnEyke) where we'll be happy to assist you!
