### ISSUE TITLE
love.errorhandler should point to the default implementation

### ISSUE THREAD

**Issue by Nelvin** [love2d/love#1606]
love.errorhandler is nil by default (boot.lua) and in case of an error the old love.errhand is used instead (if client code didn't implement an errorhandler).

love.errorhandler should point to the default handler so adding a custom handler and still calling the default one doens't require to use the old love.errhand which, I guess, will be removed in the future.

**Comment by MikuAuahDark** [comment]
`love.errhand` is deprecated in 11.0 and will be removed in 12.0.

**Comment by Nelvin** [comment]
I know, but look at the sources, right now what's still used in the most current version of the sources *is* errhand instead of errorhandler which is, what this issue is about.

https://github.com/love2d/love/blob/5f4d2f3323ca81678fb674d9117c5c78c30f3007/src/scripts/boot.lua#L640
https://github.com/love2d/love/blob/5f4d2f3323ca81678fb674d9117c5c78c30f3007/src/scripts/boot.lua#L774

I wrote my own error handler and wanted to keep using the default errorhandler which simply does not work right now when using errorhandler (as that's nil) instead of the deprecated errhand.

**Comment by slime73** [comment]
As per the original commit https://github.com/love2d/love/commit/9654376bddac22bed1280dd96cb523f779274241 it's implemented that way to avoid problems with existing user code.

> I wrote my own error handler and wanted to keep using the default errorhandler

You mean calling the original implementation from within your custom one? Can't you just do `local original = love.errorhandler or love.errhand`?

**Comment by Nelvin** [comment]
Of course I can and obviously did :) 

But someone who can't/won't look into Löves sources when trying to add his own error handler like that will just get a silent crash and does not know why.

So if anything I'd add love.errorhandler = love.errhand to boot.lua so both will work.

**Comment by slime73** [comment]
> I'd add love.errorhandler = love.errhand to boot.lua so both will work.

Wouldn't that prevent existing user-defined `love.errhand` functions from working? As AuahDark says, errhand will be removed in love 12, but it is still meant to work in love 11.

**Comment by Nelvin** [comment]
I don't get why it would be more safe to copy the code of the default handler and use that code that may have been changed for a reason leaving me with a potentially worse implementation compared to just calling the default one?

A solution/fallback would've been to define the default handler as a local function, assign it to errhand and errorhandler and once an error is triggered test if errhand and errorhandler are the same, if so, just call the handler, if not test which one is different from the default one and call that. Of course there's still the potential problem that a client redefines both with different implementations. I don't have an idea for that case.

In the end, I don't care - found the problem and workaround, so I'm fine :)
