### ISSUE TITLE
ByteData as function argument for math.Transform

### ISSUE THREAD

**Issue by rozenmad** [love2d/love#1608]
It would be nice to let the Transform object get ByteData as a function parameter. (for love.math.newTransform and setMatrix).

Transform does not have support for 3-dimensional transformations, and this fact forces me to use my own class for matrices based on ByteData. However, if Transform had support for 3D transforms, the first problem would disappear.
Can we expect any of this in the future?

**Comment by MikuAuahDark** [comment]
3-dimensional transformation can be "done" by creating temporary `Transform` object (referred as `dummyTransform` from now on), calling `dummyTransform:setMatrix` by setting the individual matrices, then calling `Transform:apply(dummyTransform)`. Example 3-dimensional translate can be defined as follows.

```lua
local dummyTransform = love.math.newTransform()

local function translate3D(transform, x, y, z)
    dummyTransform:setMatrix("row",
        1, 0, 0, x,
        0, 1, 0, y,
        0, 0, 1, z,
        0, 0, 0, 1)
    return transform:apply(dummyTransform)
end
```

Side note: `Transform` object is internally 4x4 matrices.

**Comment by slime73** [comment]
As AuahDark says I think what you want can be accomplished by setMatrix. You might not not even need the second Transform, if you want to replace the transformation entirely.
