### ISSUE TITLE
Box2D fixture restitution incorrect unless the collision hits hard enough

### ISSUE THREAD

**Issue by thegrb93** [love2d/love#1611]
I've set the restitution here to 2 to illustrate the effect. It doesn't bounce with restitution of 2 unless I make the collision hit hard enough.

https://streamable.com/tlp9ag

**Comment by FlamingArr** [comment]
I doubt how this can be a issue with löve itself as it doesn't do any modification to box2d except changing the b2Assert to throw love's exceptions instead of doing a C assert iirc, Löve, however currently uses a older version of box2d though...

**Comment by thegrb93** [comment]
Perhaps an update would solve the issue. I might try that in a minute. I'm going to post another issue I found though in a second.

**Comment by thegrb93** [comment]
I'll start trying to compile love with the latest box2d

**Comment by thegrb93** [comment]
Ok 250 errors, this might take a little while.

**Comment by thegrb93** [comment]
I think the line I found here https://github.com/love2d/love/issues/1612 is somewhat responsible.

**Comment by thegrb93** [comment]
Ok, I got it compiled, but had the same issue still. Turns out the physics library I was using had `love.physics.setMeter(32)` in it so that was causing the issues.

**Comment by thegrb93** [comment]
I can pull the Box2D update if u guys are interested

**Comment by thegrb93** [comment]
Only caveat is ChainShape and EdgeShape require a 'nextVertex' and 'prevVertex' now; so those functions will have to change.
