### ISSUE TITLE
Error  main.lua:52: attempt to get length of global 'zombies' (a nil value) 

### ISSUE THREAD

**Issue by ZackGaming101** [love2d/love#1619]
Hi so I have had problems making this zombie game and I have a particular error which is the title of this comment you could call it. I have been stuck for a long time and I was wondering if anyone could solve the mistake I  will drop both of the files in here. they are both .lua I just compressed them
[collision.lua.zip](https://github.com/love2d/love/files/5148141/collision.lua.zip)
[main.lua.zip](https://github.com/love2d/love/files/5148142/main.lua.zip)

**Comment by MikuAuahDark** [comment]
Hello, but this is not place to ask for support or general usage of LOVE. This kind of question goes to the [forums](https://love2d.org/forums/) or [Discord](https://discord.gg/rhUets9), thanks.
