### ISSUE TITLE
Bug: touch not working / windows / pens

### ISSUE THREAD

**Issue by Thecoolpeople** [love2d/love#1626]
Hi,
On every Android Device I could find, the Pen always calls the touch event, but on windows, no Pen calls it. (I tested it with 6 different Devices!)
It would be nice, if that bug is fixed soon.

Mouse event is not called. I checked that. Program just didn't react.

Have a good afternoon!
Thecoolpeople

**Comment by slime73** [comment]
SDL (and by extension LÖVE) doesn't support pen input on desktops, currently.
