### ISSUE TITLE
Stuttering on Windows (windowed)

### ISSUE THREAD

**Issue by HDPLocust** [love2d/love#1628]
Love2d with or without vsync has issues with render stuttering/jittering (may be checked with double love.graphics.present: rendered stuff looks like stroboscope) because Windows DWM gets frames in unknown timing.
Some people sync opengl/dx apps with DwmFlush:
https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmflush
And it works (also on fullscreen apps)

I use it with ffi:
```Lua
if love.system.getOS() == "Windows" then
	local ffi = require'ffi'
	local dwm = ffi.load("dwmapi")
	ffi.cdef"void DwmFlush();"
	local oldpresent = love.graphics.present
	function love.graphics.present()
		oldpresent()
		dwm.DwmFlush()
	end
end
```

But it may be useful if someone puts it in LOVE.

**Comment by thegrb93** [comment]
I don't get any stuttering. wdym?

**Comment by slime73** [comment]
> And it works (also on fullscreen apps)

Does that mean you had stuttering in fullscreen that this prevents? Or it just doesn't do anything negative in fullscreen on your system? Was that with desktop-fullscreen or exclusive fullscreen, or both?

**Comment by thegrb93** [comment]
One thing I did notice is using timer.getTime() for physics updates leads to jitter so I fixed that to the screen refresh rate. Never seen any fps problems though. Maybe try logging an fps counter's results and post them here?

**Comment by slime73** [comment]
> I fixed that to the screen refresh rate.

This is off-topic but that sounds like a bad idea.. for example I use a 120hz monitor and a 60hz monitor on one of my computers. I would expect all games to run at the same rate no matter which monitor the game is in. The typical approach to stable physics simulation is to use an accumulator method to run physics at a fixed rate without depending on frame rate.

**Comment by thegrb93** [comment]
So if you move the window between those two monitors? The refresh rate will change? That's interesting. Yeah, I might look into that.

**Comment by HDPLocust** [comment]
> > And it works (also on fullscreen apps)
> 
> Does that mean you had stuttering in fullscreen that this prevents? Or it just doesn't do anything negative in fullscreen on your system? Was that with desktop-fullscreen or exclusive fullscreen, or both?

"It works" means "it makes 60fps on fullscreen with love-vsync off".

**Comment by HDPLocust** [comment]
> I don't get any stuttering. wdym?
You might not have noticed it.
What it looks like in the video is what it looks like in the game. It looks like dropped frames or something similar.[](url)
https://vimeo.com/user109337190/review/462438403/6be45d4c8f

**Comment by slime73** [comment]
> You might not have noticed it.

The issue is specific to certain GPUs and graphics drivers, I believe.

**Comment by HDPLocust** [comment]
> > You might not have noticed it.
> 
> The issue is specific to certain GPUs and graphics drivers, I believe.

I check it with:
1. Windows 7, Intel HD 4000
2. Windows 8.1, Nvidia GT720
3. Windows 10 Nvidia GTX1660Ti
On my friends Radeons it appears too.

The problem is windows desctop window manager, it not synced with sdl-window.

**Comment by HDPLocust** [comment]
(gif 4 times slowdowned)
default: 
![ezgif-6-78f652e3892c](https://user-images.githubusercontent.com/13125395/94377541-68e52000-012b-11eb-93ec-e4350df25a08.gif)
DwmFlush: 
![ezgif-6-97e9c7dfe651](https://user-images.githubusercontent.com/13125395/94377552-79959600-012b-11eb-8a81-f81f871aee89.gif)

**Comment by endlesstravel** [comment]
i have the same issue on `windows 10 / amd 2600x / gtx 1050 ti  / vsync 60 hz` , but i used the [Love2dCS](https://github.com/endlesstravel/Love2dCS) (C# version of love) : 
the program will stuttering on `love.graphics.present` , about once every 5 seconds it will freeze 60 ms.
this is considered to be related to C# GC, the freeze status is different on C# implement  `.netframework 4.5` / `dotnetcore 3.1` / `.net5`
but now:
after i call `DwmFlush` before  `love.graphics.present`, i get less then 20 ~30 ms relieve on stuttering .:

* the freeze  frame record, [before]:
![image](https://user-images.githubusercontent.com/10757838/94379301-ecb9ff00-0161-11eb-82dd-f16f709f9aa0.png)

* the freeze  frame record, [after]:
![image](https://user-images.githubusercontent.com/10757838/94379348-402c4d00-0162-11eb-9f93-211fc46ce4d1.png)

I'm sure the problem has something to do with GC, but `DWM` has relevance to do with it as well after i test the api `DwmFlush`.

**Comment by zorggn** [comment]
On Win7 x64 with GTX1650 latest drivers, this completely eliminated my visual (micro?)stutter issues... with or without löve's vsync being set to 0 or not, since this will force sync to 60Hz (maybe it'll force it to other values if other screens are set to use different refresh rates? i couldn't test that).

The only issue with it is that it does introduce momentary stutter when the window is un/re-focused, or if it's moved by mouse, which didn't happen without it.

**Comment by HDPLocust** [comment]
> completely eliminated my visual (micro?)stutter issues
Also it disappears on 121 and more fps (241fps on 120hz screens) because of [Nyquist-Shannon theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem), but if we can fix it on wide range Windows and drivers versions, why not?

**Comment by slime73** [comment]
I haven't been able to reproduce the issue to the degree that it happens in those gifs (that likely has to do with other things being composited on your system etc), but I've put in a change to use it here: https://github.com/love2d/love/commit/5dd4a463beba7eb956f881b73f6d5572105768e3

It seems very delicate in terms of potential side effects, so I'd appreciate any sort of testing anyone wants to do. It only activates in windowed mode and desktop-fullscreen (not exclusive fullscreen), and only when non-adaptive vsync is enabled.

A build with it should be available here shortly: https://ci.appveyor.com/project/AlexSzpakowski/love/builds/35477235

**Comment by MikuAuahDark** [comment]
5dd4a463beba7eb956f881b73f6d5572105768e3 caused heavy stuttering in my laptop running Windows 10 2004 using integrated graphics (Intel HD Graphics 620 with 27.20.100.8681 driver).

Printing the delta time to console, I can see it eratically alternate between 16.67ms and 33.33ms like
```
32.6911
18.162
15.8922
32.4313
17.9072
16.6764
33.9829
15.9993
32.2744
17.0747
17.2684
16.4797
33.0312
17.0406
17.0162
16.0592
33.0121
16.9929
16.8723
17.0406
16.9015
16.5148
32.763
17.0374
16.5379
32.9344
17.063
15.7637
```

This does not happen when using dGPU or iGPU without that commit applied.

**Comment by HDPLocust** [comment]
> It seems very delicate in terms of potential side effects, so I'd appreciate any sort of testing anyone wants to do. It only activates in windowed mode and desktop-fullscreen (not exclusive fullscreen), and only when non-adaptive vsync is enabled.

Thank you, I will test it with all my stuff and a lot of people and also if something goes wrong, I will look for a better solution (set of solutions?).

**Comment by HDPLocust** [comment]
> Printing the delta time to console, I can see it eratically alternate between 16.67ms and 33.33ms like

It looks like two sync systems fighting: Love waits love-vsync (one frame) then dwm (second frame), and it alternates with normal rendering when it makes it in time.

**Comment by slime73** [comment]
I'll probably have to revert the change, missing vsync on some systems isn't worth it.

> It looks like two sync systems fighting: Love waits love-vsync (one frame) then dwm (second frame), and it alternates with normal rendering when it makes it in time.

Unfortunately turning vsync off and using DwmFlush as "vsync" isn't going to work - for example on my computer, DwmFlush syncs to my primary monitor's 120hz refresh rate no matter which display the window is on, but I have 60hz secondary monitors which vsync correctly syncs to when the window is in one of those displays.
