### ISSUE TITLE
touch latency on android

### ISSUE THREAD

**Issue by N1ghtSiren** [love2d/love#1629]
I've done some tests and stuck in that touches sometimes not getting registered on android.
Seems like only touches longer than ~70ms going thru and that ruins user experience.
[gif](https://gfycat.com/ru/glaringbountifulaplomadofalcon)

Vsync is off, code is super simple:
```lua
main.lua
local circle = love.graphics.circle
local touches = {}

function love.update(dt)
    --touches
    for i, id in ipairs(love.touch.getTouches()) do
        table.insert(touches,{love.touch.getPosition(id)})
    end
    --mouse
    if(love.mouse.isDown(1))then
        table.insert(touches,{love.mouse.getPosition()})
    end
end

function love.draw()
    for k,v in pairs(touches) do
        circle("fill",v[1], v[2], 30)
        table.remove(touches,k)
    end
end
``` 
build with this: [https://github.com/N1ghtSiren/love2droid/actions/runs/280913008](https://github.com/N1ghtSiren/love2droid/actions/runs/280913008)

game.love+video in [game.zip](https://github.com/love2d/love/files/5307455/game.zip)

**Comment by slime73** [comment]
If you output data from `love.touchpressed` and `love.touchreleased` do the missing touches register there (but not in love.update), or are they gone completely?

**Comment by N1ghtSiren** [comment]
Hm, i didnt tested it yet

**Comment by N1ghtSiren** [comment]
They are not gone, they just registering with delay, not sure if thats related to my not-that-old phone or api itself
As example, [this game](https://play.google.com/store/apps/details?id=com.norubal.ob2v&hl=en_US) also written on love2d and has no issues with delay, but its from 2014
For now, my code:
```lua
local width = love.graphics.getWidth
local printf = love.graphics.printf
local setColor = love.graphics.setColor
local circle = love.graphics.circle
local touches = {}
local touches2 = {}

love.graphics.setFont(love.graphics.newFont("comicsans.ttf", 15))

function love.update(dt)
    --touches
    for i, id in ipairs(love.touch.getTouches()) do
        table.insert(touches,{love.touch.getPosition(id)})
    end
end

function love.draw()
    --green - with love.update
    local i1 = 1
    local i2 = 1

    setColor(0,1,0,1)
    for k,v in pairs(touches) do
        printf(i1.." x: "..v[1]..", y: "..v[2],10,20*i1,999)
        circle("fill",v[1], v[2], 30)
        table.remove(touches,k)
        i1 = i1 + 1
    end

    --red - without love.update
    setColor(1,0,0,1)
    for k,v in pairs(touches2) do
        printf(i2.." x: "..v[1]..", y: "..v[2],width()/2+10,20*i2,999)
        circle("fill",v[1], v[2], 20)
        i2 = i2 + 1
    end
end

function love.touchpressed( id, x, y, dx, dy, pressure )
    touches2[id] = {x,y}
end

function love.touchreleased( id, x, y, dx, dy, pressure )
    touches2[id] = nil
end

function love.touchmoved( id, x, y, dx, dy, pressure )
    touches2[id] = {touches2[id][1]+dx,touches2[id][2]+dy}
end
```

video:
white: default android touch-showing thing from setting
green: love.touch.getTouches called from love.update
red: love.touchpressed/moved/released with no dependencies on love.update
[gif](https://gfycat.com/ru/flatuniquearabianhorse)

[apk](https://github.com/N1ghtSiren/love2droid/actions/runs/281032492)
[Desktop.zip](https://github.com/love2d/love/files/5307895/Desktop.zip) with original video and game.love

+ if you deep analyse it, only one circle affected by love.touchmoved (?)
![image](https://user-images.githubusercontent.com/33629215/94732163-54996100-037f-11eb-82a5-3cc011a226a1.png)
rest 2 circle positions here is same for green and red, not sure if thats my mistake in code, or something within api

**Comment by MikuAuahDark** [comment]
Some phones register three-finger motion as screnshot and that can interfere with the latency of the touch events received by LOVE.

**Comment by creshbunny** [comment]
I think this is an informative post and it is very useful and knowledgeable [Hotmail](https://hotmailvs.com)

**Comment by MikuAuahDark** [comment]
I tested this and I can confirm I see same delay as in your screen. However, this may related to (recent version of) SDL. LOVE 11.3 for Android uses SDL 2.0.10 and in my development build (my own API30 branch) it uses SDL 2.0.12.

I'll keep this open for a while.

**Comment by MikuAuahDark** [comment]
I retested this in my touchscreen laptop and see same issue, so I think this is by design(?)

Feel free to reopen if this isn't the case.
