### ISSUE TITLE
Shader issue from LÖVE 11.3 to 12.

### ISSUE THREAD

**Issue by ImagicTheCat** [love2d/love#1631]
I have an error with the v12 branch compared to the stable version with the same shader, at this specific line:
```glsl
float soft = clamp(brightness-bloom_curve.y, 0, bloom_curve.z);
```
`brightness` and `bloom_curve` are `float` and `vec4`. The issue is gone with `0.0` instead (now I understand why it is explicitly used everywhere online, I thought there was some kind of deduction, but it seems to be unreliable). Nonetheless, the error hints double ?

```
Error: Error validating pixel shader code:
Line 26: ERROR: 'clamp' : ambiguous function signature match: multiple signatures match under implicit type conversion 
Line 26: ERROR: '=' :  cannot convert from ' global double' to ' temp float'
Line 26: ERROR: '' : compilation terminated 
```

**Comment by slime73** [comment]
I think https://github.com/love2d/love/commit/d083c87d74f9079190505cd1366f4a4315e6a528 should fix it.
