### ISSUE TITLE
Inertial scrolling support on macOS 

### ISSUE THREAD

**Issue by molevision** [love2d/love#1632]
It would be a massive help to have a way to enable macOS' built in inertial scrolling when reading mousewheel inputs, to get parity when designing interfaces inside love2d. Manually recreating the inertia is harder than simply enabling it through SDL, [like someone has already done here.](https://gist.github.com/josephg/a54367b678e6c38c38e6e247f97b1624)

Thank you.

**Comment by selenagobella** [comment]
Great post, you have pointed out some fantastic details , I too conceive this s a very fantastic website [freecell](https://free-cell.co)

**Comment by molevision** [comment]
To implement natural direction, smooth scrolling.

```
function love.wheelmoved(dx, dy)
    vel.x = vel.x - dx * 80
    vel.y = vel.y + dy * 80
end

function love.update(dt)
    if vel.x ~= 0 or vel.y ~= 0 then
        --scrolling actions go here
    end
    -- Gradually reduce the velocity to create smooth scrolling effect.
    vel.x = limit(vel.x - vel.x * math.min(dt * 10, 1), 0, 0.01)
    vel.y = limit(vel.y - vel.y * math.min(dt * 10, 1), 0, 0.01)
end

function limit(num, centre, range)
    if centre - range < num and num < centre + range then num = centre end
    return num
end
```
