### ISSUE TITLE
Multi-touch support for trackpads and touch displays

### ISSUE THREAD

**Issue by vaner-org** [love2d/love#1633]
Allowing the trackpad under macOS to trigger pre-exisiting love.touch functionality through SDL's native SDL_TouchFingerEvent [(which already supports it)](https://discourse.libsdl.org/t/mac-multitouch/17695/3) would make testing mobile applications on desktop a breeze, and allow gestures for interface navigation (which would be a godsend).

**Comment by slime73** [comment]
Trackpads don't behave like touch screens at all, because there's no correlation between where the user presses the trackpad and a location on the screen.

I added this functionality to SDL relatively recently to account for that difference https://hg.libsdl.org/SDL/rev/eb60e952b13f - I wouldn't feel good about exposing trackpad touches in love without making sure the API made that touch type distinction very clear, so people don't write code that will break when a trackpad is used (especially since end users actually use their trackpad to move the mouse cursor).

**Comment by slime73** [comment]
I described the problem a bit more here https://bugzilla.libsdl.org/show_bug.cgi?id=3542#c1 (although I wrote that before the above APIs were added to SDL).

**Comment by molevision** [comment]
Thank you for the detailed explanation, I understand what you mean.
> Trackpads don't behave like touch screens at all, because there's no correlation between where the user presses the trackpad and a location on the screen.

My hypothetical case of testing mobile apps in Love doesn't make a whole lot of sense, I realise now. Still, I think this is worth including just for the sake of location-agnostic gestures like pinch to zoom or drawing with multi touch. I personally know of a lot of people (myself included) whose programs could benefit from this weird hybrid place the trackpad sits in. Maybe only allowing ignoring the mouse data in favour of trackpad when the mouse has been captured and hidden by the window? Like how Preview accepts signatures.

<img width="580" alt="Screenshot 2020-10-05 at 02 38 02" src="https://user-images.githubusercontent.com/9658355/95027153-01434d80-06b4-11eb-9c46-e1049a3af4d7.png">


> I added this functionality to SDL relatively recently to account for that difference https://hg.libsdl.org/SDL/rev/eb60e952b13f - I wouldn't feel good about exposing trackpad touches in love without making sure the API made that touch type distinction very clear, so people don't write code that will break when a trackpad is used (especially since end users actually use their trackpad to move the mouse cursor).

Is API naming the biggest hurdle here? I'm guessing a love.trackpad class might be too much fragmentation for your liking, which I understand. If not I would be glad to draft documentation that could justify it.

**Comment by zorggn** [comment]
For the sake of cross-platform feature compatibility, how would this work on windows and linux?

**Comment by molevision** [comment]
> For the sake of cross-platform feature compatibility, how would this work on windows and linux?

I was unable to find documentation for a multitouch API in either for trackpads but... [found someone talking about it here, about SDL_MultiGestureEvent](
https://discourse.libsdl.org/t/no-gesture-events-from-touchpad-on-windows-or-linux-why/25205).


Looks to me that Mac has trackpads triggering MultiGestureEvent natively, while Windows and Linux have only touch panels doing the same. So it would benefit all three platforms. :)

**Comment by molevision** [comment]
@slime73 Is the [Touch FFI](https://github.com/slime73/love-snippets/tree/master/Touch) from love-snippets still expected to be functional? Otherwise, would it be non-trivial to get it running with the new SDL functionality you added?

**Comment by lullabyist** [comment]
I have the [Touch FFI](https://github.com/slime73/love-snippets/tree/master/Touch) and therefore trackpad multitouch working when I build love2d with SDL_SetHint(SDL_HINT_MOUSE_TOUCH_EVENTS, "1") added to the int main() in love.cpp.

**Comment by MikuAuahDark** [comment]
AFAIK there's no equivalent API in Windows and Linux for this one, so having it working in all platforms that LOVE supports would be next to impossible.

**Comment by lullabyist** [comment]
But surely there isn't a downside to having the SDL hint enabled by default, since it needs FFI to be usable anyway?

**Comment by MikuAuahDark** [comment]
Not sure but after checking it, `SDL_HINT_MOUSE_TOUCH_EVENTS` is responsible whetever LOVE will also fire `mousepressed`/`moved`/`released` when the input comes from touchscreen and this is enabled by default.
