### ISSUE TITLE
Unable to set line width lower than 1

### ISSUE THREAD

**Issue by antoniotorresm** [love2d/love#1635]
Using 11.3, I'm unable to draw lines with width lower than 1.

![image](https://user-images.githubusercontent.com/17461846/95585485-9a20f280-0a3f-11eb-9a0f-cff7826d4845.png)

```lua
function love.draw()
    love.graphics.setLineWidth(1)
    love.graphics.line(200, 200, 200, 500)
    love.graphics.print("1", 200, 150)

    love.graphics.setLineWidth(0.7)
    love.graphics.line(300, 200, 300, 500)
    love.graphics.print("0.7", 300, 150)


    love.graphics.setLineWidth(0.5)
    love.graphics.line(400, 200, 400, 500)
    love.graphics.print("0.5", 400, 150)


    love.graphics.setLineWidth(0.2)
    love.graphics.line(500, 200, 500, 500)
    love.graphics.print("0.2", 500, 150)

    love.graphics.setLineWidth(0.01)
    love.graphics.line(600, 200, 600, 500)
    love.graphics.print("0.01", 600, 150)
end
```

**Comment by slime73** [comment]
Try `love.graphics.setLineStyle("rough")`.

That being said, a line width less than 1 means the line has less chance of passing through the center of a pixel, which is how GPUs determine whether a pixel is affected by an object or not.

**Comment by antoniotorresm** [comment]
I'm using this on a zoomed view, so there is no problem with lines being thinner than 1 pixel. Using rough as line style seems to fix it. Thank you!
