### ISSUE TITLE
20 sec delayed start when microphone is in use by another program

### ISSUE THREAD

**Issue by llotz** [love2d/love#1643]
I got a Sharkoon Skiller SGH2. I found out that when I used this headset, love2d won't start immediately with a project when the microphone input is in use by one or more applications. Same thing happens with Sharkoon Skiller SGH 30. The 20 sec delay feels like a timeout. When I stop using the mic in another application during the start delay, love2d launches the project immediately. Gonna debug further on but maybe someone already knows a solution for this problem.

**Comment by MikuAuahDark** [comment]
Can you reproduce same issue but with `love.audio` disabled?

**Comment by llotz** [comment]
Yes I can. Somehow disabling the `love.joystick` module makes the delay disappear.

**Comment by slime73** [comment]
A build of the latest code from git uses an updated version of SDL, which might fix it if you're able to try: https://ci.appveyor.com/project/AlexSzpakowski/love/builds/36984535/job/xvbocfrtu5cqj54p/artifacts

**Comment by llotz** [comment]
Your new Build of love2d launches the project the same way 11.2 did. Still only disabling `love.joystick` makes the delay disappear

**Comment by MikuAuahDark** [comment]
It could probably worth filling bug report on SDL instead, since `love.joystick` is handled by SDL.

**Comment by llotz** [comment]
https://bugzilla.libsdl.org/show_bug.cgi?id=5485

**Comment by llotz** [comment]
It's a bug inside the headset driver. Details are in the libsdl bugzilla link. I reported the issue to the vendor. Therefore I'm closing this issue.
