### ISSUE TITLE
Bug in Nvidia Tegra 3 driver

### ISSUE THREAD

**Issue by xordspar0** [love2d/love#1647]
I'm trying to run LÖVE on an Ouya, which has an Nvidia Tegra 3. It supports OpenGL ES 2.0, which [doesn't support 3D textures](http://docs.gl/es3/glTexImage3D#versions). It also doesn't support the [ES 2.0 extension for 3D textures](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_3D.txt).

Currently, LÖVE checks to see if the extension is supported, and if it is, it aliases the functions for easier use later:

https://github.com/love2d/love/blob/0b06d0d1f9defaef0353523012acf918cbc01954/src/modules/graphics/opengl/OpenGL.cpp#L394-L403

On my Ouya, is doesn't matter whether these functions get alias or not, because both the regular versions and the OES versions are NULL.

As a result, I get a segfault during the boot process when LÖVE uses a 3D texture function for the first time:

```
<unknown> 0x0000000000000000
glad::glTexImage3D(unsigned int, int, int, int, int, int, int, unsigned int, unsigned int, void const*) gladfuncs.hpp:376
love::graphics::opengl::OpenGL::rawTexStorage(love::graphics::TextureType, int, love::PixelFormat, bool&, int, int, int) OpenGL.cpp:1171
love::graphics::opengl::OpenGL::createDefaultTexture() OpenGL.cpp:533
love::graphics::opengl::OpenGL::setupContext() OpenGL.cpp:261
love::graphics::opengl::Graphics::setMode(int, int, int, int, bool) Graphics.cpp:167
love::window::sdl::Window::setWindow(int, int, love::window::WindowSettings*) Window.cpp:527
love::window::w_setMode(lua_State*)::$_2::operator()() const wrap_Window.cpp:119
int love::luax_catchexcept<love::window::w_setMode(lua_State*)::$_2>(lua_State*, love::window::w_setMode(lua_State*)::$_2 const&) runtime.h:663
love::window::w_setMode(lua_State*) wrap_Window.cpp:118
lj_BC_FUNCC 0x0000000068df1ed0
love::luax_resume(lua_State*, int) runtime.cpp:971
runlove(int, char**, int&) love.cpp:218
::SDL_main(int, char **) love.cpp:259
Java_org_libsdl_app_SDLActivity_nativeRunMain SDL_android.c:761
dvmPlatformInvoke 0x0000000040749e34
dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) 0x0000000040778dce
dvmJitToInterpNoChain 0x00000000407532a8
```

If I comment out that line I get this segfault:

```
<unknown> 0x0000000000000000
glad::glTexSubImage3D(unsigned int, int, int, int, int, int, int, int, unsigned int, unsigned int, void const*) gladfuncs.hpp:377
love::graphics::opengl::OpenGL::createDefaultTexture() OpenGL.cpp:549
love::graphics::opengl::OpenGL::setupContext() OpenGL.cpp:261
love::graphics::opengl::Graphics::setMode(int, int, int, int, bool) Graphics.cpp:167
love::window::sdl::Window::setWindow(int, int, love::window::WindowSettings*) Window.cpp:527
love::window::w_setMode(lua_State*)::$_2::operator()() const wrap_Window.cpp:119
int love::luax_catchexcept<love::window::w_setMode(lua_State*)::$_2>(lua_State*, love::window::w_setMode(lua_State*)::$_2 const&) runtime.h:663
love::window::w_setMode(lua_State*) wrap_Window.cpp:118
lj_BC_FUNCC 0x0000000068df1db0
love::luax_resume(lua_State*, int) runtime.cpp:971
runlove(int, char**, int&) love.cpp:218
::SDL_main(int, char **) love.cpp:259
Java_org_libsdl_app_SDLActivity_nativeRunMain SDL_android.c:761
dvmPlatformInvoke 0x0000000040749e34
dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) 0x0000000040778dce
dvmJitToInterpNoChain 0x00000000407532a8
```

And finally, if I also comment out that line, I don't get a segfault, but LÖVE successfully catches the following fatal error:

```
Error: [string "boot.lua"]:535: Cannot compile vertex shader code:
    (104) : error C1115: unable to find compatible overloaded function "texture2DArray(sampler2DArray, vec3)"
    
    stack traceback:
    	[string "boot.lua"]:777: in function <[string "boot.lua"]:773>
    	[C]: in function 'setMode'
    	[string "boot.lua"]:535: in function <[string "boot.lua"]:380>
    	[C]: in function 'xpcall'
    	[string "boot.lua"]:787: in function <[string "boot.lua"]:780>
    	[C]: in function 'xpcall'
```

**Comment by slime73** [comment]
LÖVE only hits that glTexImage3D codepath if `GLAD_VERSION_1_1 || GLAD_ES_VERSION_3_0 || GLAD_OES_texture_3D`, so it seems like your graphics driver is probably claiming to support OES_texture_3D (or less likely, GLES3) when it doesn't actually support it.

**Comment by xordspar0** [comment]
Where is the `GLAD_VERSION_1_1 || GLAD_ES_VERSION_3_0 || GLAD_OES_texture_3D` check that you're looking at? I didn't see that when I stepped through this with a debugger. Also, according to the debugger, all of those are `0`.

**Comment by slime73** [comment]
Here: https://github.com/love2d/love/blob/master/src/modules/graphics/opengl/OpenGL.cpp#L1216

Called by createDefaultTexture before it tries anything: https://github.com/love2d/love/blob/master/src/modules/graphics/opengl/OpenGL.cpp#L521

**Comment by slime73** [comment]
If you're using a debugger you could step through that loop and see which codepaths it's taking.

**Comment by xordspar0** [comment]
Awesome, thanks. It looks like `GLAD_OES_texture_3D == 0`, but `GLAD_EXT_texture_array == 1`. This lets textures of type TEXTURE_2D_ARRAY through here:

https://github.com/love2d/love/blob/0b06d0d1f9defaef0353523012acf918cbc01954/src/modules/graphics/opengl/OpenGL.cpp#L1217-L1218

I think the issue is that the [texture arrays extension](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_array.txt) doesn't come with support for the glTexImage3D, etc. functions. It can be used with those functions, but it doesn't define them.

When I do this, I get past the segfaults! :tada: 

```diff
diff --git a/src/modules/graphics/opengl/OpenGL.cpp b/src/modules/graphics/opengl/OpenGL.cpp
index f2fcbb01..12957f46 100644
--- a/src/modules/graphics/opengl/OpenGL.cpp
+++ b/src/modules/graphics/opengl/OpenGL.cpp
@@ -1210,7 +1210,7 @@ bool OpenGL::isTextureTypeSupported(TextureType type) const
        case TEXTURE_VOLUME:
                return GLAD_VERSION_1_1 || GLAD_ES_VERSION_3_0 || GLAD_OES_texture_3D;
        case TEXTURE_2D_ARRAY:
-               return GLAD_VERSION_3_0 || GLAD_ES_VERSION_3_0 || GLAD_EXT_texture_array;
+               return GLAD_VERSION_3_0 || GLAD_ES_VERSION_3_0 || GLAD_OES_texture_3D && GLAD_EXT_texture_array;
        case TEXTURE_CUBE:
                return GLAD_VERSION_1_3 || GLAD_ES_VERSION_2_0;
        default:
```

I still get the following crash though:

```
Error: [string "boot.lua"]:535: Cannot compile vertex shader code:
    (104) : error C1115: unable to find compatible overloaded function "texture2DArray(sampler2DArray, vec3)"
    
    stack traceback:
    	[string "boot.lua"]:777: in function <[string "boot.lua"]:773>
    	[C]: in function 'setMode'
    	[string "boot.lua"]:535: in function <[string "boot.lua"]:380>
    	[C]: in function 'xpcall'
    	[string "boot.lua"]:787: in function <[string "boot.lua"]:780>
    	[C]: in function 'xpcall'
```

**Comment by slime73** [comment]
That's a bug in the driver. EXT_texture_array is only defined in terms of desktop OpenGL (where glTexImage3D always exists) and can't actually work without glTexImage3D to create the texture and upload data to it. The extension won't work within GLES2 contexts and the driver shouldn't be claiming to support it.

There is this GLES2-specific texture array extension: https://www.khronos.org/registry/OpenGL/extensions/NV/NV_texture_array.txt but love's code doesn't make use of it.

**Comment by xordspar0** [comment]
Ok. Got it. Would you be interested in a patch that works around this by checking for `GLAD_ES_VERSION_2_0 && !GLAD_OES_texture_3D` and then disabling the texture array extension?

One more question: what's the best way to disable mark that extension as not supported? I can patch isTextureTypeSupported to work for me, but then there are failures in the default shaders, which also check the GL_EXT_texture_array macro. Is there a way to centrally disable it or would there have to be patches at each place that checks that macro?

**Comment by slime73** [comment]
> checking for GLAD_ES_VERSION_2_0 && !GLAD_OES_texture_3D and then disabling the texture array extension?

I think a better approach for the CPU code might be to always set `GLAD_EXT_texture_array` to false if `GLAD_ES_VERSION_2_0` is true, near the top of `initOpenGLFunctions` (maybe) - with a comment explaining that the Ouya driver is broken. However...

>  there are failures in the default shaders, which also check the GL_EXT_texture_array macro. Is there a way to centrally disable it or would there have to be patches at each place that checks that macro?

Unfortunately this part isn't so easily turned off, since there's no layer between the shader code and the (buggy) driver like there is between the CPU code and the driver. love also has some assumptions in its shader code that about how and when `GL_EXT_texture_array` will be present, that it uses to make GLSL ES 1.0 shader code that uses texture arrays still work, when running on a GLES 3.0 system.
