### ISSUE TITLE
Love2D Taking Too Much RAM

### ISSUE THREAD

**Issue by Winksplorer** [love2d/love#1650]
Version: 11.3

Hi, I Am Making A Space Game With Love2D, When I Run it, Love2D Takes Too Much Ram (up to 16 GB). Please Optimize Love2D so i can make my game better.

**Comment by MikuAuahDark** [comment]
Not sure, but the memory usage of the game is entirely depends on how you code the game. This kind of question should go in our #support Discord channel.
