### ISSUE TITLE
I am trying to solve this thing but it displays : attempt to perform arithematic  on local  (dt) (a nil value), the problem is in update function

### ISSUE THREAD

**Issue by Mst19618** [love2d/love#1651]
Ball = Class {}

function Ball: init(x, y, width, height)
    self.x = x
    self.y = y
    self.width = width
    self.height = height

    self.dx = math.random(2) == 1 and 100 or -100
    self.dy = math.random(-50, 50)
end
function Ball: reset()
    self.x = VIRTUAL_WIDTH / 2 - 2
    self.y = VIRTUAL_HEIGHT / 2 -2

    self.dx = math.random(2) == 1 and -100 or 100
    self.dy = math.random(-50, 50) * 1.5
end

function Ball:update(dt)
    self.x = self.x + self.dx * dt
    self.y = self.y + self.dy * dt
end

function Ball:render()

    love.graphics.rectangle('fill', self.x, self.y, 4, 4)

 end

**Comment by Mst19618** [comment]
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

PADDLE_SPEED= 200

Class = require 'class'
push = require 'push'

require 'Ball'
require 'Paddle'

function love.load()
    math.randomseed(os.time())
    love.graphics.setDefaultFilter('nearest', 'nearest')

    smallFont = love.graphics. newFont('font.ttf', 8)

    scoreFont = love.graphics.newFont('font.ttf',32)

    player1Score = 0
    player2Score = 0

    paddle1 = Paddle(5, 20, 5, 20)
    paddle2 = Paddle(VIRTUAL_WIDTH - 10, VIRTUAL_HEIGHT - 30, 5, 20)
    ball = Ball(VIRTUAL_WIDTH / 2 - 2, VIRTUAL_HEIGHT / 2 - 2, 5, 5)
    
    gameState = 'start'
    
     

    push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEIGHT, {
        fullscreen = false,
        vsync = true,
        resizable = false
    })
end

function love.update(dt)

    paddle1: update(dt)
    paddle2: update(dt)

    if love.keyboard.isDown('w') then
        paddle1.dy = -PADDLE_SPEED
    elseif love.keyboard.isDown('s') then
        paddle1.dy = PADDLE_SPEED
    else
        paddle1.dy = 0
    end
    
    if love.keyboard.isDown('up') then
        paddle2.dy = -PADDLE_SPEED
    elseif love.keyboard.isDown('down') then
        paddle2.dy = PADDLE_SPEED
    else
        paddle2.dy = 0
    end
      
    if gameState == 'play' then 
       ball: update()
    end
end


function love.keypressed(key)
    if key == 'escape' then
        love.event.quit()
    elseif key =='enter' or key == 'return' then
        if gameState == 'start' then
            gameState = 'play'
        elseif gameState == 'play' then
            gameState = 'start'
        ball: reset()
        end
    end
end


function love.draw()

    push:apply('start')

    love.graphics.clear(40/255, 45/255, 52/255 ,255/255)

    love.graphics.setFont(smallFont)

    if gameState == 'start' then
       love.graphics.printf("HELLO Start State!", 0, 20, VIRTUAL_WIDTH, 'center')
    elseif gameState == 'play' then
        love.graphics.printf("HELLO Play State!", 0, 20, VIRTUAL_WIDTH, 'center')
    end

    paddle1 : render()
    paddle2 : render()

    ball: render()
    push:apply('end')

end
this is the main function, please help

**Comment by FlamingArr** [comment]
This seems like an issue with your program rather than an issue with löve itself, please come into the löve forums or ask in the #support channel in the [discord server](https://discord.gg/B7UVM5uQ).

**Comment by slime73** [comment]
your `ball:update` method expects `dt` to be passed as an argument into it, but your code in love.update doesn't do that.

As mentioned above, the forums and the discord server are places where you can ask for help with your own code - this issue tracker is meant to be about love's internal code.
