### ISSUE TITLE
larger sprites look blurry on windows 7 32bit but not on windows 10 64bit

### ISSUE THREAD

**Issue by dnxa** [love2d/love#1652]
here is my code
```
function love.load()
	love.graphics.setDefaultFilter("nearest", "nearest")
	image = love.graphics.newImage("image.png")
end

function love.draw()
	love.graphics.scale(5, 5)
	love.graphics.draw(image,0,0)
end``
```
on win7 its blurry
but not on win10

**Comment by dnxa** [comment]
also its only like that since 0.10.0

**Comment by MikuAuahDark** [comment]
Could you post screenshot on how it's look like?

**Comment by dnxa** [comment]
on 11.3
![Capture1](https://user-images.githubusercontent.com/76252391/102690828-98cf2b80-4221-11eb-8cb7-9aa9069b4362.PNG)
on 0.9.2
![Capture2](https://user-images.githubusercontent.com/76252391/102690836-aab0ce80-4221-11eb-8055-1297bcee4f0d.PNG)

**Comment by MikuAuahDark** [comment]
Looks like the filtering setting (`love.graphics.setDefaultFilter`) is not respected. What's the output of this test code?
```lua
-- main.lua
local renderer = table.concat({love.graphics.getRendererInfo()}, " ")
function love.draw()
    love.graphics.print(renderer)
end
```

Also try launching LOVE with `LOVE_GRAPHICS_USE_GL2=1` environment variable too and see if it still blurs.

**Comment by dnxa** [comment]
OpenGL 3.0 Intel Corporation Intel(R) Graphics Media Accelerator 3600 Series
this laptop is old and bad so that may be the problem
also how do i use `LOVE_GRAPHICS_USE_GL2=1` in love do i just put it in main.lua??

**Comment by MikuAuahDark** [comment]
You could try to add this code snippet in your `conf.lua` https://gist.github.com/MikuAuahDark/2efb38e123240e11702c1ba4f96fbcad

**Comment by dnxa** [comment]
nope its still blurry

**Comment by MikuAuahDark** [comment]
What if you add `image:setFilter("nearest", "nearest")` after creating the image in `love.load`? It probably won't make any difference but just in case.

The best causes I can think of is driver bugs and the solution is to update your graphics driver to latest.

**Comment by dnxa** [comment]
`image:setFilter("nearest", "nearest")` dose nothing
oh well thanks for trying

**Comment by dnxa** [comment]
but 32 by 32 pixel image is just fine
![Capture](https://user-images.githubusercontent.com/76252391/102691783-7ab8f980-4228-11eb-9552-7eb1fd25a88c.PNG)

**Comment by MikuAuahDark** [comment]
Could you try with 64x64, 128x128, 512x512, 1024x1024, and 800x600? I know the last resolution is weird but quick search shows that some older GPUs doesn't respect nearest filtering if the resolution is not power-of-2.

**Comment by dnxa** [comment]
64x64
![64x64](https://user-images.githubusercontent.com/76252391/103106627-7178c400-4650-11eb-9653-4d794452df3a.PNG)
128x128
![128x128](https://user-images.githubusercontent.com/76252391/103106632-7e95b300-4650-11eb-93bb-e4cc6f98f5d2.PNG)
512x512
![512x512](https://user-images.githubusercontent.com/76252391/103106641-8f462900-4650-11eb-9d08-3957dd7323a8.PNG)
1024x1024
![1024x1024](https://user-images.githubusercontent.com/76252391/103106644-a258f900-4650-11eb-8dca-15ca82c5f988.PNG)
800x600
![800x600](https://user-images.githubusercontent.com/76252391/103106655-b3a20580-4650-11eb-87ea-19b8229d5dbd.PNG)

**Comment by dnxa** [comment]
oops sorry this is 128x128 not that
![Uploading 128x128.PNG…]()

**Comment by dnxa** [comment]
oops this is 128x128 not that
![128x128](https://user-images.githubusercontent.com/76252391/103106709-33c86b00-4651-11eb-9b67-990030f345f7.PNG)

**Comment by slime73** [comment]
If the laptop's graphics drivers don't have any newer versions than what you're using, I guess you'll probably have to use images (or sprite sheets / texture atlases) that have power-of-two dimensions if you want to avoid that graphics driver bug.

love 0.9 and older supported GPUs that didn't support images with non-power-of-two dimensions at all, so it internally padded any non-power-of-two sized image to the next power of two. But love 0.10 and newer only supports GPUs that claim to support npot images, so that padding code was removed.

It probably won't be brought back to work around a driver bug, since it introduces its own set of problems.

**Comment by slime73** [comment]
There's not much LÖVE's own code can do to work around this driver bug unfortunately.
