### ISSUE TITLE
love.joystickadded reporting same joystick twice (Xbox360 + Nintendo Pro Controller)

### ISSUE THREAD

**Issue by powertomato** [love2d/love#1653]
I've noticed a strange behavior when I connect my Xbox360 and Nintendo Pro Controller at the same time.
For some reason when the controllers are connected before starting löve2d, the second call of `love.joystickadded` is called with the very same joystick object (same reference) twice.

I'm on Windows 10 v2004
XBox360 controllers are connected wirelessly via the wireless adapter (I have no USB adapter)
Nintendo pro controller is connected via USB and Bluetooth, both result in the same behavior
Sadly I don't have any other compatible gamepad to test if mixing is the problem in general.
Drivers for both were installed automatically by windows. I have no 3rd party software for remapping ect. tough I have installed Steam, which might install gamepad drivers. Steam was not running during my tests, to not interefere with them.

The Löve2D version I'm using is the released 11.3 installer for windows x64 (love-11.3-win64.exe)

I used the following test-script and run different scenarios:
```
function love.joystickadded(joystick)
	print(joystick)
	print("----")
	local joysticks = love.joystick.getJoysticks()
    for i, joystick2 in ipairs(joysticks) do
        print(joystick2)
	end
	print("###################")
end
```

1. Connect XBox360 controller
2. Connect Nintendo Pro controller
3. Start löve

Result:
```
Added:  Joystick: 0x01c7b5cb2b80
----
Joystick: 0x01c7b5cb2b80
Joystick: 0x01c7b5cb3360
###################
Added:  Joystick: 0x01c7b5cb2b80
----
Joystick: 0x01c7b5cb2b80
Joystick: 0x01c7b5cb3360
###################
```
-> Not OK, Expected 2nd call to print the reference to the nintendo controller i.e.  `Added:  Joystick: 0x01c7b5cb3360`

1. Connect Nintendo Pro controller
2. Start löve
3. Connect XBox360 controller

Result:
```
Added:  Joystick: 0x0134fec96390
----
Joystick: 0x0134fec96390
###################
Added:  Joystick: 0x0134fec8e0a0
----
Joystick: 0x0134fec96390
Joystick: 0x0134fec8e0a0
###################
```
-> OK

1. Connect XBox360 controller
2. Start löve
3. Connect Nintendo Pro controller

Result:
```
Added:  Joystick: 0x0244e1d10a80
----
Joystick: 0x0244e1d10a80
###################
Added:  Joystick: 0x0244e54b98d0
----
Joystick: 0x0244e1d10a80
Joystick: 0x0244e54b98d0
###################
```
-> OK

1. Connect XBox360 controller
2. Connect 2nd XBox360 controller
3. Start löve

Result:
```
Added:  Joystick: 0x01bc0f5c12e0
----
Joystick: 0x01bc0f5c12e0
Joystick: 0x01bc0f5c1040
###################
Added:  Joystick: 0x01bc0f5c1040
----
Joystick: 0x01bc0f5c12e0
Joystick: 0x01bc0f5c1040
###################
```
-> OK

**Comment by slime73** [comment]
Can you try with a build of the latest code from git? It uses an updated version of SDL2 which might (or might not) have fixed it: https://ci.appveyor.com/project/AlexSzpakowski/love/builds/36984535/job/xvbocfrtu5cqj54p/artifacts

**Comment by powertomato** [comment]
Hey I tried and can confirm the new SDL2 build fixes it. I built LÖVE myself a couple of days ago and debugged it to to see if the faulty event came from SDL (it did). With the dll from your build it's no longer the case.
Thanks!

**Comment by slime73** [comment]
Excellent. Thanks for testing!
