### ISSUE TITLE
file not opening

### ISSUE THREAD

**Issue by dan-the-fan** [love2d/love#1661]
when i have the file, and i run it, it **doesn't work**. (sorry for bad quality)

https://user-images.githubusercontent.com/72838747/103698261-dcdf6180-4f7f-11eb-9b00-7c82dd05524a.mp4

**Comment by steveRoll-git** [comment]
The `lovegame` folder thing is only on Android. On PCs, you have to open the executable with the folder.
To do this in the file explorer, you can _drag_ the folder onto love.exe with your mouse.

_(Or through the command line, you can call `love` with the path of the folder as the first argument.)_

**Comment by qaisjp** [comment]
1. Is the file extension `LUA` or `lua`? It should be `lua`
2. You need to drag the folder onto the `love.exe`. You are double clicking `love.exe`. Have you read the docs? https://love2d.org/wiki/Getting_Started

**Comment by dan-the-fan** [comment]
well, that actually helped...
