### ISSUE TITLE
love.window.getMode(height)

### ISSUE THREAD

**Issue by Vovkiv** [love2d/love#1665]
Seems like _love.window.getMode(height)_ function returns _width_ of window instead of _height_ or something
Resizing window with _love.window.setMode()_ works fine
Love 11.3

**Comment by FlamingArr** [comment]
According the documentation of 11.3, `love.window.getMode` always returns the width, followed by height, followed by many other things.
You don't pass in any arguments to it and if you do they are ignored.
You can use `love.window.getHeight` to retrive only the height of the window or if for some reasons you want to use `getMode` then you can do `local w, h = love.window.getMode` to do that.
