### ISSUE TITLE
Font:getHeight() does not account for newlines (\n)

### ISSUE THREAD

**Issue by Pechu317** [love2d/love#1666]
If you have a string containing \n then use Font:getHeight() on the string, the newline will not be included in the height measurement.

**Comment by slime73** [comment]
`Font:getHeight()` doesn't take any arguments - it's only meant to return the height of a single line (no matter what characters are used in a line).

You can use `Font:getWrap` and multiply `getHeight()` by the number of elements in the returned table, if you want to compute the real height measurement for a given string.

**Comment by Pechu317** [comment]
oh.

**Comment by Vovkiv** [comment]
Also, better use love forum instead of github for questions
https://www.love2d.org/forums/
