### ISSUE TITLE
Feature: love.font.getTextWidth(text)

### ISSUE THREAD

**Issue by Teo434** [love2d/love#1671]
Would basically return the width of the text depending on wich font is being used, yes you could do `textWidth = text * fontSize` but, that only works with monospaced fonts, fonts that aren't monospaced would not work, this function would return the width (in pixels) of the text depending on the current font (or, argument #2's value).

**Comment by slime73** [comment]
Is [Font:getWidth](https://love2d.org/wiki/Font:getWidth) not enough for your use cases?

**Comment by steveRoll-git** [comment]
This already exists, it's a method in `Font` objects: https://love2d.org/wiki/Font:getWidth

**Comment by Teo434** [comment]
oh, i didn't know that was a thing, thanks!
