### ISSUE TITLE
Love 11.3 can't load FLAC files

### ISSUE THREAD

**Issue by EmeraldWizardX** [love2d/love#1677]
"Added support for FLAC audio files.". But guess what, i can't load flac files, running one gives me this error.

Error

Could not load FLAC file

Traceback

[C]: at 0x7fffeea73ca0
[C]: in function 'newSource'
main.lua:4: in function 'draw'
[C]: in function 'xpcall'

**Comment by slime73** [comment]
Can you provide a .love that demonstrates the issue, or at least a flac file that does?

**Comment by EmeraldWizardX** [comment]
github does not support .love
[Uploading lovegame.zip…]()

**Comment by slime73** [comment]
It looks like the zip file didn't get uploaded fully.

**Comment by EmeraldWizardX** [comment]
github is very bad at dragging dropping files

**Comment by MikuAuahDark** [comment]
I wonder if you can upload the FLAC audio to some file sharing service (i.e. Dropbox or Google Drive) so we can take a look at the file?

**Comment by EmeraldWizardX** [comment]
the flac actually worked, but the sound is super distorted and roboty. I looked this up, and people had this problem since 2008

**Comment by EmeraldWizardX** [comment]
and the flac sounds good using a media player, but not in love

**Comment by EmeraldWizardX** [comment]
[lovegame.zip](https://github.com/love2d/love/files/6090765/lovegame.zip)

**Comment by MikuAuahDark** [comment]
But that's MP3 file you sent. Also please write in one big text then press "Comment", thanks. It gets quite spammy in the Discord.

**Comment by Vovkiv** [comment]
> 
> 
> the flac actually worked, but the sound is super distorted and roboty. I looked this up, and people had this problem since 2008

uh...
it's because you start playing audio file every love.draw() event...

**Comment by EmeraldWizardX** [comment]
i still get the "COULD NOT LOAD FLAC FILE" Error

**Comment by EmeraldWizardX** [comment]
[lovegame.zip](https://github.com/love2d/love/files/6090816/lovegame.zip)

**Comment by zorggn** [comment]
The first problem was mentioned by Vovkiv and was solved with the newly uploaded version.
I would ask if flac actually supported ID3 tags or not, because that might be the issue.

**Comment by MikuAuahDark** [comment]
Because it's still MP3. Remaing extension to FLAC and expect it to load as FLAC won't work.
![gambar](https://user-images.githubusercontent.com/7500438/110123485-e8260080-7dfb-11eb-9680-dcd965bf0476.png)

**Comment by EmeraldWizardX** [comment]
> Because it's still MP3. Remaing extension to FLAC and expect it to load as FLAC won't work.
> ![gambar](https://user-images.githubusercontent.com/7500438/110123485-e8260080-7dfb-11eb-9680-dcd965bf0476.png)

Well can i get a link to the software that you used

**Comment by Vovkiv** [comment]
Well, i guess your "BuckleYourPants.flac" not even a FLAC...
Try converting it to actual FLAC format

**Comment by EmeraldWizardX** [comment]
ok it worked, i just used a .mp3 to .flac converter
