### ISSUE TITLE
Graphics Tablets?

### ISSUE THREAD

**Issue by Vovkiv** [love2d/love#1678]
Soo, apparently love doesn't have support of graphics tablets?

**Comment by Vovkiv** [comment]
Things like pressure, if tablet connected, buttons (if it have one, and binding them) etc?

**Comment by slime73** [comment]
[SDL](https://libsdl.org/) doesn't support them right now, and LÖVE can't support them unless SDL does.

I've heard driver/API support for them is kind of a mess, especially on Windows. What do you intend to use it for?

**Comment by Vovkiv** [comment]
> 
> 
> [SDL](https://libsdl.org/) doesn't support them right now, and LÖVE can't support them unless SDL does.
> 
> I've heard driver/API support for them is kind of a mess, especially on Windows. What do you intend to use it for?

well, basically use tablet as input device for game, i guess

**Comment by slime73** [comment]
We'll have to wait for this, I guess. https://github.com/libsdl-org/SDL/issues/2217

**Comment by zhengying** [comment]
hi, [libsdl-org/SDL#2217](https://github.com/libsdl-org/SDL/issues/2217) is finished, any plan to add (SDL_pen.h)feature to love12?

**Comment by MikuAuahDark** [comment]
Probably, if we decide to use SDL3 for LOVE 12. Otherwise, no.

**Comment by slime73** [comment]
The feature in SDL is far from finished: https://github.com/libsdl-org/SDL/issues/9871#issuecomment-2134396360

It'll be a low priority feature to add compared to the other things SDL3 brings I think - so it might not happen immediately after love starts using SDL3.

**Comment by zhengying** [comment]
> The feature in SDL is far from finished: [libsdl-org/SDL#9871 (comment)](https://github.com/libsdl-org/SDL/issues/9871#issuecomment-2134396360)
> 
> It'll be a low priority feature to add compared to the other things SDL3 brings I think - so it might not happen immediately after love starts using SDL3.

hi [libsdl-org/SDL#9871 (comment)](https://github.com/libsdl-org/SDL/issues/9871#issuecomment-2134396360) is finished, any plan to add Graphics Tablets pen pressure feature in love2d 12

**Comment by zhengying** [comment]
hi, can we reopen this issue for track the feature `Graphics Tablets pen pressure`?
