### ISSUE TITLE
Stencil not working in Raspberry Pi OS (tested 11.1 and 11.4)

### ISSUE THREAD

**Issue by tavuntu** [love2d/love#1679]
I'm building a user interface in Linux (DietPi on Raspberry Pi 3b+) and I can't get to work the most basic stencil functionality:

```lua
love.graphics.stencil(myStencilFunction, "replace", 1)
love.graphics.setStencilTest("greater", 0)
```

If I install 0.10.2, the stencil works just fine. [Here's](https://github.com/tavuntu/rucopie-bkp/blob/main/root/RucoPie/ui/list-manager.lua#L69) the code where I'm using it.

So yes, something's not right in 11.3/11.4 on this specific context since I'm using the exact same code for both versions (I just change the colors to work in both of them).

Some more info:

* 11.4 was installed via retropie_setup.sh script
* Same for 0.10.2
* 11.3 was compiled from Source using [this page](https://love2d.org/wiki/Building_L%C3%96VE)

---

Weird thing is, if I use the wiki example:
```lua
local function myStencilFunction()
   love.graphics.rectangle("fill", 225, 200, 350, 300)
end

function love.draw()
    -- draw a rectangle as a stencil. Each pixel touched by the rectangle will have its stencil value set to 1. The rest will be 0.
    love.graphics.stencil(myStencilFunction, "replace", 1)

   -- Only allow rendering on pixels which have a stencil value greater than 0.
    love.graphics.setStencilTest("greater", 0)

    love.graphics.setColor(1, 0, 0, 0.45)
    love.graphics.circle("fill", 300, 300, 150, 50)

    love.graphics.setColor(0, 1, 0, 0.45)
    love.graphics.circle("fill", 500, 300, 150, 50)

    love.graphics.setColor(0, 0, 1, 0.45)
    love.graphics.circle("fill", 400, 400, 150, 50)

    love.graphics.setStencilTest()
end
```

then it works just fine... so it may be something my code is doing but, again, the stencil works using the same code for 0.10.2.

### EDIT: Not DietPi specific, please go to [this comment](https://github.com/love2d/love/issues/1679#issuecomment-812924524).

**Comment by lifeisfoo** [comment]
I see you're using a canvas in your code, if so:

> Starting with version 11.0, a stencil buffer must be set or requested in [love.graphics.setCanvas](https://love2d.org/wiki/love.graphics.setCanvas) when using stencils with a Canvas. `love.graphics.setCanvas{canvas, stencil=true}` is an easy way to use an automatically provided temporary stencil buffer in that case. 

Source: https://love2d.org/wiki/love.graphics.stencil

**Comment by tavuntu** [comment]
Yes, I'm actually [doing](love.graphics.setCanvas{canvas, stencil = true}) that.

**Comment by tavuntu** [comment]
I've managed to create a minimal piece of code to reproduce this:
```lua
-- main.lua
function love.load()
  canvas = love.graphics.newCanvas(320, 180)
end

function love.draw()
  love.graphics.setCanvas({canvas, stencil = true})

  love.graphics.stencil(function ()
    love.graphics.rectangle('fill', 10, 10, 200, 100)
  end, "replace", 1)
  love.graphics.setStencilTest("greater", 0)

  love.graphics.circle('fill', 10, 10, 50)

  love.graphics.setStencilTest()
  love.graphics.setCanvas()

  love.graphics.draw(canvas, 0, 0, 0,
    love.graphics.getWidth() / canvas:getWidth(),
    love.graphics.getHeight() / canvas:getHeight()
  )
end
```

```lua
-- conf.lua
function love.conf(t)
  t.window.width = 1280
  t.window.height = 720
end
```

This is the result in my Mac, stencil works ok:
[![Screen-Shot-2021-04-03-at-1-11-27-PM.png](https://i.postimg.cc/XYn46jXX/Screen-Shot-2021-04-03-at-1-11-27-PM.png)](https://postimg.cc/ZCs1rh8h)

This is running in LOVE inside DietPi (I haven't tried in other ARM-targeted distros but I feel it's something around the divers for these systems)
[![IMG-20210403-131209245-HDR.jpg](https://i.postimg.cc/j5DR3M2X/IMG-20210403-131209245-HDR.jpg)](https://postimg.cc/8JV8jBhJ)

I'll try this same thing in Raspberry Pi OS just to verify if this is something specific to DietPi or not.

**Comment by tavuntu** [comment]
Update: I'm able to reproduce this issue in Raspberry Pi OS as well (fresh install), with LOVE 11.1, I'll try with 11.3.

**Comment by tavuntu** [comment]
Update 3: this has something to do with Canvas, if I don't use it, the stencil works ok:
```lua
function love.draw()
  love.graphics.stencil(function ()
    love.graphics.rectangle('fill', 0, 0, 100, 100)
  end, "replace", 1)
  love.graphics.setStencilTest("greater", 0)

  love.graphics.circle('fill', 10, 10, 100)

  love.graphics.setStencilTest()
end
```

**Comment by slime73** [comment]
Adding these debug prints might help narrow it down:
```Lua
print(love.graphics.getRendererInfo())
for k,v in pairs(love.graphics.getCanvasFormats()) do
    print("canvas format " .. k .. ": " .. tostring(v))
end
```

You could also test to see if any of the specific stencil buffer formats work, by creating a depth/stencil canvas and setting it in setCanvas instead of using LÖVE's auto-created one:
```Lua
stencilcanvas = love.graphics.newCanvas(320, 180, {format="stencil8"}) -- also try "depth24stencil8"

love.graphics.setCanvas({canvas, depthstencil=stencilcanvas})
```

**Comment by tavuntu** [comment]
Here's the debug info:
```
Renderer info   OpenGL ES       OpenGL ES 2.0   Broadcom        VideoCore IV HW
canvas format depth32fstencil8: false
canvas format r32f: false
canvas format r16f: false
canvas format rg32f: false
canvas format rgba32f: false
canvas format rgba8: true
canvas format rgb565: true
canvas format normal: true
canvas format srgba8: false
canvas format rgb5a1: false
canvas format depth24stencil8: false
canvas format hdr: false
canvas format rgba16: false
canvas format rgb10a2: false
canvas format r16: false
canvas format rgba4: false
canvas format r8: false
canvas format stencil8: true
canvas format rg16: false
canvas format rg16f: false
canvas format depth16: true
canvas format depth32f: false
canvas format la8: false
canvas format depth24: true
canvas format rg8: false
canvas format rg11b10f: false
canvas format rgba16f: false
```

I tried the stencil canvas solution, for `stencil8` the result is the same (as if not stencil is being used at all) and for ```depth24stencil8``` I get something like ```canvas format not supported by graphics card```, which makes sense because of the above. Thanks for the quick answer, btw.

**Comment by tavuntu** [comment]
So as. workaround I'm printing text lines with :sub and 2 indexes to simulate movement to left and right (I was trying to clip them with the stencil). I'll try to figure this out somehow but I doubt I will be able to since I know almost nothing about C++/OpenGL.

**Comment by thegrb93** [comment]
Last time I tried opengl es on raspberry pi 3, many things didn't work and I had to try their beta drivers. Not a raspberry 3 pro, but if you can find beta opengl drivers then give that a go. Whatever it is, it's driver related most likely.

**Comment by slime73** [comment]
You could also use [love.graphics.setScissor](https://love2d.org/wiki/love.graphics.setScissor) as an alternative workaround, if what you're doing only needs to be in a screen-aligned rectangle.

**Comment by tavuntu** [comment]
Unfortunately setScissor doesn't work with canvases (which makes sense since it's a very old function), the parameters are screen based. I tried scaling them but that doesn't work, it just messes up graphics (weird squares, objects freezing, etc).

**Comment by slime73** [comment]
It does work with canvases - but the scissor rectangle is always relative to the top left of the canvas and completely unaffected by love.graphics.scale/translate/rotate/etc. That being said, it sounds like your graphics driver has bugs related to opengl scissors.

**Comment by tavuntu** [comment]
> Last time I tried opengl es on raspberry pi 3, many things didn't work and I had to try their beta drivers. Not a raspberry 3 pro, but if you can find beta opengl drivers then give that a go. Whatever it is, it's driver related most likely.

You're right, 0.10.2 for instance, works really bad, super low FPS and other issues.

**Comment by tavuntu** [comment]
> EDIT: Never mind, I think I can actually make it work... thanks!

So I couldn't get the Scissor to work either, just to let you know.

**Comment by slime73** [comment]
Unfortunately LÖVE can't realistically support graphics drivers / driver versions which don't properly support the things they claim to support. However I'm reasonably sure other people have used raspberry pi devices with LÖVE without these issues,  so maybe there's a different graphics driver or different driver version you can use?

**Comment by tavuntu** [comment]
@slime73 I hope so, what I'm afraid of is this Stencil thing notreally being used a lot in these devices. But yeah, best case scenaro is graphics drivers. I'll keep you posted.

**Comment by tavuntu** [comment]
If there's some other scenarios or other information you need (that I may be missing), please let me know.

**Comment by slime73** [comment]
> If there's some other scenarios or other information you need

I don't think there's anything we can do to fix a scissor bug in your graphics driver. I also think it's unlikely there will be a workaround in love's source for your driver's stencil issue, so your best bet is to use a driver that doesn't have those bugs.
