### ISSUE TITLE
set require path for a thread

### ISSUE THREAD

**Issue by iamevn** [love2d/love#1680]
I think it'd be useful to be able to set the require path for a newly created thread.
<details>
  <summary>Example</summary>

```lua
-- main.lua
local module = require 'module'

function love.load()
  module.runThread()
end
```
```lua
-- module/init.lua
local module = {}
function module.runThread()
  local thread = love.thread.newThread('thread/thread.lua')
  thread:start()
end

return module
```

```lua
-- module/thread/thread.lua
local foo = require 'foo'

foo.bar()
```

```lua
-- module/thread/foo.lua
local foo = {}
function foo.bar()
  return 1 + 1
end

return foo
```
</details>

This currently errors with:
> module/init.lua:3: Could not open file thread/thread.lua. Does not exist.

If we edit that line to be `local thread = love.thread.newThread('module/thread/thread.lua')`, then it loads the thread okay but the thread then errors with:
> module/thread/thread.lua:1: module 'foo' not found

Alright, we can change that require to `local foo = require 'module.thread.foo'` and everything works.

<details>
  <summary>Example after edits</summary>

```lua
-- main.lua
local module = require 'module'

function love.load()
  module.runThread()
end
```
```lua
-- module/init.lua
local module = {}
function module.runThread()
  local thread = love.thread.newThread('module/thread/thread.lua')
  thread:start()
end

return module
```

```lua
-- module/thread/thread.lua
local foo = require 'module.thread.foo'

foo.bar()
```

```lua
-- module/thread/foo.lua
local foo = {}
function foo.bar()
  return 1 + 1
end

return foo
```
</details>

But now it's hard coded to be in exactly the `module` directory in the game directory. If module is a library, it shouldn't need to care about what path you put it in in your project.

I'd like to add an optional argument to `love.thread.newThread` to set the require path for that thread and the base directory to use to look for the given filename. But keep the current behavior if this argument is not used.

You'd want to be able to specify paths rooted in the current module (probably makes sense as a default?) as well as paths rooted from the base game directory.

<details>
  <summary>How I'd like it to work</summary>

```lua
-- main.lua
local module = require 'module'

function love.load()
  module.runThread()
end
```
```lua
-- module/init.lua
local module = {}
function module.runThread()
  -- load 'thread.lua' from the thread directory within this module and set its requirePath to this module's path
  local thread = love.thread.newThread('thread.lua', 'thread/')
  thread:start()
end

return module
```

```lua
-- module/thread/thread.lua
local foo = require 'foo'

foo.bar()
```

```lua
-- module/thread/foo.lua
local foo = {}
function foo.bar()
  return 1 + 1
end

return foo
```
</details>

(Edit: put thread.lua and foo.lua in a subdirectory of module and added example of how I'd like this to work.)

**Comment by slime73** [comment]
You can use [love.filesystem.setRequirePath](https://love2d.org/wiki/love.filesystem.setRequirePath). However I believe it's shared across threads.

**Comment by iamevn** [comment]
So like this would be idiomatic?
```lua
-- module/init.lua
local module = {}

local modulePath = ...

function module.runThread()
  local thread = love.thread.newThread(modulePath .. '/thread/thread.lua')
  thread:start(modulePath .. '.thread')
end

return module
```

```lua
-- module/thread/thread.lua
local modulePath = ...
local foo = require (modulePath .. '.foo')

foo.bar()
```

**Comment by slime73** [comment]
That seems fairly reasonable, yeah.
