### ISSUE TITLE
Different colors in the image editor and in love2d.

### ISSUE THREAD

**Issue by uriid1** [love2d/love#1681]
I get slightly different colors between gimp and love2d.
This only happens if the image has transparency.

Everything I do:
```lua
local image = love.graphics.newImage("spr.png");

function love.draw()
	love.graphics.setBackgroundColor(1, 1, 1, 1);
	love.graphics.draw(image, 0, 0);
end
```

Example:
![exemple](https://cs05.spac.me/f/039016002103243017070236155230211190182251236245049144139042/1617731103/84750330/0/cc800c3036ea4d78947fdffc03854cea/exemple-spaces.im.png)

Picture:
![exemple](https://cs08.spac.me/f/039016002103243017070236155230211190182251236245049144139042/1617731836/84750411/0/c4028308b51989715ee00401b497ec90/spr2-spaces.im.png)
left gimp, right love2d.

[.love file](https://cs10.spac.me/f/039016002103243017070236155230211190182251236245049144139042/1617731462/84750350/0/f09bf3f956429d45da7316065a5b286a/test-spaces.im.love)

LOVE 11.3 (Mysterious Mysteries)
GIMP 2.10.22
OS: Manjaro Linux x86_64 
Kernel: 5.4.101-1-MANJARO 
CPU: AMD Athlon II X2 260 (2) @ 3.200GHz 
GPU: NVIDIA GeForce GT 710

**Comment by SystemLogoff** [comment]
It appears to have an embedded extra data profile for gimp. It may be using that to adjust colors inside of gimp. 


ICC_Profile | storage/public/tmp/2nb4tpvpsvu72mna3179fi27ja/Analyzepro_icc_profile_338fd6c1385d99dfb926127ac3b1b276.icc
-- | --
Little CMS
4.3.0
Display Device Profile
RGB
XYZ
2021-04-06 17:39:01
acsp
Apple Computer Inc.
Not Embedded, Independent
 
 
Reflective, Glossy, Positive, Color
Perceptual
0.9642 1 0.82491
Little CMS
0
GIMP built-in sRGB
Public Domain
0.9642 1 0.82491
1.04788 0.02292 -0.05022 0.02959 0.99048 -0.01707 -0.00925 0.01508 0.75168
0.43604 0.22249 0.01392
0.14305 0.06061 0.71393
0.38512 0.7169 0.09706
(Binary data 32 bytes)
(Binary data 32 bytes)
(Binary data 32 bytes)
3
Unknown (0)
0.64 0.33002
0.3 0.60001
0.15001 0.06
GIMP
sRGB

**Comment by uriid1** [comment]
Yes. This seems to be a GIMP-only problem. Because everything is fine in Krita. Probably because of the sRGB profile.
I was confused by the fact that the viewer had the same colors as gimp, and in love2d they were different.
