### ISSUE TITLE
Distribute macOS app - Apple rejects because dialog appears: "App" would like to receive keystrokes from any application

### ISSUE THREAD

**Issue by wolf81** [love2d/love#1682]
When trying to create a build of a game for the macOS App Store, Apple rejects the build.

The reason is when the app starts a dialog appears that states: "[App]" would like to receive keystrokes from any application.

The user is then requested to go to System Preferences => Security and enable this checkmark under "Input Monitoring".

This dialog doesn't appear in local test builds, only in my AppStore release builds (when it's packaged using the Xcode project).

As far as I can see there's no reason to request this permission whatsoever, since the app works fine even if the user rejects the permission. 

How do I prevent this dialog from appearing?

**Comment by slime73** [comment]
If you downloaded macOS frameworks from https://love2d.org/sdk/ for use with the Xcode project, they're very out of date compared to the frameworks in official love builds, and the version of SDL in them has that issue (which was since patched).

**Comment by wolf81** [comment]
@slime73 I believe I cloned from GitHub, but I did use an older commit, from version 11.3 IIRC. I'll try to see if a newer commit will fix the issue (though that might cause other issues for me).

**Comment by slime73** [comment]
You need framework dependencies (including SDL2) when building the Xcode project. The version of SDL2 being used determines whether the key issue will occur.

**Comment by wolf81** [comment]
@slime73 Ah, that's very good to know. So the issue is with the SDL framework. I will try to update my local framework dependencies and see if that works out well.

**Comment by wolf81** [comment]
@slime73 Thanks man! This fixed my issue. I believe I can release my first Love2D game on AppStore over the next few days :)
