### ISSUE TITLE
my love2d is broken

### ISSUE THREAD

**Issue by bigbruhh0** [love2d/love#1683]
hello everyone, for half a week I can't solve this problem, my love2d just freezes when I start the game, or even just the program itself without a project, tried to install version 11.4 as advised by slime from the forum, tried to restore the system to roll back some changes, nothing Does not help

I have suspicions that this happened due to the fact that I launched Corona SDK recently, it was on this day that it all started

can someone help me with this? ready to throw off any data so that they can understand what the problem is, if possible

**Comment by MikuAuahDark** [comment]
Could you reproduce it by using empty `main.lua` then disabling joystick, graphics, and window module at `conf.lua`? Afterwards try to enable those modules one by one.

**Comment by bigbruhh0** [comment]
so, I tried to disable modules as you said:

**everything is disabled** - nothing happens at startup
**turned on only the joystick** - nothing happens
**turned on only graphics** - nothing happens
**turned on only the window** - a white window appeared (I can move the window itself, which means the application does not freeze)
**turned on all three** - everything works without failure, no freezes

I have already tried to run **love2d without a game**, every time it freezes


And i checked something else

I wrote the following code in main.lua:

```
function love.load()
p={}
p.x=1
p.y=1
end

function love.update()
	p.x=p.x+1
	print(p.x)
end

function love.draw()
	--love.graphics.print("zzz",p.x,p.y)
	p.y=p.y+1
	print("       "..p.y)
end
```
everything works fine **without drawing**
**when i want to draw something the game freezes**

**Comment by slime73** [comment]
Sharing the output of `print(love.graphics.getRendererInfo())` might help to narrow this down. You could also make sure your graphics drivers are as up to date as possible.

Setting the environment variable `LOVE_GRAPHICS_USE_GL2=1` before launching love might also work around the driver bug for now.

**Comment by bigbruhh0** [comment]
> Setting the environment variable `LOVE_GRAPHICS_USE_GL2=1` before launching love might also work around the driver bug for now.
>
Wow,that works fine
`print(love.graphics.getRendererInfo())` printing this: 
**OpenGL 4.0.0 - Build 10.18.10.4276 Intel Intel(R) HD Graphics**

Setting the env. variable helped me. So what was the problem? in the drivers of the device itself?

**Comment by bigbruhh0** [comment]
Thank you so much **:3**

**Comment by slime73** [comment]
> Build 10.18.10.4276 Intel Intel(R) HD Graphics

Based on some other info I found online to compare to, that version number isn't the latest possible one for that GPU on Windows, so it's possible a graphics driver update could fix the problem for you.

I think this page has a graphics driver which should work for your model of GPU, if you want to try updating: https://downloadcenter.intel.com/download/29969/Intel-Graphics-Driver-for-Windows-15-33-

**Comment by slime73** [comment]
> what was the problem? in the drivers of the device itself?

I believe it's a bug in the specific version of the graphics drivers you have for your GPU yeah - I think it's waiting for a `glClientWaitSync` call to complete (that codepath only gets run when using OpenGL 3+), but the driver never signals that it's done so it just hangs forever.

**Comment by slime73** [comment]
I'm assuming a graphics driver update might've fixed this for you (aside from manually forcing love to use OpenGL 2 codepaths), but let me know if it hasn't.
