### ISSUE TITLE
Physics meter scale persists after love.event.quit("restart")

### ISSUE THREAD

**Issue by Haatveit88** [love2d/love#1685]
Steps:

1. Create a physics world with some gravity
2. Set a custom meter scale `love.physics.setMeter(200)`
4. Run application, observe value of `world:getGravity()`
5. Restart using `love.event.quit("restart")`
6. Observe a _different_ value of `world:getGravity()`

Basically, the setMeter value is not applied if the application is restarted using the restart event. This actually affects objects in the physics world, not just the value being printed.

Don't really understand how that makes sense, since, as in the example code below, `love.physics.setMeter()` is used in `love.load()`, which is called on every restart.

Example code to reproduce (requires console window open):
Hit `r` to restart the app, `q` to quit.

```lua
local world
local gravity = 9.8

function love.load()
	world = love.physics.newWorld(0, gravity)
	love.physics.setMeter(200)
end

local i = 0
function love.update(dt)
	world:update(dt)

	if i % 10 == 0 then
		print(world:getGravity())
	end
	i = i + 1
end

function love.keypressed(key)
	if key == "r" then
		love.event.quit("restart")
	elseif key == "q" then
		love.event.quit()
	end
end

```

**Comment by slime73** [comment]
setMeter affects everything after it. In your code example, it won't affect the initial world's gravity (because newWorld with the gravity parameter is called before the first setMeter), but the meter value affects subsequent API calls (even across restarts because it's internally a static variable).

**Comment by Haatveit88** [comment]
> 
> 
> setMeter affects everything after it. In your code example, it won't affect the initial world's gravity

Hmm it definitely did though, which is why I didn't discover this until later. The Wiki doesn't really specify that the order of operations matter, so I made a guess. And it works as expected on the first run (it is scaled), but reverts to unscaled after a restart.

Either way I guess it should be fixed now!
