### ISSUE TITLE
12.x development - Segfault when directly assigning indices to mesh through setVertexMap

### ISSUE THREAD

**Issue by ettiernu** [love2d/love#1686]
"indexData" is never assigned and remains NULL after the creation of the index buffer.

https://github.com/love2d/love/blob/14cda7818f2de579410532276911ea20cb3253e4/src/modules/graphics/Mesh.cpp#L332-L355

Minimal non-working example compiled from latest pull of 12.0:

```
local testmesh = love.graphics.newMesh({ {-100, 100, 0, 1}, {-100, -100, 0, 1}, {100, -100, 0, 1}, {100, 100, 0, 1} })
testmesh:setVertexMap({1, 2, 3, 4})
function love.draw()
  love.graphics.draw(testmesh, 200, 200)
end
```

**Comment by slime73** [comment]
Fixed by https://github.com/love2d/love/commit/3d3c665f . Thanks!
