### ISSUE TITLE
Add support for RTL scripts like Arabic, Hebrew and character joining

### ISSUE THREAD

**Issue by spritefullake** [love2d/love#1687]
Currently drawing strings written in languages like arabic fails to correctly render.

This issue has been discussed before #1059 but it does not seem changes were made to Love2D to support this. 

Does anyone know how we can add support for this? I found [this](https://github.com/luapower/harfbuzz/blob/master/harfbuzz_demo.lua) and [this](https://github.com/ufyTeX/luaharfbuzz) but these cannot be easily integrated with Love.

I am down to help contribute a solution but I don't know myself the internals of Love and integrating it with something like Harfbuzz.

**Comment by MikuAuahDark** [comment]
At https://github.com/love2d/love/issues/1059#issuecomment-589410653, there's https://github.com/RamiLego4Game/LoveArabic linked but I doubt it works on other characters other than Arabic.

**Comment by spritefullake** [comment]
> At [#1059 (comment)](https://github.com/love2d/love/issues/1059#issuecomment-589410653), there's https://github.com/RamiLego4Game/LoveArabic linked but I doubt it works on other characters other than Arabic.

yeah even this has issues like not rendering certain common ligatures

**Comment by slime73** [comment]
LÖVE's current font rendering relies heavily on glyph texture atlases – when text is rendered, the Font code draws each glyph in the text as unconnected sprite quads (and adds the glyph to the texture atlas it uses if it isn't there already). Individual glyphs in the atlas are reused for any piece of text which contains that character. When it works, it has huge performance and memory benefits compared to creating a unique texture for whole rows of text.

I'm not very familiar with rendering cursive-style languages like Arabic, but the above approach is probably not going to work for them, right? What sort of techniques are used by other games that properly render those languages, and can they work efficiently with arbitrary amounts of text created at runtime?

**Comment by slime73** [comment]
I did a tiny bit of research into harfbuzz and I believe LÖVE's current text rendering approach will work with it, although LÖVE's code will need a bit of restructuring.

**Comment by turbo** [comment]
Adding my use case: I need to render certain musical symbols, and a common way of doing this is by utilizing a font that automatically renders symbols based on special strings through ligatures. For example, using the MusGlyphs font, the string `B;b;m⁷;b⁵` should render as:

<img width="57" alt="image" src="https://user-images.githubusercontent.com/8023543/180957148-204ac003-b18d-4d06-bc81-3394af84931c.png">

But love doesn't collapse the glyphs into ligatures, so it ends up rendering as:

<img width="103" alt="image" src="https://user-images.githubusercontent.com/8023543/180957306-775c04c8-c395-4d70-9fd3-8d85887688c8.png">

Ligatures are also becoming more common in [monospace fonts](https://www.jetbrains.com/lp/mono/).

**Comment by slime73** [comment]
I think character joining / combining is working as of [8572d4f](https://github.com/love2d/love/commit/8572d4f9353da812f7d8d428446a38e5064592a2), but RTL support will need some extra work and testing.

**Comment by spritefullake** [comment]
Wow great job open source on supporting this! I did not expect it to get solved so soon.  Many thanks.
