### ISSUE TITLE
Love2d 11.3 crash under Ubuntu 18.04

### ISSUE THREAD

**Issue by Nono5000** [love2d/love#1688]
Love2d is crashing every single time I try to open it without a game. I have tried with both the PPA and the AppImage on Ubuntu mate 18.04 i686 and they both crash. The PPA version outputs ``` Aborted (core dumped)``` and the AppImage outputs 
```
X Error of failed request: BadWindow (invalid Window parameter)
Major opcode of failed request: 4(X_DestroyWindow)
Resource id in failed request: 0x3000014
Serial number of failed request: 303
Current serial number in output stream: 308
```

**Comment by Vovkiv** [comment]
Can you tell about your PC specs?

**Comment by Nono5000** [comment]
2gb ram , intel celeron single core at 2.8ghz and 80gb hdd. Ubuntu MATE 18.04 i686

**Comment by Vovkiv** [comment]
> 
> 
> 2gb ram , intel celeron single core at 2.8ghz and 80gb hdd. Ubuntu MATE 18.04 i686

What about gpu?

**Comment by Nono5000** [comment]
Integrated graphics

**Comment by MikuAuahDark** [comment]
We probably need more information about the backtrace. Can you [extract the AppImage](https://docs.appimage.org/user-guide/run-appimages.html#id5) then run the `love` executable [under gdb then print the backtrace](https://serverfault.com/a/61676)?

**Comment by Vovkiv** [comment]
> 
> 
> Integrated graphics

Which one?
Make sure that you gpu support opengl at least 2.0, because, at my own expirience, "X Error of failed request: BadWindow (invalid Window parameter)" often happens when gpu doesn't support opengl 2.0
Can you try download lubuntu, burn it on usb and launch love there?

**Comment by slime73** [comment]
That system sounds really old. LÖVE requires OpenGL 2.1 or OpenGL ES 2 support in order to run. Maybe find out if your GPU supports GL2, and also share which GPU it is?

**Comment by EmeraldWizardX** [comment]
That system is probably older than queen Elizabeth￼

**Comment by Nono5000** [comment]
The GPU is intel GMA 900. According to internet, it should support GL2.1 and GL2 ES under linux, but this system is extremely old. Here is the comparison table I used: [https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#cite_note-OGL21_i915-6]()

**Comment by Nono5000** [comment]
Also, to be a little more precise, the cpu is Intel Celeron D 336.

**Comment by slime73** [comment]
The GMA 9xx series don't actually have hardware support for OpenGL 2. But some graphics drivers have software fallbacks that run on the CPU instead for certain aspects of rendering, when using that GPU.

You could try running something that outputs the maximum OpenGL version your driver supports (GLXInfo might, I think?) - and also make sure your graphics drivers are as up to date as possible.

**Comment by Vovkiv** [comment]
Well, you should try lubuntu, it's in general better for old pcs and possibly have fallback mentioned by slime for gma 9xx, at least it have it for 3xxx

**Comment by Nono5000** [comment]
> The GMA 9xx series don't actually have hardware support for OpenGL 2. But some graphics drivers have software fallbacks that run on the CPU instead for certain aspects of rendering, when using that GPU.
> 
> You could try running something that outputs the maximum OpenGL version your driver supports (GLXInfo might, I think?) - and also make sure your graphics drivers are as up to date as possible.


I tried updating the drivers and LOVE2d seems to be working now. Thanks for helping.
