### ISSUE TITLE
Running luasocket 3.0-rc1 sample code with love2d 11.3 fails

### ISSUE THREAD

**Issue by prashantgupta24** [love2d/love#1689]
I am trying to run the following code using  love2d 11.3 on Mac OS Catalina 10.15:

https://github.com/diegonehab/luasocket/blob/master/samples/mclisten.lua

code:
```
local socket = require"socket"
local group = "225.0.0.37"
local port = 12345
local c = assert(socket.udp())
print(assert(c:setoption("reuseport", true)))
print(assert(c:setsockname("*", port)))
print(assert(c:setoption("ip-add-membership", {multiaddr = group, interface = "*"})))
while 1 do
    print(c:receivefrom())
end
```
But I get this error when I run it using love2d:
```
╰$ /Applications/love.app/Contents/MacOS/love .   
Error: main.lua:5: setsockopt failed
stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: in function 'assert'
        main.lua:5: in main chunk
        [C]: in function 'require'
        [string "boot.lua"]:570: in function <[string "boot.lua"]:380>
        [C]: in function 'xpcall'
        [string "boot.lua"]:787: in function <[string "boot.lua"]:780>
        [C]: in function 'xpcall'
```

If I run it using lua, then it works fine. I have `luasocket   3.0rc1-2` installed locally.

Is love2d 11.3 using a different variation of luasockets? I thought it was `3.0rc1`.

**Comment by slime73** [comment]
Creating a UDP socket with `socket.udp()` will defer the choice between ipv4 and ipv6 until later. setoption will only work once one of the two is chosen.

From https://tst2005.github.io/lua-socket/udp.html: 

> Note: The choice between IPv4 and IPv6 happens during a call to sendto, setpeername, or sockname, depending on the address family obtained from the resolver.

> Note: Before the choice between IPv4 and IPv6 happens, the internal socket object is invalid and therefore setoption will fail.

There are APIs to explicitly create an ipv4 or ipv6 socket.

**Comment by prashantgupta24** [comment]
Thank you @slime73 ! That worked.
