### ISSUE TITLE
Add support for Apple Silicon (M1) Mac

### ISSUE THREAD

**Issue by SJang1** [love2d/love#1690]
(without rosetta2)

**Comment by slime73** [comment]
If anyone's interested in trying out a test build with native arm64 / Apple Silicon support, you can grab one from here (or the artifacts section of the latest github actions workflow): https://github.com/love2d/love/actions/runs/890477661#artifacts

**Comment by SJang1** [comment]
Build succeeded, but got a panic error
`PANIC: unprotected error in call to Lua API (attempt to redefine 'FFI_Data' at line 4)`

**Comment by slime73** [comment]
Are you using `pcall` in your code? You might be running into this LuaJIT bug: https://github.com/LuaJIT/LuaJIT/issues/698

**Comment by SJang1** [comment]
Yes, that was a problem. that affected option should turned off only on arm, but turned on on x64. 
I've sucsessfully build lua 4fe21d40d119b59b8e3bcf16a70d7778c1365921 on my machine, and got universal binary
[love.app.zip](https://github.com/love2d/love/files/6566500/love.app.zip)

**Comment by SJang1** [comment]
If I use that one (LuaJIT/LuaJIT#698), gets error with building x64, so fixed this way
```diff
@@ -319,7 +319,9 @@ ifeq (Darwin,$(TARGET_SYS))
     $(error missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY)
   endif
   TARGET_STRIP+= -x
+  ifneq (arm64,$(TARGET_LJARCH))
   TARGET_XCFLAGS+= -DLUAJIT_UNWIND_EXTERNAL
+  endif
   TARGET_XSHLDFLAGS= -dynamiclib -single_module -undefined dynamic_lookup -fPIC
   TARGET_DYNXLDOPTS=
   TARGET_XSHLDFLAGS+= -install_name $(TARGET_DYLIBPATH) -compatibility_version $(MAJVER).$(MINVER) -current_version $(MAJVER).$(MINVER).$(RELVER)
```

This way we can build universially.

**Comment by slime73** [comment]
Thanks for testing! Here's an updated build which uses that LuaJIT patch: https://github.com/love2d/love/actions/runs/890535379#artifacts

**Comment by SJang1** [comment]
It now works great!
<img width="799" alt="screenshot with task manager" src="https://user-images.githubusercontent.com/29011440/120113428-67399380-c1b5-11eb-98b7-540dba483efc.png">

**Comment by slime73** [comment]
Excellent. Thanks again for testing!
