### ISSUE TITLE
Headless löve doesn't work on Ubuntu 20.10

### ISSUE THREAD

**Issue by pfirsich** [love2d/love#1692]
I used commit e9c58c81, built as instructed in the readme, went to `src/.libs/` and started love with a test game:
```
env LD_LIBRARY_PATH=(pwd) ./love headless_test/
```
headless_test contains two files:
main.lua
```lua
function love.run()
   print("Hello")
end
```
config.lua
```lua
function love.conf(t)
    t.identity = "makelove testgame"
    t.version = "11.3"
    t.console = false

    t.window = nil

    --t.modules.data = true
    --t.modules.event = true
    t.modules.audio = false
    t.modules.font = false
    t.modules.graphics = false
    t.modules.image = false
    t.modules.joystick = false
    t.modules.keyboard = false
    t.modules.math = false
    t.modules.mouse = false
    t.modules.physics = false
    t.modules.sound = false
    t.modules.system = false
    t.modules.thread = false
    t.modules.timer = false
    t.modules.touch = false
    t.modules.video = false
    t.modules.window = false
end
```
Sadly I do see a window flashing briefly before the game exits.
The wiki currently states this:
> It is possible to defer window creation until love.window.setMode is first called in your code. To do so, set t.window = nil in love.conf 

So I assume that it should work this way currently.

**Comment by MikuAuahDark** [comment]
Just to make sure it's not typo, did you name your config file `config.lua` instead of **`conf.lua`**?

**Comment by pfirsich** [comment]
That was exactly the issue! I'm such an unbelievable idiot and really out of practice with löve. Sorry for wasting the time of anyone who read this. Thanks a lot!
