### ISSUE TITLE
Love change saving directory without visible reasons

### ISSUE THREAD

**Issue by thisnickwasfree** [love2d/love#1693]
Sometimes it uses directory ~/.local/share/love/lovegame then suddenly switches to ~/.local/share/love/game
Main directory's name is game.

**Comment by slime73** [comment]
How do you run the game? If you don't explicitly set the game's identity via `t.identity` in conf.lua, then LÖVE will try to guess one based on the game path you give as an argument when launching LÖVE. If you run your game like  `love  .` then it probably won't be able to guess your game's folder from that.

**Comment by thisnickwasfree** [comment]
>via t.identity
>will try to guess

Guess this can be the reason, I'll check if the t.identity is correct.

**Comment by slime73** [comment]
> LÖVE will try to guess one based on the game path you give as an argument when launching LÖVE. 

Maybe we can make LÖVE normalize the path (including converting from CWD-relative to absolute) before using it for this. I'll look into it for 12.0.
