### ISSUE TITLE
Add ppa support to recent ubuntu(21.04) versions

### ISSUE THREAD

**Issue by Yzelast** [love2d/love#1695]
Hi guys, just recently updated to ubuntu 21.04 and noticed that love ppa does not support any version past 20.04...so i wanted to ask if the ppa will ever be updated to a newer version. I know that a can use the appimage or use the release from github but if possible i world like to not to have random stuff in my system. Looking at the lauchpad it looks like all versions used to have packages compiled to then, so what happened? Last question, when 22.04 is released will the ppa be updated? or maybe love could be released as snap or flatpak...

**Comment by MikuAuahDark** [comment]
For 21.04 and beyond, PPA is unnecessary.

**Comment by MikuAuahDark** [comment]
That's being said, if 11.4 is released we probably update the PPA for 21.04.

But LOVE 11.3 is already available on default Ubuntu package repository https://packages.ubuntu.com/hirsute/love
