### ISSUE TITLE
LOVE game engine not working.

### ISSUE THREAD

**Issue by SI1NNER** [love2d/love#1696]
even if i copy and paste code it does nothing, even if i just make a circle is just a blank screen. And if i use debug mode it says this: Error

Syntax error: main.lua:12: ')' expected near '1'

Traceback

[C]: at 0x548ad550
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall' even if i copy and paste code it doesent work. its either a black screen or this error. I tried re installing LOVE and visual studio code and it still does this. sometimes the "main.lua" tab has a diffrent font. what does that mean?

**Comment by flamendless** [comment]
Please show the code here. And the error screen tells you that you have a syntax error with your code, you are missing `)`. Please recheck your code and make sure it's correct.

**Comment by SI1NNER** [comment]
function love.load()
 score = 0 
 timer = 0
end

function love.update(dt)

end

function love.draw()
    love.graphics.setColor(1, 0, 0)
    love.graphics.circle("fill", 1,1,1 1,1,1 1,1,1)
end

**Comment by zorggn** [comment]
> love.graphics.circle("fill", 1,1,1 1,1,1 1,1,1)
you have two ones separated by a space, of course it will error.
Do peruse the löve forums or the discord server's support channel for user error please, this place is for actual engine issues.

**Comment by SI1NNER** [comment]
oh, only game engine issues. also discord is terrible :D dont respond to do this anymore.
