### ISSUE TITLE
Code doesent work even if i copy and paste it 

### ISSUE THREAD

**Issue by SI1NNER** [love2d/love#1697]
even if i copy and paste code or do no code what so ever i keep on getting this same error message Error

Syntax error: main.lua:12: ')' expected near '1'

Traceback

[C]: at 0x7ff8c1c728f0
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall' and when i even copy and paste code like a cheat it still doesent work 
function love.load()

end

function love.update(dt)

end

function love.draw()
    love.graphics.rectangle("fill", 200, 400, 200, 100)
end

**Comment by steveRoll-git** [comment]
How are you running your game? I suspect that you keep running the same game directory (where there's a syntax error in the code), and the new files you're writing are not being run. Are you using some code editor to run your game, or something else?
Either way, this is probably not a bug with love.

**Comment by MikuAuahDark** [comment]
As zorg said earlier in #1696, this issue place is not meant for your code problems. Please use the [forums](https://love2d.org/forums/) or our [Discord](https://discord.gg/rhUets9) server to ask for this kind of help.

Also your code is only 11 lines.
