### ISSUE TITLE
The AppImage should not ship libstdc++ (licensing reasons)

### ISSUE THREAD

**Issue by ell1e** [love2d/love#1700]
The AppImage should not ship libstdc++ because it is GPL. Therefore, as far as I understand it if it's not treated as a system library (= must already be present and not shipped) it would make the entirety of the love2d distribution, and if bundled with a game at least possibly by extension the game, also GPL licensed. Note: I am not a lawyer, so this could all be wrong.

I know leaving it out can cause portability issues. Compiling against an as old as possible libstdc++ to start with could help make these less likely, at least. Alternatively, two app images so people can decide whether to submit to the licensing caveats or not.

The libstdc++ also seems to be missing from `license.txt` right now, despite being included in the distribution.

Edit: and `libgcc_s.so.1` is also GPL, with the exception of allowing static linking into non-GPL stuff I think... so maybe that should be done, that is linking it into the `love` binary statically, instead of including it as `.so`?

**Comment by diath** [comment]
> Therefore, as far as I understand it if it's not treated as a system library 


The libstdc++ license page contains an explicit exception: https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html

**Comment by ell1e** [comment]
Ah I see, that exception covers libgcc too I assume. And I understand this exception covers linking of any kind, likely also a static link. But does it also include shipping it as a separate `.so`? I'm not so sure about it. In any case, I also think `license.txt` should possibly mention libgcc + libstdc++ in some shape or form.

**Comment by MikuAuahDark** [comment]
> Ah I see, that exception covers libgcc too I assume. And I understand this exception covers linking of any kind, likely also a static link. But does it also include shipping it as a separate `.so`?

If statically linking it is fine then I's very safe to say it's allowed to distribute it as a separate `.so`.

> I'm not so sure about it. In any case, I also think license.txt should possibly mention libgcc + libstdc++ in some shape or form.

I'm not sure about this one. If LOVE is compiled with Clang + libc++ (i.e. Android, possibly Linux too) then there will be no libgcc and libstdc++ in this case.

**Comment by ell1e** [comment]
> If statically linking it is fine then I's very safe to say it's allowed to distribute it as a separate .so.

Is this just a blind guess? From what I can gather, only output of "Target Code" produced via an "Eligible Compilation Processes" seems to count as a `combination`. It is more obvious to me that a static link is such a `combination`. Whether a separate `.so` is still enough of a combination I find less obvious. I am however not a lawyer. But is there a downside to just statically linking these two libs to sidestep this question?

> possibly Linux too

The Linux AppImage currently ships with a separate libgcc, so doesn't seem to be clang. From what I can gather it likely has the same licensing as the `libstdc++`, but don't quote me on that. If switching to clang sidesteps these questions too, that might be a useful thing to consider for the Linux AppImage build.

**Comment by MikuAuahDark** [comment]
> Is this just a blind guess? From what I can gather, only output of "Target Code" produced via an "Eligible Compilation Processes" seems to count when it is a "combination".

Not quite a blind guess. (L)GPL requires that it's possible for user-end to replace the library with better version, and the AppImage approach suits it because:

1. User can extract the AppImage
2. Switch out the (L)GPL libraries with their own version
3. Repackage the AppImage

**Comment by slime73** [comment]
> is there a downside to just statically linking these two libs

Aren't there many libraries (each of the .so's the love executable and .so depends on) which use libstc++, rather than just one? If we had to statically link libstdc++ with each of those, that seems like a lot of wasted space along with the replacement issues.

**Comment by ell1e** [comment]
> Not quite a blind guess. (L)GPL requires

That is likely irrelevant, since the exception is completely independent to LGPL/GPL terms. So nothing of the LGPL/GPL appears to apply, it's an entirely separate text. (Again, not  a lawyer though.)

> Aren't there many libraries (each of the .so's the love executable and .so depends on) which use libstc++

I guess that depends on whether any of the deps also are C++. I think multiple separate stdc++ copies compiled in separately would likely break, so if any deps also are C++ they would likely also need to be statically linked. (Which would avoid wasting space, but might be bad for other reasons.) It really was just a quick idea, I'm not 100% sure it's feasible.
