### ISSUE TITLE
Suggestion: offer AppImage without libmpg123 for (code) licensing reasons, and/or switch it out for drmp3

### ISSUE THREAD

**Issue by ell1e** [love2d/love#1701]
Currently, the app image for Linux ships libmpg123 which is LGPL. As far as I understand it, this means anyone shipping the AppImage with a game would also need to ship the source code for the exact mpg123 version used, or provide a download link to it at least or some other obvious(!) way of obtaining it. Given games may easily just use .ogg instead, this seems like an unfortunate obstacle. Maybe love2d could therefore be offered without mpg123 in addition, and maybe in the future switch to the liberally licensed drmp3 to avoid this? Disclaimer: I'm not a lawyer so all of this could be wrong.

**Comment by slime73** [comment]
I believe the only thing games need to ship to comply with mpg123's license (as well as the licenses of other direct library dependencies) is the `license.txt` file. You're also able to pass in a flag while building LÖVE to manually compile it without mpg123 support I believe.

That being said, the LÖVE 12 branch already uses a different more liberally licensed mp3 decoding library ([dr_mp3](https://github.com/mackron/dr_libs/blob/master/dr_mp3.h)).

**Comment by ell1e** [comment]
@slime73 LGPL has to my understanding a pretty strong soure code offering requirement (for the LGPL part only, so mpg123). I'm not a lawyer, but you can find enough on it on Google if you're curious. So it's always a bit of a pain to ship an LGPL binary rather than rely on it as a system lib already present, at which point whoever shipped the system lib has to deal with the source code offering part.

**Comment by slime73** [comment]
You just need to provide the ability and direction for the user to recompile mpg123.dll. The license.txt file contains information about that by linking to the source code, so as long as you ship the license.txt file with your game there shouldn't be any legal issue.

**Comment by ell1e** [comment]
Hm the license.txt just seems to provide a generic source link, not to the exact version shipped for the respective love2d version. So I don't think under a strict reading that would hold up. However, the best fix really might be to just focus on getting dr_mp3 support out the door and remove mpg123.

**Comment by MikuAuahDark** [comment]
We already used dr_mp3 in 12.0 as slime said. We can't simply replace mpg123 to dr_mp3 on next 11.4 because there may MP3 files that mpg123 can open but dr_mp3 does not.
