### ISSUE TITLE
Update Löve on raspberry pi to 11.3

### ISSUE THREAD

**Issue by EmeraldWizardX** [love2d/love#1703]
When I install love on raspberry pi, I get 11.1 instead of 11.3, that is 2 versions back.

**Comment by slime73** [comment]
We don't control the version of LÖVE that package managers have - that's up to the maintainer of the specific package manager (usually someone affiliated with the OS you're using).

That being said, there are likely other places which have more up to date LÖVE versions for your OS, or you could build it from the source code manually.
