### ISSUE TITLE
Automated build #254 doesn't work on Debian 11

### ISSUE THREAD

**Issue by monolifed** [love2d/love#1710]
Running `continuous-integration #254` love.AppImage results in `symbol lookup error: /usr/lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Done_MM_Var`
It works after removing `libfreetype.so.6` from the AppImage:
```bash
 love.AppImage --appimage-extract
 rm squashfs-root/usr/lib/x86_64-linux-gnu/libfreetype.so.6
./appimagetool-x86_64.AppImage squashfs-root/ love12.AppImage
```

I checked appimage from `#240`, it worked.
Appimage from `#241` gives the same error message

Note: `love-11.3-x86_64.AppImage` works

**Comment by MikuAuahDark** [comment]
Looks like switching from 16.04 to 18.04 (4fe21d4) breaks this.

We probably need to completely ditch the current AppImage and made new one.

**Comment by MikuAuahDark** [comment]
Out of curiosity, could you try this AppImage? This was built a round month ago but just to make sure. https://cdn.discordapp.com/attachments/516361887840075812/843806005884485662/love2d-master.AppImage

**Comment by monolifed** [comment]
It works.

**Comment by MikuAuahDark** [comment]
[This script](https://github.com/MikuAuahDark/love-appimage-source) is supposed to fix this issue but I don't have any greenlight to push the change to replace the current AppImage packaging method.
