### ISSUE TITLE
Wiki page is "broken"

### ISSUE THREAD

**Issue by RafaelWO** [love2d/love#1712]
Hi, not sure if this issue appears also for others but for me the [wiki page](https://love2d.org/wiki) looks "broken" (plain HTML, no styles). See screenshot below:

![grafik](https://user-images.githubusercontent.com/38643099/123583485-edaaba80-d7df-11eb-86ab-1089660e62f8.png)

Sorry, if this is just for me.

**Comment by FlamingArr** [comment]
Possible duplicate of #1573

**Comment by AKDev21** [comment]
it looks fine for me, maybe try to remove cookies and cache and try to run that website on incognito mode
![image](https://user-images.githubusercontent.com/68454783/123593760-87885c80-d80c-11eb-9cf7-cb31403264ea.png)

**Comment by RafaelWO** [comment]
@AKDev21 Thanks for checking!

Just checked the page on my other PC, also looks fine. Closing this issue; sorry for bothering you all
