### ISSUE TITLE
Window size incorrect when launching as maximized in Windows

### ISSUE THREAD

**Issue by User670** [love2d/love#1714]
https://github.com/26F-Studio/Techmino/issues/100

The above issue is on a game built using the Love engine. In summary, that person created a shortcut to the game executable, in right click -> properties -> shortcut, set "Run:" to Maximized, then opened the shortcut. When the game launched, the game's window is slightly larger than desirable, with a few pixels on the bottom of the window covered by the task bar.

I tried doing the same thing, but with the Love executable itself (without a game project), and it seems like this problem exists too, thus I believe this is a problem with the Love engine rather than the game.

We are both running Windows 10. There are screenshots in the issue linked above.

**Comment by slime73** [comment]
The primary issue has been solved in love 12, since it uses SDL3 now which doesn't make the window maximized in that situation.
