### ISSUE TITLE
New math functions

### ISSUE THREAD

**Issue by RuanLucasGD** [love2d/love#1717]
Hello, I started in Love a short time ago, I took a look at the documentation more did not find such functions and I wonder if I could help contributing writing these functions for Love:

- getDirectionLenght(x, y)
- normalizeDirection(x, y)
- lerp(x, y)

**Comment by MikuAuahDark** [comment]
If it can be easily implemented in Lua, then it's completely unnecessary to implement in C++. The overhead of Lua C function call in LuaJIT is higher than implementing those 3 functions in Lua.

```lua
function getDirectionLength(x, y)
    return math.sqrt(x * x + y * y)
end

function normalizeDirection(x, y)
    local dist = getDirectionLength(x, y)
    if dist > 0 then
        return x / dist, y / dist
    end
    return 0,0
end

function lerp(x, y, t)
    return x + (x - y) * t
end
-- or
function lerp(x, y, t)
    return x * (1 - t) + y * t
end
```

**Comment by RuanLucasGD** [comment]
Thanks for the explanation @MikuAuahDark , but if these functions were already part of LOVE more moon writing as you showed, would it still not be a good option to add these functions to LOVE? I wanted to implement them just to speed them up a bit when writing my scripts and not having to keep rewriting the functions with each new project.

**Comment by MikuAuahDark** [comment]
> I wanted to implement them just to speed them up a bit when writing my scripts

Writing them in Lua, is in fact is the fastest as you can get.

>  and not having to keep rewriting the functions with each new project.

Consider writing a Lua module that contains those functions, so you can just copy-paste the files to new project everytime.

**Comment by Aweptimum** [comment]
There's a previous discussion on adding vectors to love in #931 for a bit more info, but as per @MikuAuahDark's suggestion: the "fastest" implementation around is probably [vector-light](https://github.com/vrld/hump/blob/master/vector-light.lua). There is also the vector modules in [batteries](https://github.com/1bardesign/batteries) and [russet](https://github.com/potatonomicon/russet) that use objects but provide more methods .

**Comment by RuanLucasGD** [comment]
@Aweptimum  I also think using vectors in LOVE would be something good, easier to program, spends fewer lines.

**Comment by zorggn** [comment]
It would also be nice if löve included complex numbers, FFT functions, hell why not a "create MMO" function even? :3
/s
You can use vectors in löve already, it was mentioned above how, use a library, "spends fewer lines" than you needing to reimplement it anyway, otherwise i fail to see why one would care how many lines of code a self-contained file has.

**Comment by thegrb93** [comment]
You could use FFI and LAPACK :v
