### ISSUE TITLE
linux/unix dependencies required for build

### ISSUE THREAD

**Issue by bferguson3** [love2d/love#1720]
The following libraries are required to build on *nix

libluajit-5.1-dev 
libmodplug-dev
libmpg123-dev

is there a way to add these to autoconf or something similar?

**Comment by MikuAuahDark** [comment]
I'm not familiar with autotools, but I thought the dependencies are tracked at configure or at autogen step and it will tell you what libraries are missing (in case for the former).

Also those library name notation are Debian-specific. It's different for other distros. For example, in ArchLinux, it's `luajit`, `libmodplug`, and `mpg123` respectively.

**Comment by bferguson3** [comment]
Correct, I meant to say Debian, apologies for not being specific.

I think that may be the issue - those libraries exist on Debian as well,
and I had all of those already. Hmm.

If this issue is a nuisance please feel free to close it.

**Comment by MikuAuahDark** [comment]
Alright, so TL;DR: autoconf will tell you the required dependencies on configure step. Adding code to automatically install those dependencies is not possible.
