### ISSUE TITLE
Problems with love.displayrotated

### ISSUE THREAD

**Issue by LeoStark84** [love2d/love#1722]
The love.displayrotated callback, second argument is always the boolean true, instead of a string with the new orientation. Also, it is called when the screen orientation is changed via code, like when resolution changea, but not when the device is physically rotated. This has been observed in love's 11.3.0 for android (play store downloaded) running on Android 10

**Comment by LeoStark84** [comment]
A simplevway to reproduce the boolean parameter error

```
function love.load()
	w, h = love.graphics.getDimensions()
	love.window.setMode(h, w)
end

function love.displayrotated(i, o)
	o = o .. "flipped"
end
```

This leads me to believe the callback runs when the resolution is changed. However, a less destructive code such as:

```
function love.load()
	a = 0
	b = ""
end

function love.draw()
	
	love.graphics.print("Rotated " .. a .. " times", 100, 100)
	love.graphics.print(tostring(b), 150, 150)
	
end

function love.displayrotated(i, o)
	a = a + 1
	b = o
end
```

Reveals that the callback runs only when tilting from landscape to landscapeflipped, but not when the device is in portrait or portraitflipped orientations. The second parameter in displayrotated, however, is still boolean.
Sorry for the delay, I posted as soon as I discovered how to format code here.

**Comment by MikuAuahDark** [comment]
A workaround of this would be calling [`love.window.getDisplatOrientation`](https://love2d.org/wiki/love.window.getDisplayOrientation) in `love.displayrotated` callback.

That's being said, I plan to debug this issue on weekend.

**Comment by LeoStark84** [comment]
Don't get me wrong here, I really aooreciate you trying to help. However ñ, I don't think there's a workaround to this issue. I'll share my insight on it, expecting it will be of some use in the debugging process. Also please be aware that this is being tested on the playstore version of Love, as I don't have access to a desktop environment

First, your suggestion would look something like this
```
function love.load()
	nuor = ""
end

function love.update(dt)
	
end

function love.draw()
	love.graphics.print(nuor, 100, 100)
end

function love.displayrotated(i, o)
	nuor = love.window.getDisplayOrientation(i)
end
```
In this scenario only landscape to landscapeflipped and vice-versa is correctly detected (regardless of device's auto-rotate feature being enabled or disabled) but nothing happens on portrait or portraitflipped orientations. Funny enough, not only the value of nuor changes, also the graphics get rotated, and that, I think is one of the main problems, the graphics are not being rotated by Love, but by Android, then the callback is triggered because of the rotation in graphic display, not the device being tilted. However, if we try
```
function love.load()
	nuor = ""
end

function love.update(dt)
	nuor = love.window.getDisplayOrientation(i)
end

function love.draw()
	love.graphics.print(nuor, 100, 100)
end
```
Dropping the displayrotated entirely, the result is almost the same with the only difference that the variable nuor is assigned "landscape" on the first update cycle.

Finally, the vlosest to a workaraound would be to implement a button to rotate the screen manually and doing something like
```
function love.load()
	curor = "landscape"
	w, h = love.graphics.getDimensions(1)
end

function love.update(dt)
	
end

function love.draw()
	love.graphics.print(curor, 100, 100)
end

function love.touchpressed(id, x, y, dx, dy, pr)
	rotate(curor)
end

function rotate(ori)
	if ori == "landscape" or ori == "landscapeflipped" then
		curor = "portrait"
	elseif ori == "portrait" then
		curor = "landscape"
	end
	w, h = h, w
	love.window.setMode(w, h)
end
```
However automatic screen rotation is not possible in the current state of Love2d.
Again I'm grateful for your help and hope the bug is not as nasty as I think it is. Let me know if there's anyrhing else I can do to help.

**Comment by MikuAuahDark** [comment]
Probably nothing to do with the bug, but I'd like yo know your phone model and Android version.

Looks like thus bug is wrose than I imagine, but by the sound of it, it's probably an SDL issue. I'm still waiting for my package so I can use my laptop with Android Studio in it to debug this issue and this may take a week at worst.

**Comment by LeoStark84** [comment]
Model ZTE 8010
ANDROID 10
MIFavor 10.1 Ver GEN_EU_EEA_8019_v1.13

Forgot to mention I saw a simillar closed issue from 2018 on ios devices. It was SDL Version, kust gimme  a sec to find it

**Comment by LeoStark84** [comment]
Issue #1446 closed on 2018. You might want to take a look, it might give a clue

**Comment by slime73** [comment]
> Don't get me wrong here, I really aooreciate you trying to help. However. I don't think there's a workaround to this issue. 

There are two separate problems being talked about here.

The first is `love.displayrotated` receiving a boolean instead of a string enum. If that can be reproduced then it's something we can fix inside love's source code, since that's where the logic for that happens.

The second problem is either misunderstandings, real issues, or a mix of both, related to when and why the `displayrotated` callback is called. Ultimately love is just forwarding SDL's event into Lua code - and there have been a lot of updates to SDL since the version used in 11.3, so maybe an updated version will change some things. That being said, the `displayrotated` event is intended to reflect OS display orientation changes, *not* physical device rotation. The accelerometer can be used for the latter I believe.

**Comment by LeoStark84** [comment]
Well... technically, displayrotated does what you say, that is detecting graphic rotation, however, graphics will not rotate to either portrait or portraitflipped automatically, but will always rotate to landscape and landscapeflipped. Not an error, but it's inconsistant. However, if that's caused by SDL version mismatch the problem is nit on Love2d itself.
For the orientation parameter issue, I always get a boolean (true), but I don't know if that only happens on the playstore flavour of Love or in all of them. Thanks for the explanation @slime73

**Comment by MikuAuahDark** [comment]
> In this scenario only landscape to landscapeflipped and vice-versa is correctly detected (regardless of device's auto-rotate feature being enabled or disabled) but nothing happens on portrait or portraitflipped orientations.

To allow portrait(flipped) orientation, you need to set `t.window.resizable` to `true` in your conf.lua.
