### ISSUE TITLE
Thread:start not behaving as documented.

### ISSUE THREAD

**Issue by daelvn** [love2d/love#1724]
I'm having trouble with passing a table through `thread:start`. I have the following function:
```lua
-- src/sound.lua
local function saySentence(audioseq, opts)
  local thread = love.thread.newThread("worker/audio.lua")
  thread:start({
    execute = "saySentence",
    args = {
      sequence = audioseq,
      options = opts
    }
  })
end
```
And here is the code for `worker/audio.lua`:
```lua
local argl    = {...}
local Sound   = require("src.sound")
local inspect = require("src.lib.inspect.inspect") -- https://github.com/kikito/inspect.lua
print("ARGL", inspect(argl))
local worker = { }
worker.saySentence = function(self)
  local audioseq, opts = self.sequence, self.options
  for _index_0 = 1, #audioseq do -- thread error here
    local audio = audioseq[_index_0]
    audio:setVolume(opts.volume / 100)
    audio:setPitch(opts.pitch + ((opts.variation / 100) * ((love.math.random(-1, 1)) / 100)))
    Sound.play(audio)
    love.timer.sleep(opts.speed / 100)
  end
end
return worker[argl[1].execute](argl[1].args)
```
However, when run, it prints the following:
```lua
ARGL    { {
    args = {}, -- this should be populated with 'sequence' and 'options'
    execute = "saySentence"
  } }
```
And I get the following error:
```lua
THREAD ERROR! worker/audio.lua:10: attempt to get length of local 'audioseq' (a nil value)
stack traceback:
        worker/audio.lua:10: in function <worker/audio.lua:9>
```
The documentation says I should be able to pass a [Variant](https://love2d.org/wiki/Variant) to [`Thread:start`](https://love2d.org/wiki/Thread:start). The table I'm passing has the following type structure:
```moon
-- [x] means list of type x
-- {x:y} means list with keys of type x and values of type y
{
  execute: string
  args: {
    options: {string:number}
    sequence: [{string:Audio}]
  }
}
-- Where Audio my own object, defined as:
Audio {
  format: string
  location: string
  source: Source -- from love.audio.newSource
}
```
It says it supports nested tables from 11.0 and onwards. I am testing this on 11.3. I have also tried to remove the Source object in case it was having trouble serializing the table, but it didnt change anything. In theory it should all be compatible with `Variant`? I took this to the LÖVE2D Discord Server and after some debugging I was told to open an issue here.

Help would be appreciated, thanks.

**Comment by Aiq0** [comment]
Passing nested tables to thread:start works fine for me

### main.lua
```lua
print(('LÖVE version: %i.%i.%i (%s)'):format(love.getVersion()))
print(('OS: %s'):format(love.system.getOS()))

love.thread.newThread([[
	local inspect = require 'inspect'
	local argl = {...}
	print('ARGL', inspect(argl))
]]):start({
	execute = "saySentence",
	args = {
		options = {
			volume = 123,
			pitch = 5,
			speed = 10
		},
		sequence = {
			{
				test = {
					format = 'format',
					location = 'sources/file',
					source = love.audio.newSource(love.sound.newSoundData(44100))
				}
			}, {
				{
					format = 'format2',
					location = 'sources/file2',
					source = love.audio.newSource(love.sound.newSoundData(44100))
				}
			}
		}
	}
})
```
### Output
```lua
LÖVE version: 11.3.0 (Mysterious Mysteries)
OS: Linux
ARGL	{ {
    args = {
      options = {
        pitch = 5,
        speed = 10,
        volume = 123
      },
      sequence = { {
          test = {
            format = "format",
            location = "sources/file",
            source = <userdata 1>
          }
        }, { {
            format = "format2",
            location = "sources/file2",
            source = <userdata 2>
          } } }
    },
    execute = "saySentence"
  } }
```

**Comment by bartbes** [comment]
Are you sure the values you're passing to `saySentence` aren't `nil`?

**Comment by daelvn** [comment]
> Are you sure the values you're passing to `saySentence` aren't `nil`?

After some debugging I think this may be the case. I don't know exactly what's causing it, but after passing a mock table it did work. Sorry for the trouble! I will make sure to look for other points of error next time.

**Comment by slime73** [comment]
A likely cause to me might be metatables – if there's an empty table with a metatable __index field redirecting to something else, LÖVE probably won't look at the redirect.

**Comment by daelvn** [comment]
I'm not using metatables, there's probably a place where my table is not being populated correctly or a function that isn't returning what I want, it's probably LÖVE-unrelated at this point.
