### ISSUE TITLE
`RevoluteJoint:getMotorTorque` doesn't work.

### ISSUE THREAD

**Issue by FlamingArr** [love2d/love#1731]
According to the [docs](https://love2d.org/wiki/RevoluteJoint:getMotorTorque) the `:getMotorTorque()` function takes in no argument and returns a number representing the torque of the joint.
But when calling the function with no args it fails as it expects a number as argument.

Löve's source: https://github.com/love2d/love/blob/master/src/modules/physics/box2d/RevoluteJoint.h#L92

Minimal code example:
```lua
function love.load()
	local world = love.physics.newWorld()
	local body1 = love.physics.newBody(world, 100, 100, "dynamic")
	local body2 = love.physics.newBody(world, 100, 100, "dynamic")
	local revoluteJoint = love.physics.newRevoluteJoint(body1, body2, 100, 100)
	local torque = revoluteJoint:getMotorTorque() -- FAILS
	-- main.lua:6: bad argument #1 to 'getMotorTorque' (number expected, got no value)
end
```

**Comment by slime73** [comment]
Looks like it's just a documentation issue.

**Comment by megagrump** [comment]
[fixed](https://love2d.org/wiki/RevoluteJoint:getMotorTorque)

**Comment by megagrump** [comment]
Would it be acceptable to get `dt` automatically if it wasn't provided in the call? Is changing `invdt` to `dt` a good idea?

**Comment by slime73** [comment]
Yeah I think those are reasonable changes.

**Comment by slime73** [comment]
I think trying to guess the dt might be too error-prone (the frame delta time isn't always used with love.physics, and these APIs might be called before `World:update` rather than always being called during/after, in a given update cycle). So I think this is solved now.
