### ISSUE TITLE
Bug love.graphics.getWidth() on Android

### ISSUE THREAD

**Issue by Bissiatti** [love2d/love#1733]
I used  flexible resolution for an app responsible on Android. But, when I get love.graphics.getWidth() and love.graphics.getHeight() when I sign in to the app for the first time don't work. However if I return to Android Menu and reload my app works normally.

https://user-images.githubusercontent.com/61877592/136639089-da7cb435-31f6-4c46-8fe3-69b0c63cb1af.mp4

**Comment by MikuAuahDark** [comment]
Can you try the latest artifacts from https://github.com/love2d/love-android/actions/runs/1455934263 instead?
