### ISSUE TITLE
Love crashes after disconnecting a USB controller

### ISSUE THREAD

**Issue by pixelscripter** [love2d/love#1734]
When I have a controller connected to USB and pull out the cable while Love is running, Love crashes throwing the following error:
70486 segmentation fault  /Applications/love.app/Contents/MacOS/love .

A debug print in love.joystickremoved is not showing up.
It does work the other way around (connecting a new USB controller while the game is running).

OS: MacOS Big Sur 11.5.2

Could possibly be related to https://github.com/love2d/love/issues/1727

**Comment by slime73** [comment]
Can you try a recent build of love 11.4 (available here https://github.com/love2d/love/actions/runs/1327087778#artifacts)? It has a newer version of SDL which might have a fix for that crash.
