### ISSUE TITLE
Particles using quads seem to get offset by the quad position in the atlas

### ISSUE THREAD

**Issue by radgeRayden** [love2d/love#1741]
When using an atlas texture for the Particle System, the particles appear displaced by what seems to be the position in the atlas itself. Some pictures (the white circle is the mouse position, where the ParticleSystem position is set to):
standalone image
![Screenshot from 2021-11-17 23-52-55](https://user-images.githubusercontent.com/8618621/142354314-13b79385-4fbc-4eac-a3dd-30f5af50d5e2.png)
atlas image
![Screenshot from 2021-11-17 23-53-03](https://user-images.githubusercontent.com/8618621/142354330-66d709e8-21ca-4b7f-97a6-ccde0e3baf89.png)

Repro:
[repro.zip](https://github.com/love2d/love/files/7560030/repro.zip)

cc: @MikuAuahDark

**Comment by slime73** [comment]
ParticleSystems initialize particle offsets to imageDimensions/2 inside newParticleSystem. This isn't ideal for texture atlases, but you can manually change the offset via `ParticleSystem:setOffset` after creation.

I wonder what a better API design would be - it's rare that you'll want an offset that doesn't center particles so it makes sense for that to be the default, but without knowing quad information it doesn't have enough info on initialization to determine that.

**Comment by MikuAuahDark** [comment]
We actually expect the particle that uses atlas image behaves as the one that uses single image.

**Comment by slime73** [comment]
Right, there's just not enough information given to newParticleSystem for its initial offset to account for that right now.

**Comment by slime73** [comment]
Fixed. You can also use `ParticleSystem:setOffset` to work around the issue in versions before the fix.
