### ISSUE TITLE
i can't run love2d on mac os, lua_State is null

### ISSUE THREAD

**Issue by widwei** [love2d/love#1742]
![image](https://user-images.githubusercontent.com/147744/142566255-7f4c11eb-8119-4c18-954a-96b45d2246fa.png)
framework is love-osx-frameworks-0.10

**Comment by slime73** [comment]
For love 11+ you should use the frameworks in this repository: https://github.com/slime73/love-apple-dependencies

**Comment by slime73** [comment]
Let me know if that doesn't work.
