### ISSUE TITLE
love.conf is called only if it is defined in conf.lua

### ISSUE THREAD

**Issue by stone628** [love2d/love#1747]
For example, in case of simple project with just main.lua and love.conf defined in it, love.conf is not called.

Did some digging, and found out that,
love.conf is called between loading conf.lua (if exists) and loading main.lua

[Official Wiki page](https://love2d.org/wiki/Config_Files) says you can overwrite love.conf with conf.lua
And I feel like it is a little bit misleading.

**Comment by slime73** [comment]
What's the expected result for you, given the fact that configuration (and especially module loading) has to happen before main.lua is executed?

**Comment by stone628** [comment]
I was confused when my test project is not showing window title correctly.
(single file project, love.conf in main.lua)
Spent some time figuring out why, and there might be others wondering.

For me, it would be enough to have statement in the wiki, that config **must** be defined only in conf.lua

**Comment by slime73** [comment]
I added an extra sentence/paragraph to the top of that wiki page which should help clarify it.
