### ISSUE TITLE
Implement love.window.getSafeArea for macOS

### ISSUE THREAD

**Issue by slime73** [love2d/love#1751]
Now that some Mac laptops have a notch at the top, Apple has new APIs for this on macOS.

**Comment by slime73** [comment]
Then again... macOS handles this automatically in some cases, so maybe I'll hold off adding this until I can be sure it's actually needed:
> If your app uses the system’s full-screen experience, you don’t need to account for the safe area in your window. When you call your window’s toggleFullScreen(_:) method to enter full-screen mode, the system automatically positions the window’s contents within the safe area.

**Comment by gianmichelemariani** [comment]
I can confirm this is handled in a very elegant way. When you go full screen the area of the notch is not drawn on, only menus get in there

**Comment by slime73** [comment]
I'll reopen this if some form of it ends up being necessary in the future.
