### ISSUE TITLE
byteData:clone is a nil function

### ISSUE THREAD

**Issue by EngineerSmith** [love2d/love#1754]
I cannot clone a `byteData` object in love 11.3, the function is nil.

Repo:
```lua
local byteData = love.data.newByteData(196)
local cloned = byteData:clone() -- attempt to call method 'clone' (a nil value)
```

Links: https://love2d.org/wiki/ByteData https://love2d.org/wiki/Data:clone

**Comment by zorggn** [comment]
Looks like this might be the culprit, ByteData's clone method isn't exposed in the wrapper:
https://github.com/love2d/love/blob/main/src/modules/data/wrap_ByteData.cpp#L34-L37
```Cpp
static const luaL_Reg w_ByteData_functions[] =
{
	{ 0, 0 }
};
```

**Comment by EngineerSmith** [comment]
Temp solution to this issue to clone a byteData: 
```lua
local clone = function(byteData)
  return love.data.newByteData(byteData:getString(), 0, byteData:getSize())
end
```
This solution is twice as fast than a cpp(ffi lib) memcpy in my benchmarks
