### ISSUE TITLE
Getting cannot create image error (OpenGL error: out of memory)

### ISSUE THREAD

**Issue by JacomusP** [love2d/love#1759]
I just downloaded Love 2D and when I'm just trying to run the basic hello world program I get the following error: **cannot create image (OpenGL error: out of memory)**

My code is the following
`function love.draw()
    love.graphics.print("Hello World!", 1280, 720)
end`

And my PC specs are: Windows 10 Pro, intel i7-9750H, 32GB of RAM, Nvidia 2070 GTX

**Comment by MikuAuahDark** [comment]
(closed as per OP confirmation in Discord)
