### ISSUE TITLE
Mouse cursors with custom image renders with incorrect size

### ISSUE THREAD

**Issue by ReFreezed** [love2d/love#1762]
_LÖVE version: 11.4
OS: Window 7_

Using a custom image file when creating a hardware cursor makes the cursor render stretched with a size of 32x32 (or something like that) no matter what size the image is. LÖVE 11.3 did not have this issue.

Test project:  [Love114CursorBug.zip](https://github.com/love2d/love/files/7831635/Love114CursorBug.zip)

**Comment by slime73** [comment]
Thanks for the repro project! After reproducing the issue myself I've created a bug report in the SDL repository: https://github.com/libsdl-org/SDL/issues/5198

**Comment by slime73** [comment]
A fix has been made in SDL: https://github.com/libsdl-org/SDL/commit/1085c31

I'll close this issue when I push a version of SDL with that commit to the megasource repository so it gets picked up by new love builds (I'll probably do that when SDL 2.0.20 is released, which should be soon).

**Comment by slime73** [comment]
I've pushed an updated SDL2 now. Here's some generated builds if you want to try it: [32 bit](https://ci.appveyor.com/project/AlexSzpakowski/love/builds/42216407/job/alh5iefa0d7pvn6i/artifacts), [64 bit](https://ci.appveyor.com/project/AlexSzpakowski/love/builds/42216407/job/6ioreo6ue7y1n33m/artifacts).

**Comment by ReFreezed** [comment]
Nice. I can confirm the bug is fixed.
