### ISSUE TITLE
Feature Request: Enums Instead of Strings

### ISSUE THREAD

**Issue by jeffmikels** [love2d/love#1765]
How difficult would it be to change things like `DrawMode` from a string value to an enum value?

In my own code, I can make a global table like this:

```lua
DrawMode = { fill = 'fill', line = 'line' }
```

And then I can do this:

```lua
love.graphics.circle(DrawMode.fill, 100, 100, 20)
```

There's not much benefit to doing that in Lua, but if this were done at the framework level, it would create two specific benefits:

- LuaJIT can use the same memory location for every reference to `DrawMode.fill` saving a tiny bit of memory and speed, and can avoid all the (more expensive) string comparisons
- the IDE can parse enum values and use Intellisense or whatever other suggestion mechanisms to suggest possible values.

**Comment by slime73** [comment]
For the first point, Lua/LuaJIT interns strings (ie only ever has a single copy of a given string in memory) so it wouldn't save performance in that sense. Accessing a table (especially a global table) has a slight cost to it, so `love.graphics.circle(DrawMode.fill, ...)` would be more expensive than `love.graphics.circle("fill", ...)`.
