### ISSUE TITLE
[Discussion] I hate zero! 😭

### ISSUE THREAD

**Issue by lua-rocks** [love2d/love#1769]
When I look at this kind of code, it makes me wanna cry:

```lua
batch:add(quad, x - 1, y - 1)
```

[These `- 1` are a consequence of love ignoring](https://en.wikipedia.org/wiki/Off-by-one_error) [lua rule to start iterating with one!](https://en.wikipedia.org/wiki/Zero-based_numbering)

I understand that this is a very controversial issue, and most people would disagree with my desire to shift the coordinate axis by [+1,+1]. I'm sure they will say that in mathematics the coordinate axis always starts with zero and it cannot be otherwise, bla bla bla... But to such a dogmatic argument I have an appropriate response: fuck that broken math! Zero and infinity are not numbers at all! 😐

**Comment by slime73** [comment]
Coordinates are not array indices. They can even be fractions.

This issue tracker is meant for actual problems and changes rather than troll posts.

**Comment by lua-rocks** [comment]
@slime73 For me, this is an actual problem. I'm not trying to troll, I just want to get criticism and counterarguments. If you change my mind, I will thank you. The coordinate axis in love is counted in pixels. Pixels cannot be fractions.

**Comment by thegrb93** [comment]
Just use love.graphics.translate to shift the coordinate system if you wish.

> The coordinate axis in love is counted in pixels. Pixels cannot be fractions.

There is subpixel accuracy with coordinates which lets edges blend between pixels when antialiasing is enabled.

**Comment by lua-rocks** [comment]
Okay, it is not an array, the axis can start from zero or -14.86, but should it? Are you really comfortable subtracting and adding one in every second line of your code?

**Comment by lua-rocks** [comment]
love.graphics.translate is not universal solution. It doesn't work in the example I gave above.

**Comment by lua-rocks** [comment]
I usually store quads in an array and go through this array using `for index, quad in ipairs(quads) ...`. In `ipairs` loop you can't start from 0 and even if you could, you would have to end the loop at array length - 1

**Comment by thegrb93** [comment]
What is x and y?

**Comment by lua-rocks** [comment]
variables?

**Comment by slime73** [comment]
If you're initializing `x` and `y` to number values somewhere, you can just... make them use the pixel coordinate system, instead of pretending they're array index numbers, when you initialize them.

If you need further help or guidance feel free to use the Discord server's support channel or the forums.

**Comment by thegrb93** [comment]
> variables?

What are they defined as

**Comment by lua-rocks** [comment]
numbers

**Comment by thegrb93** [comment]
> numbers

I mean the formula

**Comment by lua-rocks** [comment]
Why can't you just say your thought?

**Comment by slime73** [comment]
Hi folks, this isn't a chat channel or support forum. Please use what I suggested earlier to continue this conversation.

**Comment by lua-rocks** [comment]
@slime73 Sorry, I don't use Discord.

**Comment by lua-rocks** [comment]
@slime73 It would be cool if you could add a discussion section on the githab

**Comment by thegrb93** [comment]
> Why can't you just say your thought?

Because you still haven't given a clear example and I was trying to get more info, but it seems like you already know you're not going to get what you want.

**Comment by slime73** [comment]
> @slime73 It would be cool if you could add a discussion section on the githab

People (including but not limited to me) felt that it would fragment the community too much considering we already have Discord, forums, and a subreddit. You can choose one of those three (doesn't have to be Discord).

**Comment by lua-rocks** [comment]
@thegrb93 Understand, I didn't come here to argue. If you really have a thought that convinces me, I'll be happy!

**Comment by lua-rocks** [comment]
Okay, I don't want to cause any problems. Anyway, thank you all.
