### ISSUE TITLE
macOS: freetype.framework Info.plist case-sensitive CFBundleExecutable

### ISSUE THREAD

**Issue by eliteraspberries** [love2d/love#1770]
The value of the CFBundleExecutable key in the Info.plist of the freetype framework:

    <key>CFBundleExecutable</key>
    <string>FreeType</string>

but the file name is all lower case:

    % ls love.app/Contents/Frameworks/freetype.framework/Versions/A/  
    Resources	_CodeSignature	freetype

This results in this error (after signing love.app with my own key):

    % codesign --deep --verbose --verify love.app
    love.app: code has no resources but signature indicates they must be present
    In subcomponent: /Users/dev/love.app/Contents/Frameworks/freetype.framework

Editing the value to "freetype" fixes this.

Edit: using plutil

    plutil -replace CFBundleExecutable -string freetype love.app/Contents/Frameworks/freetype.framework/Resources/Info.plist

**Comment by slime73** [comment]
Looks like it got fixed very recently in upstream FreeType too: https://github.com/freetype/freetype/commit/56d182a74d90cde8753d5ec28d37f748f909c729

Now to overcome the issues I'm running into trying to rebuild it...

**Comment by eliteraspberries** [comment]
You're getting this error right?

    CMake Error: Target freetype Info.plist template "builds/mac/freetype-Info.plist" could not be found.

Try this patch: [patch-CMakeLists.txt](https://github.com/love2d/love/files/8008382/patch-CMakeLists.txt)

```
--- CMakeLists.txt.orig	2022-02-05 11:34:30.000000000 -0500
+++ CMakeLists.txt	2022-02-05 11:34:43.000000000 -0500
@@ -438,7 +438,7 @@
   )
   set_target_properties(freetype PROPERTIES
     FRAMEWORK TRUE
-    MACOSX_FRAMEWORK_INFO_PLIST builds/mac/freetype-Info.plist
+    MACOSX_FRAMEWORK_INFO_PLIST ${PROJECT_SOURCE_DIR}/builds/mac/freetype-Info.plist
     PUBLIC_HEADER "${PUBLIC_HEADERS}"
     XCODE_ATTRIBUTE_INSTALL_PATH "@rpath"
   )
```

**Comment by slime73** [comment]
That was one of the issues I was getting. After I solved that, it failed to build because the cmakelists never found `fcntl.h` (which seems to always be used on macOS, and should exist).

I've been trying with the 2.11.1 source, maybe some stuff has changed in the latest git or other versions.

**Comment by eliteraspberries** [comment]
The first part of https://github.com/freetype/freetype/commit/56d182a74d90cde8753d5ec28d37f748f909c729 (changing ARCHS_STANDARD_32_64_BIT to ARCHS_STANDARD) fixed the headers not found bug for me.

**Comment by slime73** [comment]
Thanks, that was it – I was just modifying the xcode project manually to account for the arch change, before.

I've pushed the new freetype framework to the love-apple-dependencies repository, and I uploaded a new build of love.app as well as a copy of the dependencies to the 11.4 release page.
