### ISSUE TITLE
How to build love without luajit

### ISSUE THREAD

**Issue by guoyunhe** [love2d/love#1771]
I am building love for a game handheld device. Unluckily, luajit isn't available for that platform but it does have lua. Can I build love without requiring luajit? Is here an option to disable luajit when run configure? Thanks!

**Comment by slime73** [comment]
`--with-lua=lua` and `--with-luaversion=5.1` (or 5.2 or 5.3 or 5.4) should work, I think.

**Comment by guoyunhe** [comment]
Thanks! Now I can start to compile. But I got some errors:
```
common/runtime.h: In function 'lua_Number love::luax_optnumberclamped01(lua_State*, int, double)':
common/runtime.h:224:33: error: no matching function for call to 'max(lua_Number, double)'
  224 |         return std::min(std::max(luaL_optnumber(L, idx, def), 0.0), 1.0);
      |                         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/guo/git/gkd-350h/gkdmini_buildroot/output/host/mipsel-buildroot-linux-musl/include/c++/11.1.0/bits/char_traits.h:39,
                 from /home/guo/git/gkd-350h/gkdmini_buildroot/output/host/mipsel-buildroot-linux-musl/include/c++/11.1.0/string:40,
                 from /home/guo/git/gkd-350h/gkdmini_buildroot/output/host/mipsel-buildroot-linux-musl/include/c++/11.1.0/bitset:47,
                 from common/types.h:27,
                 from common/runtime.h:26,
                 from common/Reference.cpp:22:
```

I run this command:

```
./configure --host=mipsel-linux --with-lua=lua --with-luaversion=5.3
```

Full script can be found here https://github.com/guoyunhe/gkd-350h

**Comment by slime73** [comment]
Is your system using a build of Lua that's custom-compiled to use something other than 64 bit floating point numbers (doubles) for its `number` type? LÖVE doesn't officially support anything other than that, although you might be able to work tweak its source code I suppose.

**Comment by guoyunhe** [comment]
The target system uses a MIPS CPU. Maybe the float number length of MIPS is different?

**Comment by slime73** [comment]
IMO it's more likely that the build of Lua was modified before compilation to do this: https://stackoverflow.com/questions/21336377/how-to-change-lua-number-from-double-to-float-properly-in-lua-5-2-3 (which LÖVE isn't guaranteed to work with).

**Comment by guoyunhe** [comment]
It was built by buildroot. But I didn't see it patched luaconf.h. I modified love's source with `static_cast<double>` and now it can be compiled.

Here is a new issue:

```
/usr/include/SDL2/SDL_cpuinfo.h:102:10: fatal error: immintrin.h: No such file or directory
```

**Comment by slime73** [comment]
Judging by the contents of `SDL_cpuinfo.h`, that error could only happen if `HAVE_IMMINTRIN_H` was set by a build system while building SDL2 despite the system not having that header (x86 intrinsics).

That being said, maybe a support forum for the platform you're compiling for would have better answers to the issues you're running into? Especially since they aren't necessarily related to love's source code.

**Comment by guoyunhe** [comment]
Thanks for the help!

**Comment by gynt** [comment]
Can this also be done via megasource (i.e. on Windows)? I looked for the command line argument but it is in a platform/unix folder, in an autoconf file. So I think it isn't available on Windows?

**Comment by slime73** [comment]
Windows uses the project's cmake configuration files. For those, there's a `LOVE_JIT` boolean flag which defaults to on, I think to set it to false when configuring the cmake project you'd pass in `-DLOVE_JIT=OFF` or something similar, to the cmake command.

**Comment by gynt** [comment]
Ah sorry, I wasn't specific enough, I was wondering if specifying the lua version (5.4) is also possible. I only see that when LOVE_JIT is OFF (or False), that lua51.dll is still required. I assume I can't just pass a 5.4 dll renamed as lua51.dll :)

**Comment by slime73** [comment]
megasource is only bundled with one version of stock lua, but replacing it with another version will probably work.
