### ISSUE TITLE
Enforce usage of dots in `require`

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1773]
LOVE accidently supports loading modules using `require("path/to/library")` notation. This is not supported in normal Lua environment and it seems some newbies falls into this and sometimes multi-file libraries doesn't handle paths with slashes very well.

Feel free to discuss your opinion about this change. If this is accepted, I think this is good idea to start this enforcement in 12.0.

**Comment by slime73** [comment]
I've been thinking about using love's deprecation mechanism to deprecate slashes for love 12. Maybe if we do that we'll evaluate when to turn the deprecation into a removal based on how many libraries and codebases have been updated.

**Comment by slime73** [comment]
There's also some older discussion about it in #1214 - I suppose keeping it deprecated forever would work around the problem I mentioned there with removal.

**Comment by slime73** [comment]
This is implemented now via deprecation notices, as of 941fe51
