### ISSUE TITLE
Decoding PNG image throws an error in 11.4

### ISSUE THREAD

**Issue by tavuntu** [love2d/love#1774]
I was happily updating the game I'm workin on (on a Mac, using 11.3), I pushed the code to NotABug, pulled it in my other laptop (Manjaro Linux, LÖVE 11.4) and then I get this issue. I'm not doing anything fishy at this point, just opening a bunch of png images, and this error pops up with the first call to `love.graphics.newImage()`

[![Captura-de-pantalla-2022-02-09-22-23-14.png](https://i.postimg.cc/qqF8tFfk/Captura-de-pantalla-2022-02-09-22-23-14.png)](https://postimg.cc/YL14ZbqV)

this is the line that fails, just for reference:
`images.popImg = love.graphics.newImage(imgDir .. 'pop.png')`

**Comment by MikuAuahDark** [comment]
Please read from here https://github.com/love2d/love/issues/1727#issuecomment-944993952

It's not LOVE mistake, but this start seem to be more common, so I'll keep this open for a while.

**Comment by tavuntu** [comment]
@MikuAuahDark thanks. Added a comment in there.

**Comment by thegrb93** [comment]
I've found GIMP will cause this unless I uncheck everything in the advanced section of the save png menu.

**Comment by thegrb93** [comment]
@tavuntu 2.10.8. Looks like latest is 2.10.30 so I could try updating.

**Comment by thegrb93** [comment]
@tavuntu looks it's fixed in the latest gimp version

**Comment by tavuntu** [comment]
Awesome, thanks, so it seems this was a Gimp issue after all (or one of the libraries it uses). That's some good info.

**Comment by MikuAuahDark** [comment]
According to https://gitlab.gnome.org/GNOME/gimp/-/issues/2111, it seems to be fixed in GIMP 2.10.24 or later.
