### ISSUE TITLE
Segmentation fault when calling the first-declared FFI callback

### ISSUE THREAD

**Issue by apicici** [love2d/love#1776]
```lua
local ffi = require "ffi"

local test = function() end
local cb1 = ffi.cast("void (*)()", test)
local cb2 = ffi.cast("void (*)()", test)
```
Calling the first-declared FFI callback causes segmentation faults on Linux with LÖVE 11.4.
I tested with 11.3 and the problem does not occur there; it also does not seem to happen on Windows or macOS (tested with virtual machines).

Some more details:
- `cb1` can be called without a segmentation fault only if no other callback (including itself) has been called before:
  ```lua
  cb1() -- no segmentation fault
  ```
  ```lua
  cb1(); cb1(); -- segmentation fault on the second call to cb1
  ```
  ```lua
  cb2(); cb1(); -- segmentation fault on the first call to cb1
  ```
- `cb2` and any other callbacks declared after `cb1` can be called without problems:
  ```lua
  for i = 1, 100 do cb2() end -- no segmentation fault
  ```
- I tested this with a minimal `main.lua` including only the lines above. Running the file through LuaJIT 2.1 works fine.
- I 'm running archlinux. I tested with both the repository version of LÖVE and the AppImage with the same result.

I put together an extended `main.lua` for testing purposes:
```lua
local ffi = require "ffi"

local test = function(i)
    print(string.format("Callback %d was run", i))
end

local cb = {
    ffi.cast("void (*)(int)", test),
    ffi.cast("void (*)(int)", test),
    ffi.cast("void (*)(int)", test),
}

local function test1()
    print "Try running the 1st callback twice:"
    print "------------------"
    cb[1](1); cb[1](1)
end
local function test2()
    print "Try running the 1st callback followed by the 2nd, then the 1st again:"
    print "------------------"
    cb[1](1); cb[2](2); cb[1](1)
end
local function test3()
    print "Try running the 2nd and 3rd callbacks multiple times:"
    print "------------------"
    cb[2](2); cb[3](3); cb[2](2); cb[3](3)
end
local function test4()
    print "Try running the 1st callback after the 2nd:"
    print "------------------"
    cb[2](2); cb[1](1)
end

-- Comment out one of the following lines to test the various combinations

test1()
-- test2()
-- test3()
-- test4()
```

**Comment by MikuAuahDark** [comment]
Can you try if the same happends on LuaJIT interpreter, i.e. without using LOVE? https://github.com/LuaJIT/LuaJIT

**Comment by thegrb93** [comment]
I tried with luajit-2.1.0 and didn't have any issue.

**Comment by slime73** [comment]
Which 2.1 commit? There aren't labelled releases of 2.1 anymore.

**Comment by thegrb93** [comment]
The readme says LuaJIT 2.1.0-beta3

**Comment by thegrb93** [comment]
Ah I found it in refs/heads.
https://github.com/LuaJIT/LuaJIT/commit/20f556e53190ab9a735b932f5d868d45ec536a70

**Comment by apicici** [comment]
> Can you try if the same happends on LuaJIT interpreter, i.e. without using LOVE? https://github.com/LuaJIT/LuaJIT

I have tried with the version of LuaJIT in the archlinux repositories (2.1.0.beta3.r384.g1d7b5029) as well as LÖVE 11.4 from archlinux, which uses the same LuaJIT version. The segmentation faults only occur when running it through LÖVE.

I have also tried to run the file directly with LuaJIT and loading LÖVE by requiring the shared library and calling `love.boot()`. This also leads to the segmentation fault.

**Comment by apicici** [comment]
I just confirmed that the archlinux LuaJIT is build from the current HEAD of https://github.com/LuaJIT/LuaJIT

**Comment by slime73** [comment]
If these two lines are run in a standalone interpreter does it affect whether it's reproducible there? https://github.com/love2d/love/blob/main/src/modules/love/jitsetup.lua#L29-L34

**Comment by apicici** [comment]
> If these two lines (plus the sizemcode line at the bottom) are run in a standalone interpreter does it affect whether it's reproducible there? https://github.com/love2d/love/blob/main/src/modules/love/jitsetup.lua#L29-L34

It still works without problems if I add those three lines. In fact I don't think it is related to something in LÖVE that is only run if JIT is on, since I tried running
```lua
-- script.lua
require "love"
require "love.boot"()
```
with `luajit -j off script.lua <path to folder containing main.lua>` and I still get the segmentation faults.

**Comment by apicici** [comment]
I did some more testing by modifying the `love.init` function in `boot.lua`, and I found out that the segmentation faults are related to `love.audio`. If I disable the audio module from `love.conf` everything works without problems.

**Comment by MikuAuahDark** [comment]
If it's has to do with love.audio, it could be related to
https://github.com/love2d/love/issues/1763

Pada tanggal Sel, 15 Feb 2022 05.55, Alex Szpakowski <
***@***.***> menulis:

**Comment by MikuAuahDark** [comment]
Based from investigation in LuaJIT issue tracker, a workaround is to prevent PipeWire from setting " zero denormals" with `cpu.zero.denormals`.

I don't know if it should be LuaJIT fixes their JIT compiler, OpenAL-soft workarounds it in their code, or reported to PipeWire upstream. I'll keep this open until I have more information.

**Comment by slime73** [comment]
I think this is almost definitely pipewire's bug - they shouldn't be disturbing global state like that.

**Comment by thegrb93** [comment]
Interesting that a denormal setting is affecting luajit's ffi function calling. Seems like a luajit regression if it wasn't an issue before. I'd git bisect their commits and find what introduced the problem out of curiosity if I had a linux setup with pipewire.

**Comment by slime73** [comment]
IMO it's not a bug for code to rely on standard floating point behaviour, even if the reliance is new. Pipewire's code changes floats to behave in a non-standard way.

**Comment by thegrb93** [comment]
True, but a segmentation fault is luajit's fault

**Comment by slime73** [comment]
It's in the same category as memory corruption in my opinion. Some code may crash due to other code writing to memory it doesn't own (and some code may crash due to other code changing the float mode for code it doesn't own), it's not the crashing code's responsibility to prevent other code from messing with it.

**Comment by thegrb93** [comment]
I don't think turning off denormals is as heinous. Imo, I would expect less accurate floats to not trigger a segfault.

**Comment by thegrb93** [comment]
Considering it worked fine before, they must've overlooked something with a recent commit.

**Comment by slime73** [comment]
Some updates from the [pipewire issue report](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2160):
* Applying float denormal mode changes globally on the calling thread instead of just on internal threads was a mistake in their code.
* There's a new commit to stop applying float denormal mode changes by default.
* There's a second new commit which avoids the need for denormal mode changes entirely, in their internal code that used to benefit from it.

Since there are now fixes in pipewire for this, I think this issue can be closed.

**Comment by thegrb93** [comment]
Also looking into the luajit issue, I learned it wasn't their fault since it was due to changing the flag while luajit was in mid operation. That I can understand causing problems.

**Comment by MikuAuahDark** [comment]
PipeWire 0.3.48 has been released to fix this issue. If you're on PipeWire version between 0.3.39 and 0.3.47 then please update your PipeWire when possible or force PulseAudio backend with `ALSOFT_DRIVERS=pulse` to workaround the issue.
