### ISSUE TITLE
Mention love-packager in distribution docs

### ISSUE THREAD

**Issue by poeck** [love2d/love#1784]
Mention [love-packager](https://github.com/simplifylabs/love-packager) in the [Game Distribution Docs](https://love2d.org/wiki/Game_Distribution) as an easy way to package a LÖVE game.

This currently applies to:

- .love-File
- Windows (32 & 64)
- Linux
- Mac

with more coming soon!

**Comment by MikuAuahDark** [comment]
Hello, please create a pull request in the https://github.com/love2d-community/awesome-love2d#distribution repository.
