### ISSUE TITLE
t.appendidentity only takes effect if identity is set with t.identity, love.filesystem.setIdentity does not work with it

### ISSUE THREAD

**Issue by wolfboyft** [love2d/love#1785]
And doing both also has the save directory searched first.

**Comment by wolfboyft** [comment]
Turns out love.filesystem.setIdentity has its own appendIdentity equivalent hidden away. This is more of a wiki issue, then.

**Comment by MikuAuahDark** [comment]
What wiki are you referencing to? `love.filesystem.setIdentity` documents the 2nd argument sice 2013.
