### ISSUE TITLE
Fail to compile src/modules/system/System.cpp on msys2

### ISSUE THREAD

**Issue by ylme** [love2d/love#1786]
I use msys2 - mingw64  on Windows10 and I use love-11.4. I modify CMakeLists.txt slightly and generate Makefile successfully. Then I `make` 

```
D:/work/workplace/love/love-11.4-2/src/modules/system/System.cpp: In member function 'virtual bool love::system::System::openURL(const string&) const':
D:/work/workplace/love/love-11.4-2/src/modules/system/System.cpp:167:16: error: cast from 'HINSTANCE' {aka 'HINSTANCE__*'} to 'int' loses precision [-fpermissive]
  167 |         return (int) result > 32;
      |                ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/liblove.dir/build.make:3030：CMakeFiles/liblove.dir/src/modules/system/System.cpp.obj] 错误 1
```

And I modify src/modules/system/System.cpp:167. Then `make` succeed.

```c
-	return (int) result > 32;
+	return (ptrdiff_t) result > 32;
```

**Comment by MikuAuahDark** [comment]
Compiling with GCC in Windows (MinGW or Cygwin) is not supported. Only MSVC is supported.

**Comment by slime73** [comment]
That being said I think the fix is legitimate. `ShellExecuteW`'s documentation says this:
> If the function succeeds, it returns a value greater than 32. If the function fails, it returns an error value that indicates the cause of the failure. The return value is cast as an HINSTANCE for backward compatibility with 16-bit Windows applications. It is not a true HINSTANCE, however. It can be cast only to an INT_PTR and compared to either 32 or the following error codes.

**Comment by ylme** [comment]
If this modification is reasonable, I can send a PR

**Comment by slime73** [comment]
That'd be appreciated!

**Comment by slime73** [comment]
Merged. Thanks!
