### ISSUE TITLE
Suggestion: Option for fixed framerate

### ISSUE THREAD

**Issue by Yolwoocle** [love2d/love#1792]
Dynamic framerate is nice and all, but I would appreciate if there were a function to pin the framerate to something constant, or, like how Unity does it, having a `love.fixedUpdate(fixed_dt)` function.

**Comment by EngineerSmith** [comment]
You can change `love.run` to implement your own game loop, including fixed time steps

[It's on the wiki](https://love2d.org/wiki/love.run)

**Comment by gcmartijn** [comment]
I use https://github.com/bjornbytes/tick

**Comment by MikuAuahDark** [comment]
I don't think there's C++ code that needs to be changed for this feature. An advanced users can override our default [`love.run`](https://love2d.org/wiki/love.run) main loop and implement their fixed frame there.
