### ISSUE TITLE
`love: symbol lookup error: /usr/lib/liblove-11.4.so: undefined symbol: SDL_JoystickHasRumble`

### ISSUE THREAD

**Issue by AM7999** [love2d/love#1794]
when trying to run love2d on a nintendo switch (yes i did use the ARM binaires) will give this error when running `love .` `love: symbol lookup error: /usr/lib/liblove-11.4.so: undefined symbol: SDL_JoystickHasRumble`

**Comment by slime73** [comment]
It sounds like the version of SDL2 you have headers for is newer than the version you're linking love to - `SDL_JoystickHasRumble ` was added in SDL 2.0.18 (and love only compiles code that calls it if the SDL headers being used are at least that new: https://github.com/love2d/love/blob/main/src/modules/joystick/sdl/Joystick.cpp#L395-L398)

**Comment by AM7999** [comment]
For fixing this issue what would i do?

**Comment by slime73** [comment]
You need to make sure to link to the same version of SDL2 that you're using headers for. Since you're using a custom and unsupported build setup I can't provide much more guidance than that.

**Comment by AM7999** [comment]
Alright then, Thanks anyway.
