### ISSUE TITLE
Linux: love.mouse.setGrabbed(true) makes showMessageBox() dialogs unclickable

### ISSUE THREAD

**Issue by rabbitboots** [love2d/love#1801]
On Linux, when `love.mouse.setGrabbed(true)` is set to keep the mouse within the confines of the application window, message boxes created with `love.window.showMessageBox()` cannot be clicked. The user can partially interact with the message box using the keyboard: enter to confirm, and escape to cancel.

I experienced the issue on Fedora Desktop 35 (my main PC), and I also got it to happen on an Ubuntu 22.04 Live USB. The 'About' screens on both state that they are running in X11 mode. (I tried the GNOME Wayland mode on Fedora and also got the issue, but as far as I understand, SDL2 is supposed to display a different, better-looking message box under Wayland, so maybe something isn't working correctly on my end. Maybe Nvidia proprietary drivers are interfering?) Anyways, I didn't experience the behavior on Windows 10. I'm currently lacking hardware and space to easily test other configurations, unfortunately.

It can be worked around in Lua project code by temporarily disabling mouse-grab:

```lua
local banked_grabbed = love.mouse.isGrabbed()
love.mouse.setGrabbed(false)
-- (Do the message box stuff)
love.mouse.setGrabbed(banked_grabbed)
```

[Here is a small test repro.](https://github.com/love2d/love/files/8550235/repro.zip) I'm curious if any Wayland users have the issue. This is what the basic X11 message box looks like:

![x11-message-box](https://user-images.githubusercontent.com/23288188/164992303-8e2f61d5-922f-41b6-a43b-16accb57448a.png)

My system's info:
```
Processor: Intel® Core™ i5-4430 CPU @ 3.00GHz × 4 
Graphics: NVIDIA Corporation GM107 [GeForce GTX 750]
OS Name: Fedora Linux 35 (Workstation Edition)
OS Type: 64-bit
GNOME Version: 41.5
Windowing System: X11
NVidia Driver Version: NVIDIA-SMI 510.60.02 Driver Version: 510.60.02
```

**Comment by slime73** [comment]
> On Linux, when love.mouse.setGrabbed(true) is set to keep the mouse within the confines of the application window, message boxes created with love.window.showMessageBox() cannot be clicked.

This makes sense from the perspective of the APIs on their own IMO. `setGrabbed` prevents the cursor from escaping love's main window, and a message box is a separate window.

That being said it does seem like it'd be a bit confusing to run into that situation. However love's code itself just calls SDL's cross-platform message box APIs, so the only thing we could do (if it's a good idea) would be to have the same sort of isGrabbed check inside love's code.

If you think its behaviour in this situation should be made consistent across operating systems, reporting it to the SDL bug tracker would probably be best. Although I'm not sure whether they'd want to change it to allow message box mouse usage across the board when grabbed, or disallow it.

**Comment by rabbitboots** [comment]
Thanks, I'll reach out to the SDL issue tracker. I'm honestly not sure if it should be made consistent -- basically I started digging into it because I encountered the behavior in a LÖVE game, presumably made by devs working from Windows, who also packaged their game as a Linux AppImage. (I'll report it to them with the workaround as well, just wanted to look into it a bit first.)
