### ISSUE TITLE
Audio related errors on execution 11.4

### ISSUE THREAD

**Issue by vinnyhorgan** [love2d/love#1802]
Hi! I have noticed, since switching to version 11.4, that i get these warnings every time i run a game:

`[ALSOFT] (WW) Cannot connect to server socket err = No such file or directory
[ALSOFT] (WW) Cannot connect to server request channel
[ALSOFT] (WW) jack server is not running or cannot be started
[ALSOFT] (WW) JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ALSOFT] (WW) JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ALSOFT] (WW) jack_client_open() failed, 0x11
[ALSOFT] (WW) Failed to initialize backend "jack"
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)`

I have fixed it following a previously open issue, but i didn't have this problem with version 11.3, so just wondering if anything had change related to audio. I thought it could have been something wrong with my Debian 11 installation, but even after recently switching to Ubuntu 22 LTS i noticed the same thing!

Thanks!

**Comment by vinnyhorgan** [comment]
Thanks, just curious to know what changed in 11.4, is it just a dependency upgrade?

**Comment by MikuAuahDark** [comment]
For Linux yeah there are upgrades to their dependency. It ships with newer OpenAL-soft compared to 22 LTS but I think the others are outdated.

**Comment by vinnyhorgan** [comment]
I figured out how to suppress the console output, I'll post it here if anyone needs it:

**.alsoftrc**

[general]
drivers=pulse
rt-prio=0
