### ISSUE TITLE
Android 11.4 doesn't access main.lua

### ISSUE THREAD

**Issue by EldestFear** [love2d/love#1806]
When I install 11.4.apk it simply doesn't work, I open and the first think that shows is the duck, but installing it from PlayStore or the 11.3.apk it ask if I allow to access my storage and then it work. 11.4 for some reason doesn't ask permission.

**Comment by zorggn** [comment]
Hi,

LOVE 11.4 in Android 10 and later looks for main.lua in a different location due to Android restrictions; Please see love2d/love-android#194. LOVE 11.3 works because it still targets Android 9.

**Comment by EldestFear** [comment]
I tried with the new location but my system block the access, I can't open any folder in storage/emulated/0/Android/Data with none file manager I have, neither with the Acode.
I try with Termux but the folder games isn't created and I can't create anything in the directory.

**Comment by MikuAuahDark** [comment]
Unfortunately the location `/storage/emulated/0/Android/data` is only accessible through MTP starting from Android 11.
