### ISSUE TITLE
Application data directory in macOS sandbox

### ISSUE THREAD

**Issue by eliteraspberries** [love2d/love#1807]
When I code sign love.app and try to run a .love file from the command line, I get the error:

```
% /Applications/love.app/Contents/MacOS/love thing.love

Error

[love "boot.lua"]:323: Cannot load game at path '/Users/dev/Library/Containers/org.love2d.love/Data/thing.love'.
Make sure a folder exists at the specified path.


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'error'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

I think this is because [Filesystem::getAppdataDirectory()](https://github.com/love2d/love/blob/main/src/modules/filesystem/physfs/Filesystem.cpp#L531) returns the hard-coded path "~/Library/Application Support/".

But the path is different in the sandbox. The directory can be obtained with [NSSearchPathForDirectoriesInDomains()](https://developer.apple.com/documentation/foundation/1414224-nssearchpathfordirectoriesindoma?language=objc) similar to [the iOS code](https://github.com/love2d/love/blob/main/src/common/ios.mm#L342).

Edit: Without code signing (no sandbox), NSSearchPathForDirectoriesInDomains() returns that hard-coded path.

**Comment by slime73** [comment]
I don't think the appdata directory is involved in loading a .love file - it's only used internally by love when dealing with file writes, not loading the game source.

Either way, love 12's code already uses the equivalent of that API.

**Comment by eliteraspberries** [comment]
You're right, that wasn't it. I still get the same error with the latest package. I'll investigate permissions...

**Comment by eliteraspberries** [comment]
Nevermind, this is just a limitation of the sandbox. (If anyone else comes across the same problem, see [the answer here](https://developer.apple.com/forums/thread/13901).) Placing the .love file in the Resources folder works fine.
