### ISSUE TITLE
love.filesystem.newFile deprecated message when calling love.thread.newThread

### ISSUE THREAD

**Issue by EngineerSmith** [love2d/love#1811]
Love 12; latest commit 4a1d01c

When calling `love.thread.newThread("thread.lua")` it will cause a deprecated message to show:
```
LOVE - Warning: Using deprecated function love.filesystem.newFile (renamed to love.filesystem.openFile)
```
Note the missing file name and line number unlike the usual deprecated message format `LOVE - Warning: dir/file.lua:99: ...`

Reproduce:
```lua
--main.lua
local thread = love.thread.newThread("thread.lua")
```
```lua
--thread.lua
return
```
```lua
-- conf.lua
love.setDeprecationOutput(true)
love.conf = function(t)
  t.console = true
end
```

**Comment by modcos** [comment]
I get same warning when use ```love.filesystem.newFileData()```

**Comment by EngineerSmith** [comment]
Most likely, as `love.thread.newThread` also calls upon `newFileData`

**Comment by slime73** [comment]
Fixed. Thanks!
