### ISSUE TITLE
Feature request: ImageData encode() for HDR content/formats

### ISSUE THREAD

**Issue by Froyok** [love2d/love#1813]
**ImageData:encode()** currently only supports **TGA** and **PNG** which cannot handle HDR data. 
Would it be possible to get **.hdr** or **.exr** support for encoding (exr would be ideal) ?

In my project I need a way to save/export my current framebuffer (a rgba16f Canvas) to disk for further processing in another application afterward. Tonemapping isn't an option since I need the original HDR data and the existing format (TGA and PNG) are not precise enough if I were to compress the original data (for example using Log space).

Right now my workaround will probably be to export the framebuffer via RenderDoc, but this isn't convenient. Doing it from the game would be more productive for me. :)

**Comment by slime73** [comment]
Saving exr files is implemented now in [9c46b75](https://github.com/love2d/love/commit/9c46b751381385eeb37e907bf748cc25ed9fb20e).
