### ISSUE TITLE
Windows High DPI Only Works Through Environment Variable

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1814]
As per 17b359f, setting `t.highdpi=true` doesn't work but setting environment variable `SDL_WINDOWS_DPI_SCALING=1` works.

This is due to `love.mouse` initialize SDL video subsystem before `love.window`, where the hint for Windows high DPI support is set. The hint must be set before SDL video subsystem is initialized. slime plan to fix the issue instead of reordering the `require` in boot.lua so I wrote this issue for tracking purpose.

**Comment by slime73** [comment]
Fixed in d586d18
