### ISSUE TITLE
love.image.newImageData can't fail

### ISSUE THREAD

**Issue by nephele-gh** [love2d/love#1816]
Hey there,
I have a bit of an api problem. Basically I have "mostly" textures in my textures dir, but some aren't textures like readme files and license informations.

Ideally I would like to simply ignore files that are not images when parsing them, but I can't know beforehand whether a file is a texture or not (as users potentially will add textures to the game.)

Now, my problem arrises when trying to use love.graphics.newImageData, instead of giving me an object nil, or maybe a "nil, error" pair it will call the error handeler and thereby stop my game entirely. 
I don't see a way how I could use this safely to be able to only load the textures.

The error is also not documented on the wiki. 
This is an example of what I got when it encountered an readme file.
lua/ui.lua:162: Could not decode file 'textures/blocks/poppy-textures-minimania/Readme.md' to ImageData: unsupported file format

**Comment by marcotrosi** [comment]
can you share the code that loads the textures?

**Comment by radgeRayden** [comment]
Using `pcall` should be enough to solve your issue. Example:
```
local function loadImg(path)
    return love.image.newImageData(path)
end

local img, err = pcall(loadImg, "main.lua")
print(img, err)
```

**Comment by nephele-gh** [comment]
The relevant segment is probably jus this: 
```
function ui.loadTextures(directory, container)
	if not container then container = {} end
	local entries = love.filesystem.getDirectoryItems(directory)
	if #entries == 0 then return container end
	for i, file in pairs(entries) do
		local path = directory .."/".. file
		local entry = love.filesystem.getInfo(path)
		if entry.type == "directory" and file ~= ".git" then
			container[file] = {}
			container[file] = ui.loadTextures(path, container[file])
		elseif entry.type == "file" or entry.type == "symlink" then
			if file ~= "license.txt" and file ~= "Readme.md" then
				local imageData = love.image.newImageData(path)
				local hash = love.data.hash("sha512", imageData:getString())
				gameloop.textures[hash] = {data = imageData}
				container[file] = hash
			end
		end
	end
	return container
end
```
The line that then trows the error is this one local imageData = love.image.newImageData(path)

The if file ~= "license.txt" and file ~= "Readme.md" then line is already a workaround for this issue, I had added the Readme.md part because of this
The entire game code is here if you would like to see it, but probably a bit much for this issue alone :) 
https://git.gryphno.de/nephele/poppy-client/src/commit/fb0c3357dc46a7e2e72f5c93badf1e4f59cdb47f/lua/ui.lua#L161

**Comment by marcotrosi** [comment]
I would simply check the file extension

**Comment by radgeRayden** [comment]
Checking the file extension is flawed because you can still create a file that _appears_ to be an image (by file extension), but is in fact something else. The love image loading code already has logic to detect whether the file is what it says it is - most image formats have some sort of header, so it's best to just let it do its job, and if you can't trust the images use pcall like I mentioned above.

**Comment by nephele-gh** [comment]
I am not sure what the file extension has to do with the love2d api? In any case, sometimes I am simply too lazy to add file extensions, they are uneccesary (The only reason they are even in the repo is so it somewhat works on windows). this seems like a bad workaround.

**Comment by slime73** [comment]
Both options are viable depending on what you want. `pcall` will let you handle any failure, and checking a file extension will let you handle files that don't match your convention, and error if a file does match but has bad data (which you might want to do).

In any case, all the tools to do what you want are already provided.

**Comment by nephele-gh** [comment]
If it is intended behaviour that this call may fail it might be a good idea to document it on the wiki, and in which cases it can fail :)

**Comment by slime73** [comment]
Almost all love APIs will throw a Lua error when given bad data (newImage/newImageData isn't unique or anything in this regard). I don't think it makes a lot of sense to add a note to every single function saying so, but maybe there's a specific place elsewhere on the wiki that could mention it.

**Comment by nephele-gh** [comment]
Does the api have well formed errors for these cases? If there are those could be documented. If it's just "something" then I would agree that it does not matter if the specific calls have a note for this or not.

**Comment by marcotrosi** [comment]
@nephele-gh just in case you change your mind

```
function getFileExt(name)
   return name:match(".*%.(.*)$")
end
```

**Comment by nephele-gh** [comment]
Thanks, but my OS does not really use file extensions but rather mimetypes. So I won't be adding it :)
(If love2d adds a way to check the mimetype with file xattrs I could use that in the future though)

**Comment by marcotrosi** [comment]
ya I don't think it's Löve's task to do that, but you can add that anytime with a lib
