### ISSUE TITLE
Failed to newArrayImage by multiple dds image

### ISSUE THREAD

**Issue by xiejiangzhi** [love2d/love#1817]
```
local path = "some_img.dds"
love.graphics.newArrayImage({ path })
=> Image: 0x7f925e090110
love.graphics.newArrayImage({ path, path })
ERROR: Cannot create image (OpenGL error: invalid value)
```

for one dds image or more png image , it's ok,  got error when give multiple dds image.

love2d 11.4 on MacOS, Windows 10

**Comment by xiejiangzhi** [comment]
[newarrayimage.zip](https://github.com/love2d/love/files/9276114/newarrayimage.zip)

attachment is error demo

```
local lg = love.graphics

local arr11 = {'a.png' }
local arr12 = {'a.dds' }
local arr21 = {'a.png', 'b.png'}
local arr22 = {'a.dds', 'b.dds'}

function love.load()
  lg.newArrayImage(arr11)
  lg.newArrayImage(arr12)
  lg.newArrayImage(arr21)
  lg.newArrayImage(arr22)
end

function love.update(dt)
end

function love.draw()
  lg.print('hello', 10, 10)
end
```

**Comment by xiejiangzhi** [comment]
Hi @slime73  could you take a look at this issue?

**Comment by slime73** [comment]
Yes, I look at all issues when I have the time. Thanks for providing a repro project.

**Comment by Unix0815** [comment]
Is this really fixed? I get exactly the same error with Love 11.4 and any DDS texture in combination with ArrayImages

**Comment by MikuAuahDark** [comment]
Could you try the latest build in GitHub Actions and see if it persist?

**Comment by Unix0815** [comment]
It works great with that. So the download on the Love2D page is outdated.

**Comment by MikuAuahDark** [comment]
Yes, we're planning on releasing 11.5 soon, so 11.4 (which is the latest in the website) still have this bug.
