### ISSUE TITLE
getSystemLimits seems to report an msaa value higher than is actually supported

### ISSUE THREAD

**Issue by radgeRayden** [love2d/love#1820]
![image](https://user-images.githubusercontent.com/8618621/178166839-a2ed4344-b39c-4899-8261-1b37c5b9ba6e.png)

Using the following code:
```lua
local lg = love.graphics
local msaa = lg.getSystemLimits().canvasmsaa

lg.setBackgroundColor(.8, .9, 1)
lg.setNewFont(14)
love.window.setMode(240, 240, {msaa=msaa})

function love.draw()
	for i=40,200,40 do
		for j=50,170,40 do
			lg.setColor(0,0,0)
			lg.print("Generated with MSAA: "..msaa, 10, 10)
			
			lg.circle("fill", i, j, 20)
			lg.setColor(1,1,1)
			lg.circle("fill", i, j, 17.8)
			
		end
	end
end
```

Even though my GPU reports an MSAA value of 32, the rendering looks as if no MSAA was applied. Manually setting the value to something reasonable like 8 yields the expected result.

Renderer info:
```
OpenGL 3.3.0 NVIDIA 516.59 NVIDIA Corporation NVIDIA GeForce RTX 3080/PCIe/SSE2
```

OS is Windows 11.

**Comment by slime73** [comment]
In love 11, `canvasmsaa` is independent from the max backbuffer MSAA.
