### ISSUE TITLE
All LÖVE applications open as a blank screen on Windows 11

### ISSUE THREAD

**Issue by sh0ckR6** [love2d/love#1821]
Hey all!
A few days ago, I tried to install [Olympus](https://github.com/EverestAPI/Olympus), Celeste's mod manager, which runs on LÖVE. However, after opening the program, the window was completely blank. After spending a bit of time debugging with the folks over in the Celeste discord, I tried a few other programs that were based on LÖVE, and they all had the same problem. Every single one of them opened to a blank screen which had the window's background colour.

I'm currently running Windows 11 Home (Insider Previews), on build 25151.1010.
Below are the apps I tried and the resulting screens

**Lönn**
https://github.com/CelestialCartographers/Loenn
![image](https://user-images.githubusercontent.com/68568464/178578664-bfd31ea1-2312-416f-a3df-0214d578a431.png)

**Olympus**
https://github.com/EverestAPI/Olympus
![image](https://user-images.githubusercontent.com/68568464/178578780-4b6cabe5-6844-41a9-9853-3f7fb249e757.png)

**Löve-Example-Browser**
https://github.com/love2d-community/LOVE-Example-Browser
![image](https://user-images.githubusercontent.com/68568464/178578895-87d71f50-6e3d-4b9f-a279-33c56ec5a44f.png)

##### Apologies if this is a duplicate, I tried searching beforehand and couldn't find anything!

**Comment by slime73** [comment]
Which GPU is your computer using? Also, is your system using the latest available version of your GPU's graphics drivers?

I assume this is love 11.4 but it wasn't explicitly mentioned, so double checking the love version would be a good idea too.

**Comment by sh0ckR6** [comment]
I'm running a Radeon RX 570 with latest drivers on love 11.4. Just updated drivers to make sure and I'm still having this issue.

**Comment by slime73** [comment]
Which driver version are you using? I know of someone who discovered some pretty major bugs in the AMD 22.7.1 driver, which impacts love.

**Comment by Dispenserim** [comment]
@sh0ckR6 I have the exact same issue with LOVE2D 11.X using drivers 22.7.1, but any driver version prior to that does not have this issue. Reproduced on a 6900 XT, 6800 XT, Vega 64, and now Ryzen 7 5700U with it's integrated graphics.

I suggest the OP reports this issue to AMD (I already have on multiple fronts), so they take action, as this is a driver-specific problem introduced with the big OpenGL performance boost in drivers 22.7.1. It renders all LOVE2D projects using any version past 0.10.2 unusable.

**Comment by jaykyburz** [comment]
Reporting in that I updated my graphics drivers to 22.7.1 on my Vega 64, Windows 10 and it broke my love games in both 11.3 and 11.4.

I'm attempting to roll back my drivers now to see if I can  get working again, but happy to help debug in any way I can.

**Comment by slime73** [comment]
AMD just released a new driver version which claims to solve the issue:
> Fixed Issues
> * Games based on LOVE2D™ engine may be rendered incorrectly.

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-8-1

**Comment by Aiq0** [comment]
Some [https://love2d.org/forums/viewtopic.php?p=251352#p251352](forum user) also had this problem and it was solved by updating the driver.
