### ISSUE TITLE
Love 11.4 - Some PulleyJoint Methods are not defined?

### ISSUE THREAD

**Issue by sysl-dev** [love2d/love#1823]
```lua
love.graphics.setBackgroundColor(0.41, 0.53, 0.97) --set the background color to a nice blue
love.window.setMode(650, 650) --set the window dimensions to 650 by 650 with no fullscreen, vsync on, and no antialiasing

love.physics.setMeter(64) --the height of a meter our worlds will be 64px
world = love.physics.newWorld(0, 9.81*64, true) --create a world for the bodies to exist in with horizontal gravity of 0 and vertical gravity of 9.81
objects = {}

--let's create a couple blocks to play around with
objects.block1 = {}
objects.block1.body = love.physics.newBody(world, 200, 550, "dynamic")
objects.block1.shape = love.physics.newRectangleShape(0, 0, 50, 50)
objects.block1.fixture = love.physics.newFixture(objects.block1.body, objects.block1.shape, 6) -- A higher density gives it more mass.
objects.block2 = {}
objects.block2.body = love.physics.newBody(world, 300, 550, "dynamic")
objects.block2.shape = love.physics.newRectangleShape(0, 0, 50, 50)
objects.block2.fixture = love.physics.newFixture(objects.block2.body, objects.block2.shape, 5) -- A higher density gives it more mass.
joint = love.physics.newPulleyJoint( objects.block1.body, objects.block2.body, 200, 550, 300, 550, 200, 0, 300, 0, 1, true )
joint:getRatio() -- This should work [It Does]
joint:setRatio(1) -- This should work [It does not]
function love.draw()

  love.graphics.setColor(0.20, 0.20, 0.20) -- set the drawing color to grey for the blocks
  love.graphics.polygon("fill", objects.block1.body:getWorldPoints(objects.block1.shape:getPoints()))
  love.graphics.polygon("fill", objects.block2.body:getWorldPoints(objects.block1.shape:getPoints()))

  love.graphics.setColor(1,1,1,1)
end

function love.update(dt)
world:update(dt)
end
```
![image](https://user-images.githubusercontent.com/13181256/180624320-9e9bfa92-27de-4492-b760-cfa55d1c5aba.png)

Sorry for the mess of copypaste code, I have a library for interfacing with Box2D but I wanted the example to reproduce the error to be simple so I copied and pasted parts from the wiki quickly.

**Comment by sysl-dev** [comment]
Testing missing:
1. [setRatio](https://love2d.org/wiki/PulleyJoint:setRatio)
2. [setMaxLengths](https://love2d.org/wiki/PulleyJoint:setMaxLengths)
3. [setConstant](https://love2d.org/wiki/PulleyJoint:setConstant)

**Comment by slime73** [comment]
I think it might be a documentation mistake - it looks like the current version of Box2D doesn't support a setRatio. (Although maybe old versions did?)

**Comment by sysl-dev** [comment]
What about [setMaxLengths](https://love2d.org/wiki/PulleyJoint:setMaxLengths) or [setConstant](https://love2d.org/wiki/PulleyJoint:setConstant) for adjusting the length of the rope? The ratio can be defined when making the joint but the rope length can't.

**Comment by sysl-dev** [comment]
All of these are no longer listed anywhere for Box2d documentation, so I guess recreate the joint if you need to make changes is the only option.

MotorJoint on the wiki is also missing setMaxForce/setMaxTorque.

Thank you for looking into it.
