### ISSUE TITLE
Segfault when adding an empty string to a Text

### ISSUE THREAD

**Issue by eevee** [love2d/love#1824]
Reliably crashes:

```
love.graphics.newText(love.graphics.getFont()):add("", 0, 0)
```

Appears to be from an out of bounds access into an empty `vertices` [in `addTextData`](https://github.com/love2d/love/blob/2f17cab3b4645ee41d3ca028e86e2e7f335662c3/src/modules/graphics/Text.cpp#L119).  This was fixed in 2f17cab3, but then unfixed in c59c85e0 to fix #1555.

**Comment by slime73** [comment]
Thanks for the report! I *think* I've fixed it with 870021b, but I haven't been able to reproduce the crash itself on my computer (probably just a difference in how std::vector allocates things internally on my system), so I'm not 100% positive my fix is all that's needed.

**Comment by eevee** [comment]
Oh, interesting.  For me it specifically dies with an assert, which I took for granted would have led swiftly to a segfault:

```
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = love::graphics::vertex::XYf_STus_RGBAub; _Alloc = std::allocator<love::graphics::vertex::XYf_STus_RGBAub>; std::vector<_Tp, _Alloc>::reference = love::graphics::vertex::XYf_STus_RGBAub&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

...but if `transformXY` does nothing for zero elements, then maybe not.

No idea why I have an assertion here and you don't — this is just the Arch Linux package — but if this was the only issue then that commit oughta fix it  :)

**Comment by slime73** [comment]
I've run into the same sort of problem before (`&vec[0]` causing problems when the array is empty) so it makes sense that it was an issue I think.

**Comment by eevee** [comment]
Kind of funny when `vector::data()` appears to do the same thing, but I guess there's no `operator&[]` overload, so `operator[]` has no way of knowing that's all you're doing.
