### ISSUE TITLE
Android Background music continues to play, after app is minimized

### ISSUE THREAD

**Issue by powertomato** [love2d/love#1828]
I'm having issues that background music continues to play after the app is minimized.
During my investigation on how to fix or work around it I found the following code:

https://github.com/love2d/love/blob/878ad785bcb121a7faea1fe66f48ed7c894af609/src/modules/event/sdl/Event.cpp#L626

I debugged to confirm the code is actually executed (it is). But for some reason it doesn't actually pause the audio sources. The source type (static/stream) makes no difference.

I can replicate this behavior with two phones:
 * A Samsung Galaxy S20 (SM-G981B) with Android 12 (API 31)
 * A Huawei p30 pro with Android 10 (API 29)
 
As well as with a virtual Pixel 2 with Android 12 (API 31).

My current woraround was to implement the `love.focus` handler and pause the background music manually.

An other odd detail: if, in the same `love.focus`-handler, I check wether the source is playing with `source:isPlaying()` they will return `false`.

**Comment by MikuAuahDark** [comment]
I tried to reproduce this with this code.

```lua
function love.load()
	rolling = love.audio.newSource("test.mp3", "stream")
	rolling:setLooping(true)
end

function love.draw()
	love.graphics.print(tostring(rolling:isPlaying()), 64, 64)
end

function love.mousereleased()
	if rolling:isPlaying() then
		rolling:pause()
	else
		rolling:play()
	end
end
```

Then run the app, tap anywhere to start the audio, then press the home button. I can't reproduce it on Samsung Galaxy A52s (SM-A528B) and Pixel 3 AVD, both running Android 12. Are there any specific instruction on how to reproduce this?

**Comment by powertomato** [comment]
Thanks for looking into it. I can confirm your above code works as expected. It helped me find the source of the culprit, however. In my code the `play()` call happens in the `love.update` function and wether or not it happens depends on several factors. I was able to reproduce the issue with some small changes to your code:

```lua
local play = false

function love.load()
	rolling = love.audio.newSource("test.mp3", "stream")
	rolling:setLooping(true)
end

function love.draw()
	love.graphics.print(tostring(rolling:isPlaying()), 64, 64)
end

function love.mousereleased()
    play = not play
end

function love.update()
    if play then
	rolling:play()
    else
        rolling:pause()
    end
end
```

**Comment by MikuAuahDark** [comment]
In that case, I think there's another 1 frame that slip through just after LOVE receives event that it should pauses all sources. So, the flow will look like this:

```
event poll
- got event "will be minimized"
- all playing audio is paused
update loop
- audio is played again
draw loop
present draws

event poll
- event poll is blocked until it got "app restored" event
- got event "app restored"
- all previously played audio is resumed
update loop
draw loop
present draws
```

I think the actual solution to this is using OpenAL-soft's [`ALC_SOFT_pause_device`](https://openal-soft.org/openal-extensions/SOFT_pause_device.txt) extension, but falling back to the current code if it's unavailable.

**Comment by powertomato** [comment]
The frame slipping and replaying seems plausible. I also my initial claim that `source:isPlaying()` returns `false` is wrong and I probabbly debug-printed the state before `source:play()` was called again.

Using the following update function, `play` gets printed once after minimizing the app. 
```lua
function love.update()
    if play then
        if not rolling:isPlaying() then 
            rolling:play()
            print("play")
        end
    else
        rolling:pause()
    end
end
```
 
> I think the actual solution to this is using OpenAL-soft's [`ALC_SOFT_pause_device`](https://openal-soft.org/openal-extensions/SOFT_pause_device.txt) extension, but falling back to the current code if it's unavailable.

I would agree current solution seems a bit like a hack. As for the fallback in addition to pausing, it might make sense to also set the volume of all playing sources to 0 and restore the volumes again on regaining focus. This could lead to other problems, but they seem less annoying than background music still playing. But that's just my two cents.
