### ISSUE TITLE
Switching default audio output device on changed

### ISSUE THREAD

**Issue by HDPLocust** [love2d/love#1830]
When switching the audio device by default (tested on Windows), the audio stream is directed to the old device, so if, for example, you plug in a USB headphone (which is another device), the sound will be directed to the speakers, and vice versa.

Also, it is possible in love to get a list of recording devices, and it would be nice to get the functionality of getting a list of playback ones, to be able to get the current device and the default device and the ability to switch, it becomes possible to at least manually switch the device when it changes. Openal supports this functionality.

**Comment by MikuAuahDark** [comment]
This has been implemented in next major version of LOVE. #1805

**Comment by HDPLocust** [comment]
Thanks a lot
