### ISSUE TITLE
Retrieve 3rd-party Library Versions

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1832]
A quick discussion in Discord gives an idea that we should have LOVE function that retrieve 3rd-party library versions. This is useful for diagnosing 3rd-party library-related issues.

**Comment by slime73** [comment]
On most platforms, dependencies are provided with love. The exception is if you compile manually on Linux or install a Linux package manager's version of love - but in that case you can find out dependency versions via existing tools like `ldd` or `readelf`, so I feel like this change doesn't add much.
