### ISSUE TITLE
[12.0] Mouse Joint not working

### ISSUE THREAD

**Issue by Klonan** [love2d/love#1834]
Might be related to the Box2D update from 2.3 to 2.4.1.
It is a plain default mouseJoint

11.4:

https://user-images.githubusercontent.com/11986037/186956659-38f50ddd-7345-462b-a746-deb2c8372a44.mp4

12.0:

https://user-images.githubusercontent.com/11986037/186956772-0e9df7ef-e5b8-41db-8f58-9f1618b14dde.mp4

**Comment by Klonan** [comment]
Yes so this is related to the new 'Stiffness' of the joint that BOX2d added,
It has a default value of 0 in `b2MouseJointDef`,
Which means all the solvings end up applying 0 impulse.

Not sure if we want to maintain the easy behavior in 11.4, where it 'just works' without having to set the stiffness property on the mouse joint after creation, i.e, set a default joint stiffness that isn't 0.

E.g, this is a stiffness value of 100.0f:

https://user-images.githubusercontent.com/11986037/186959403-906d847e-d247-4b95-98be-b5412d4cfb19.mp4

(Set in the MouseJoint constructor in `src/modules/physics/box2d/MouseJoint.cpp`):
![image](https://user-images.githubusercontent.com/11986037/186959673-6d3901c5-3ee2-4842-aaf4-a3ec6580dd5d.png)

**Comment by slime73** [comment]
This is fixed by [9e4b70c](https://github.com/love2d/love/commit/9e4b70c498aaab16e48ca5d1ffbc716dcccc3341).
