### ISSUE TITLE
Flatpak installation not working (for me at least)

### ISSUE THREAD

**Issue by iskolbin** [love2d/love#1836]
Installed love using
```
flatpak install flathub org.love2d.love2d
```
After succesful install cannot run any projects, it's always an error:
```
ilya@strix:~/Documents/lua_projects$ flatpak run org.love2d.love2d ruf
Error: [love "boot.lua"]:323: Cannot load game at path '/home/ilya/ruf'.
Make sure a folder exists at the specified path.
stack traceback:
	[love "boot.lua"]:345: in function <[love "boot.lua"]:341>
	[C]: in function 'error'
	[love "boot.lua"]:323: in function <[love "boot.lua"]:126>
	[C]: in function 'xpcall'
	[love "boot.lua"]:355: in function <[love "boot.lua"]:348>
	[C]: in function 'xpcall'
```
BTW even the path is wrong (whole path is `/home/ilya/Documents/lua_projects/ruf`), yet even specifing absolute path leaves the same problem:
```
ilya@strix:~$ flatpak run org.love2d.love2d /home/ilya/Documents/lua_projects/ruf
Error: [love "boot.lua"]:323: Cannot load game at path '/home/ilya/Documents/lua_projects/ruf'.
Make sure a folder exists at the specified path.
stack traceback:
	[love "boot.lua"]:345: in function <[love "boot.lua"]:341>
	[C]: in function 'error'
	[love "boot.lua"]:323: in function <[love "boot.lua"]:126>
	[C]: in function 'xpcall'
	[love "boot.lua"]:355: in function <[love "boot.lua"]:348>
	[C]: in function 'xpcall'
```

Apt version works without any problems (but as of writing version is older: 11.3).

Flatpak version: `Flatpak 1.8.5`
Flatpak record: `LÖVE                                     org.love2d.love2d                                      11.4              stable        user`
OS: `PopOS 20.04 LTS`
Kernel: `Linux strix 5.17.5-76051705-generic #202204271406~1653440576~20.04~6277a18-Ubuntu SMP PREEMPT Thu Ma x86_64 x86_64 x86_64 GNU/Linux`

**Comment by slime73** [comment]
We don't have an official flatpak for LÖVE that's created by us - your best bet is probably to find out who made it and contact them.

**Comment by slime73** [comment]
Looks like the repository for it might be here: https://github.com/flathub/org.love2d.love2d

Unfortunately they got our name wrong (I think it should be `org.love2d.love` rather than `org.love2d.love2d`).

**Comment by iskolbin** [comment]
Ok, will try contact them. Thanks!
