### ISSUE TITLE
 music:tell() function is broken.

### ISSUE THREAD

**Issue by Jevil-Chaotic-Coder** [love2d/love#1837]
So I use a deltarune modding software called Kristal built on this, I tried to use the music:tell() function to get the song time, but I guess the buffer is broken or something because for every loop the timestamp it gives is offset, gets very severe and it isn't consistent to my knowledge, is there a workaround or patch? Thanks!

-SciSpace

**Comment by NyakoFox** [comment]
As I said, I already reported this. [#1810](https://github.com/love2d/love/issues/1810)

**Comment by Jevil-Chaotic-Coder** [comment]
duplicate
