### ISSUE TITLE
Rendering to CubeImage faces

### ISSUE THREAD

**Issue by FloatingBanana** [love2d/love#1840]
Would be very nice if there was a way to dynamicaly render things to CubeImage faces, just like Canvases. I'm implementing shadow mapping for my 3D renderer and I need to update the shadow map every frame in a CubeImage for point lights, but currently there's not an reasonable way to modify them for this kind of operation...

**Comment by slime73** [comment]
You can create a cubemap canvas via `love.graphics.newCanvas(w, h, {type = "cube"})`, which should let you do what you want. `love.graphics.setCanvas` has a variant that lets you select which cube face to render to, when passing in a cubemap canvas.

**Comment by FloatingBanana** [comment]
Oof, and here's the naive me thinking that I've read every single bit of the documentation 🤦. Thanks for the tip, but I think it would be worth adding a hint about it in the `love.graphics.newCubeImage` page.
