### ISSUE TITLE
Add optional parameter to love.filesystem.load to prevent loading bytecode

### ISSUE THREAD

**Issue by slime73** [love2d/love#1849]
LuaJIT supports Lua 5.2+'s APIs for this via `luaL_loadbufferx`. The parameter should probably match stock Lua's: https://www.lua.org/manual/5.3/manual.html#pdf-load

**Comment by MikuAuahDark** [comment]
Would this break love.js which uses plain Lua 5.1 instead of LuaJIT?

**Comment by slime73** [comment]
Not if it checks for support via a #define (if that's possible).

**Comment by MikuAuahDark** [comment]
I think I want to do this tomorrow.

**Comment by MikuAuahDark** [comment]
d65b253d60f56a19f495a3e65cf1a3f170478401
