### ISSUE TITLE
[12.0] Vulkan problems

### ISSUE THREAD

**Issue by Er2ch** [love2d/love#1852]
There will be problems with new Vulkan backend in 12.0 to be fixed.

- [x] Stencil does not works at all (752a386640d5a6ff5f61dc98b2197c90b16c0d83)

- [x] VSync disabling does not work (with both setMode and setVSync)

OS: Linux 5.15 on amd64
GPU: AMD Radeon RX550

**Comment by slime73** [comment]
vsync-off via setMode should be fixed in [d70514b](https://github.com/love2d/love/commit/d70514b2d13e41c8f68db6a805261910fde9f589).

**Comment by Er2ch** [comment]
omg this issue still exists
VSync is fixed and I don't find other problems so this issue can be closed.
