### ISSUE TITLE
Program isn't appearing on my computer no matter what

### ISSUE THREAD

**Issue by ILikeCellMachine** [love2d/love#1860]
It's just very hard to open CelLua because love2d won't setup and install on my computer

**Comment by pythonmcpi** [comment]
What exactly are you doing? (Explain each step of what you do.) Are there any error messages? If so, please copy paste them here. If not, then what do you see on your screen?

**Comment by ILikeCellMachine** [comment]
I figured it out, I found it on the Windows homescreen. I will close the issue now.
