### ISSUE TITLE
On Latest Windows 11 build - nothing is drawing. Just black or blue screen. Even errors not printing

### ISSUE THREAD

**Issue by AldieNightStar** [love2d/love#1863]
Hello i took this example to run and it's shows me blue screen from Love2D canvas and that's all. Even if there is some error, i can't see anythink at all. So the problem it is not drawing anymore on Windows 11. Please check and fix it. Otherwise a lot of Love2D games will not just work on Windows 11 latest build

https://github.com/love2d-community/LOVE-Example-Browser.git

Also i created empty project and just add "love.graphics.rectangle('fill', 10, 10, 100, 100)" and it not drawing nothing. It is crash.

**Comment by MikuAuahDark** [comment]
Please screenshot the message box shown when you run this love file: https://cdn.discordapp.com/attachments/329404715521802241/964536815908429824/renderinfo.love

**Comment by MikuAuahDark** [comment]
Have you tried this? https://github.com/love2d/love/issues/1863#issuecomment-1311549009

**Comment by MikuAuahDark** [comment]
You're using AMD driver 22.7.1. This driver is known to have issues with LOVE. Please downgrade/rollback or upgrade your drivers.

There's not much we can do in here unfortunately.
