### ISSUE TITLE
CCS for 3D textures is disabled

### ISSUE THREAD

**Issue by lua-rocks** [love2d/love#1868]
Every time I start Love on my new Nitro 5  laptop with Manjaro Linux, I see this message:

```
../mesa-22.2.3/src/intel/isl/isl.c:2216: FINISHME: ../mesa-22.2.3/src/intel/isl/isl.c:isl_surf_supports_ccs:
CCS for 3D textures is disabled, but a workaround is available.
```

Can you please tell me what it means?

**Comment by slime73** [comment]
That message is coming from your graphics driver - you could try updating it to the latest possible version if you haven't already. Either way there's not much love's own code can do about that message since it's not produced by love.
