### ISSUE TITLE
Enhancement: love2d on the AppStore?

### ISSUE THREAD

**Issue by SugarRayLua** [love2d/love#1870]
Hello. Has love2d been previously submitted to the AppStore for approval so wouldn't need to be sideloaded on iOS? Other similar apps seemed to have been approved on the AppStore (e.g. LuaTouch+, Codea, etc.). Thanks!

**Comment by slime73** [comment]
We don't really have the capacity to properly develop and support an iOS love app for the App Store. Right now the love iOS app is just the absolute bare minimum needed to run love games (a file picker and nothing else) but I think more would be needed - and definitely more support would be needed - to have a proper App Store app that's published and maintained.

**Comment by SugarRayLua** [comment]
Okay, thank you for the reply. Even at a bare minimum (and if it was a free app) I thought it might broaden Love's exposure to the iOS mobile community. It looks like there is a Love app for Android on Google Play.

**Comment by slime73** [comment]
There is, but the Google Play store tends to have fewer and less strict requirements, and even that app isn't really maintained right now.

**Comment by SugarRayLua** [comment]
Understood, thanks for the clarification. I am enjoying using the sideloaded version of Love2d on my iPad. I either write Lua scripts on my Mac or use the Textastic app on my iPad to write scripts. Textastic has a file directory which I can store other scripts and assets and lets me zip up my final project into a .love file which I then move to the Love2d app on my iPad. If I use pre-11.0 Love commands, I can even pass the .love files I create to the Love Web Builder to make love.js files that I send to others that don't have Love installed--very cool!

**Comment by SugarRayLua** [comment]
P.S.,
I found out a major disadvantage of installing Love2d app via Xcode (as it is released currently for the iPad) is that unless the user has a paid Apple developer certificate, the app only lasts for 1 week on the user's mobile device and needs to be reinstalled again through Xcode. Alternatively, the user would need to load the Love2d Xcode project in Xcode, create an Xcode archive file, and use on of the signing apps or service to produce an .ipa file that could be downloaded to an iOS mobile device.

My last suggestion would be to add a suggestion on the "Getting Started" Love wiki page under iOS is to encourage the user to enable the following entitlements when building the Love app in Xcode:

Info.plist Values:
Supports Document Browser
Supports Opening Documents in Place

Packaging:
Generate Info.plist File

Doing so will enable the Love app directory to be recognized by the iOS Files app so users can directly transfer Love files they create (or have stored on their iOS mobile device) to the Love iOS app on their device (rather than having to connect their mobile device to iTunes or their Finder app on a desktop Mac to transfer files). The user thought may have to install at least one .love file into their Love iOS app via a desktop connection to their Mac for the Love directory to start to show up in the iOS Files app. 

Fyi.

**Comment by SchreiberChiang** [comment]
> Info.plist Values:
> Supports Document Browser
> Supports Opening Documents in Place

i open two bool,but i can't find folder for love2d

**Comment by SchreiberChiang** [comment]
> 

![image](https://user-images.githubusercontent.com/51290905/229547872-a96500c8-5448-4142-b310-253b46ae00ff.png)

**Comment by SugarRayLua** [comment]
Hi, @SchreiberChiang.

Am I correct in understanding you that you've got love2D up and running on your iOS mobile device but you don't see any folder in the "Files" app on your iOS mobile device associated with your iOS love 2D app to put love2D files into? It's been a while since I've installed it on my iPad but would then refer you to the last paragraph I wrote which says for some reason I had to actually manually transfer the first file to my iOS love 2d app on my mobile device via being directly connected to iTunes on my Mac (i.e. using iTunes to on Mac while my iPad is plugged into my Mac and transferring the .love file into love2d's directory on my map via iTunes). Once I did that, the the "documents" folder appeared on my iOS file app connected to love2D, and I could load files directly to the Love2D app with the Files app and not being hooked up to my Mac. 

(See attached screenshots: first of my iOS Love2D documents folder viewed with the iOS files app on my iPad and the second with the directory screen that opens when you tap on the Love2D file on your iOS device).

*Sorry, as I mentioned, it's been a little while since I loaded the iOS Love2D Xcode project into Xcode and sideloaded it on my iPad. You didn't mentioned if you also set the following option that I wrote in Xcode:

Packaging:
Generate Info.plist File

Fyi-- hope that helps. 


![IMG_1259](https://user-images.githubusercontent.com/76857619/229653999-43cbae6d-14c0-41f0-bcba-55f568811cea.jpeg)



![IMG_1260](https://user-images.githubusercontent.com/76857619/229654029-e2912949-4377-43f1-99ef-a967e622a125.jpeg)

**Comment by SchreiberChiang** [comment]
@SugarRayLua 

thank you ,i can see love folder ,but  have some error , about  packed .love file


i use a software，then add a text file ,edit code ,then change file type to ".lua" ,then packed main.lua to main.zip ,change ".zip" 
to ".love", move this file to love folder, then i want open it on love, error😭😭😭

![IMG_7180](https://user-images.githubusercontent.com/51290905/229865857-b6260e97-a5dc-4e73-8bab-ad1c2158594a.PNG)

**Comment by SugarRayLua** [comment]
Hi, @SchreiberChiang,
So it sounds like you got Love 2D working on your iOS device and can see the Love2D documents folder now where to put your .love file, but...

When you try and use Love 2D to run your love file it would load and gives you the error you just showed me?

If so, there can be a lot of different reasons for that to include problems with how your software zipped up your main.zip folder. For instance, the default zip software that I use when scripting on my iPad is "Textastic"; it is great, but I found its zip function for some reason didn't zip up the folder in a way that Love2D could open on the iPad. Instead, I now zip up my main.lua (& other files) with the "iZip Pro" app on my iPad-- it seems to consistently zip the folder in a way that Love 2D can open.

If you've got the basic Love2D app working on iOS (and can open its "Documents" storage folder), might I suggest asking any new general Love2D questions re: iOS on the Love2D Discord channel? I'm on there (as "Myte") and iOS Love2D maintainers like @slime73 are on there among many others in the computer to try and answer your questions. :-)

**Comment by grahamboree** [comment]
To the original issue, I'm reasonably certain that a pico-8 style löve app that helps you avoid side-loading is in violation of [the App Store review guidelines §3.2.2(i)](https://developer.apple.com/app-store/review/guidelines/#unacceptable):

> (i) Creating an interface for displaying third-party apps, extensions, or plug-ins similar to the App Store or as a general-interest collection.

As helpful as an app like this might be, it doesn't seem like something that could pass app review for the iOS App Store.

**Comment by slime73** [comment]
That would probably stop it from being accepted yeah, although maybe there's some room for interpretation but it seems iffy. I'll close this issue because of that and the other reasons I said before (we don't have capacity regardless).

**Comment by SugarRayLua** [comment]
All of the above comments make sense. Hopefully in the future there will be expanded capacity to maintain (or Apple formally opens up sideloading). App Store seems to have accepted many apps similar to Love2D (e.g. Codea). I really enjoy using and developing with LOVE2D on iOS :-)

**Comment by slime73** [comment]
Codea is a code editor / IDE rather than just a launcher for existing apps created elsewhere.

**Comment by SugarRayLua** [comment]
Thank you, @slime73, for pointing out the distinction.

**Comment by SugarRayLua** [comment]
One related question:

Could the iOS love release be made into .ipa's? That would be useful to those who don't have paid developer accounts to sign Xcode .apps into .ipas. 

Thanks for the consideration.

**Comment by slime73** [comment]
A legit .ipa has to be code-signed and has a fixed list of registered devices it works on. https://help.apple.com/xcode/mac/current/#/dev7ccaf4d3c

**Comment by SugarRayLua** [comment]
Understood. I was also thinking about a TestFlight use case. I know iSH used that method for a while until it finally got accepted to the AppStore.

**Comment by SugarRayLua** [comment]
Oh, I read more of the fine print about TestFlight. Although it can be distributed to 10,000 people, it requires its own Apple Review.
