### ISSUE TITLE
Sensor API

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1872]
As per discussion in Discord, maybe we should use SDL sensor API then deprecate accelerometer-as-joystick option.

**Comment by slime73** [comment]
Maybe something like this? Naming could use some work but I think the love API can be simpler than SDL's:
```Lua
-- SensorType enum: "accelerometer", "gyroscope", etc

hassensor = love.sensor.hasSensor(sensortype)
enabled = love.sensor.isEnabled(sensortype) -- Not sure if I prefer is/setEnabled versus is/setActive, or something else.
success = love.sensor.setEnabled(sensortype, enable)
x, y, ... = love.sensor.getData(sensortype) -- acceleration vector for accelerometer, etc.
-- SDL has a getName API for sensors. Is that useful?

function love.sensorupdate(sensortype, x, y, ...) end -- Should this have a timestamp as well?

hassensor = Joystick:hasSensor(sensortype)
enabled = Joystick:isSensorEnabled(sensortype)
success = Joystick:setSensorEnabled(sensortype, enable)
x, y, ... = joystick:getSensorData(sensortype)

function love.joysticksensorupdate(joystick, sensortype, x, y, ...) end
```

**Comment by MikuAuahDark** [comment]
Here are my thoughts:
* Does that mean we'll cache `SDL_Sensor*` for the lifetime?
* `love.sensor.isEnabled` could be `love.sensor.isAvailable` since non-joystick sensor always active. It just needs to be opened. However if it's used for `love.sensorupdate` event, then `isEventEnabled` makes more sense.
* If SDL can provide timestamp for the sensor event, then having timestamp is a good idea.

**Comment by slime73** [comment]
> If SDL can provide timestamp for the sensor event, then having timestamp is a good idea.

After thinking about this more: SDL3 will be providing more accurate timestamps for a much wider range of events, so I think we won't want to do anything sensor-specific with timestamps and we'll think of how to expose them consistently for all relevant events when we move to SDL3 (it might be a while). That may end up needing a general change to the structure of events/callbacks in love, so it's out of the scope of a new sensor module IMO.

> Does that mean we'll cache SDL_Sensor* for the lifetime?

I was thinking `love.sensor.setEnabled(type, enable)` would call `SDL_SensorOpen` and `SDL_SensorClose` internally. SDL's device sensor API is designed a bit weirdly, I think it's overly complex for what it does. SDL's joystick sensor API more closely maps to the love joystick APIs I'm proposing.

**Comment by MikuAuahDark** [comment]
> I was thinking `love.sensor.setEnabled(type, enable)` would call `SDL_SensorOpen` and `SDL_SensorClose` internally.

Then having `love.sensor.isAvailable(type)` is a good idea to check if the user can really enable the sensor, or would `love.sensor.setEnabled` returns false in that case?

**Comment by slime73** [comment]
That's what my `love.sensor.hasSensor` proposal would do. But the naming is what I'm least sure about, so maybe `isAvailable` makes more sense, I dunno.

**Comment by MikuAuahDark** [comment]
> That's what my `love.sensor.hasSensor` proposal would do. But the naming is what I'm least sure about, so maybe `isAvailable` makes more sense, I dunno.

Oh sorry, missed this one. I personally go with `love.sensor.isAvailable` and `Joystick:hasSensor` to check sensor availability. The reason I'm go towards `love.sensor.isAvailable` is repeating the module name ("Sensor" as in `hasSensor` in `love.sensor`) doesn't sound that good, while it sounds good for the `Joystick` methods, but if you have different opinion please let me know.

**Comment by slime73** [comment]
I'd rather the naming be consistent between the two. Other APIs use the module name in module function names too.

**Comment by slime73** [comment]
This is done in commit 77f4334. Thanks!
