### ISSUE TITLE
The love command cannot discover main.lua files when using the Flatpak install of love2d

### ISSUE THREAD

**Issue by Lay3r8** [love2d/love#1876]
I was trying to execute the hello world yesterday and noticed that after having installed the [Flatpak version of love2d](https://flathub.org/apps/details/org.love2d.love2d), the love command was unable to locate a main.lua file containing [a simple hello world](https://love2d.org/wiki/Getting_Started) in the current directory regardless of using relative or absolute paths.

Here is a short extract of a terminal output which quickly summarize the issue:

```bash
~/test ❯ pwd   
/home/simon/test
~/test ❯ lse -a
Permissions Size User  Group Date Modified Name
.rwxrwxrwx    74 simon simon  8 Dec 15:52  main.lua
~/test ❯ flatpak run org.love2d.love2d /home/simon/test
Error: [love "boot.lua"]:323: Cannot load game at path '/home/simon/test'.
Make sure a folder exists at the specified path.
stack traceback:
    [love "boot.lua"]:345: in function <[love "boot.lua"]:341>
    [C]: in function 'error'
    [love "boot.lua"]:323: in function <[love "boot.lua"]:126>
    [C]: in function 'xpcall'
    [love "boot.lua"]:355: in function <[love "boot.lua"]:348>
    [C]: in function 'xpcall'
~/test ❯ cat main.lua                 
function love.draw()
    love.graphics.print("Hello World", 400, 300)
end
```

In the end I managed to resolve that issue by [building love2d from source](https://love2d.org/wiki/Building_L%C3%96VE) and using that to run the hello world.

Environment details:
- OS: Ubuntu 22.04.1 LTS
- Love2d version: 11.4

**Comment by MikuAuahDark** [comment]
Hello,

the FlatPak is not maintained by us. You could try giving it permission to access local files in FlatPak. You may raise the issue to the packager at here: https://github.com/flathub/org.love2d.love2d
