### ISSUE TITLE
Expose base instance offset for mesh draws

### ISSUE THREAD

**Issue by shakesoda** [love2d/love#1878]
I've been having performance problems in a prototype game here where I send all my object draws out as instanced draws, due to lacking base instance support I have to do an instance buffer update between every draw call, which is really slow with a fairly small number of draw calls (unusable, at least on GL, so I had to write a second render path and complicate things).

With base instance exposed I could do the instance buffer update once per frame instead and avoid the entire problem. I believe backend API-wise it's exposed on Metal, Vulkan and GL 3.3+ but not GLES.

**Comment by slime73** [comment]
For reference, in Metal it's supported by most but not all systems: https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

It's similar for Vulkan for indirect draws (which love doesn't support yet), but maybe it's supported everywhere there for direct draws: https://vulkan.gpuinfo.org/listfeaturescore10.php

> due to lacking base instance support I have to do an instance buffer update between every draw call

On other (non-love) projects I've worked on we store a custom base instance offset as a uniform. Would that work as a workaround in your situation?

(I'm not implying proper base instance support isn't something we should expose, but in my own experience with other projects I haven't actually needed it, so maybe there are ways to restructure things to have better performance without it.)

**Comment by shakesoda** [comment]
Metal support looks pretty good since family 2/A8 is ~8 years old, I didn't realize it wasn't universally supported there though.

Using a base instance as a uniform would work if I changed my instance buffer to either a storage buffer or data texture, but base instance would let this work when using instance buffers bound as attributes, which is fairly nice to have. Maybe another more portable solution would be to give attachAttribute an offset argument?

**Comment by slime73** [comment]
Oh right, I forgot about instanced attributes 😅 those other projects did use that in the past and switched to storage buffers at one point a while ago with no measurable performance loss - they have less hardware support than instanced attributes, but not less than native instance offsets.

> Maybe another more portable solution would be to give attachAttribute an offset argument?

I'm unsure whether that'd be more or less expensive than uniform updates, but it's probably a good idea in any case (even if native base instance support is implemented too.)

**Comment by shakesoda** [comment]
To be sure, I'm only using instanced attributes instead of a storage buffer because love 11 made me do either that or the hassle of a data texture. It might be more worthwhile to avoid the extra compatibility hazard and just expose attribute binding offsets as the more general alternative.

**Comment by slime73** [comment]
I added a vertex array index parameter to mesh:attachAttribute in [a37c2fb](https://github.com/love2d/love/commit/a37c2fb9a9b1ebab7e6e9f22d43ef8b9d317f776). I'll keep this issue open while I think about real base instance support.

**Comment by slime73** [comment]
It seems the base instance applied to instanced attributes has broader support than a built in base instance ID shader variable. (On various graphics APIs, the base instance isn't automatically applied to gl_InstanceID so it needs a separate variable - which isn't always provided, e.g. OpenGL needs https://registry.khronos.org/OpenGL/extensions/ARB/ARB_shader_draw_parameters.txt or GLSL 4.60.)

love could provide a uniform with that value itself since it already updates some uniforms every draw, but I think I'll defer doing that until I have a use case where user-applied uniforms isn't sufficient.
