### ISSUE TITLE
Expose indirect draw

### ISSUE THREAD

**Issue by shakesoda** [love2d/love#1879]
I believe simple (non-multidraw, base instance of 0) indirect draw is supported universally on compute hardware/APIs (although I'm a bit unsure about Metal family 2/A8), and it's really useful for GPU-driven particles, culling and so on.

**Comment by slime73** [comment]
I've added indirect draw and dispatch functionality in [2178b63](https://github.com/love2d/love/commit/2178b634c80f8184c6ce6888eb0cd878b185a392).
