### ISSUE TITLE
Appdata symlink bug.

### ISSUE THREAD

**Issue by Erokaution** [love2d/love#1882]
I'm under a Windows 10 environment.
I have my %appdata%\Roaming folder as a symlink to a different drive.
Here's a image showing a commandline print of 'dir /a', which shows the Roaming folder being a Symlink.
![image](https://user-images.githubusercontent.com/24382126/209040529-55d3dcf3-b6e0-495a-9550-1412c1f9a4d2.png)

With this said, love.filesystem.getAppdataDirectory() locates to "C:/Users/Athetia/AppData/Roaming".
Moreover, love.filesystem.isSymlink(love.filesystem.getAppdataDirectory()) returns false.
It appears that love2d is not seeing the Roaming folder as being a symlink.
Attempting to do any file operations on my main Windows user account fails. I am assuming it's because love2d is attempting to load from a appdata folder that doesn't exist at the specific location it's expecting.,

**Comment by MikuAuahDark** [comment]
Does `love.filesystem.write` works? If so then there's nothing to worry about. `love.filesystem.isSymlink` is relative to the save directory **and** game directory.

**Comment by Erokaution** [comment]
> Does `love.filesystem.write` works? If so then there's nothing to worry about. `love.filesystem.isSymlink` is relative to the save directory **and** game directory.

![image](https://user-images.githubusercontent.com/24382126/209042522-3412d34e-5700-4f65-98ab-e017371b42c1.png)
outputs..

![image](https://user-images.githubusercontent.com/24382126/209042579-55664aec-0ff2-48e7-92a1-c28c1a020600.png)
Do note I'm not actually working on any love2d project. I've never touched love2d before now, and I'm only testing this because a game wasn't working and I was trying to find out why, and this appears to be a engine issue and not a individual game issue from what I can see (which i obviously could be wrong).

With this said, if there's anything I can do to give a clearer idea on what's going on, let me know.

**Comment by MikuAuahDark** [comment]
I assume your `t.identity` is set correctly, so this appears to be PhysFS bug (library that `love.filesystem` uses under the hood).

**Comment by zorggn** [comment]
With issue #1880, the reporter deduced that löve versions prior to the as of now unreleased 12.0 has a PhysFS bug that caused their symlink related issue; not sure if this is the same problem or not though.
