### ISSUE TITLE
love apk + .love file

### ISSUE THREAD

**Issue by Sylfir** [love2d/love#1890]
I would like to ask this. Can i somehow combine the **love.apk file** with the **game.love file** by appending it at the end. And i quess maybe add something to the manifest.xml file to be able then to instal this apk as a game on android through the app store?

**Comment by MikuAuahDark** [comment]
No. It's not possible for 2 reasons:
1. APKs are zip archive, so appending it means it will see the game.love file instead of the actual APK.
2. APK must be signed, and appending or prepending data to it invalidates the signature.
