### ISSUE TITLE
Provide PDB with Source Indexing

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#1891]
Providing PDB in Windows means users with Debugging Tools for Windows can debug problems with LOVE in case of crashes. Having source indexing means that user can pull the source code of LOVE used for compilation of particular (exact) releases.

The PDB can either by hosted at https://love2d.org/pdb (need website access) or distributed as separate archive. However for now I think providing PDB as separate archive is the only way.

**Comment by slime73** [comment]
[7e661d2](https://github.com/love2d/love/commit/7e661d2fb159946ecbd8e5e67f5f3052842092c8) implements this.
