### ISSUE TITLE
Crashes when Source:seek offset more than the track length

### ISSUE THREAD

**Issue by modcos** [love2d/love#1898]
Appears only on 12.0. Source must be in mp3 format to reproduce this bug.

**Comment by MikuAuahDark** [comment]
I'm unable to reproduce this with this code.

```lua
function love.load()
	mymusic = love.audio.newSource("test.mp3", "stream", "file")
	mymusic:play()
	print(mymusic:getDuration())
end

function love.keyreleased(k)
	if k == "escape" then
		love.event.quit()
	elseif k == "space" then
		mymusic:seek(1000, "seconds")
		mymusic:play()
	end
end
```

`test.mp3` is encoded using libmp3lame in FFmpeg. Could you send minimal reproducible example with the MP3 file?

**Comment by MikuAuahDark** [comment]
Looks like it's fixed in later version of dr_mp3 and updating it fixes the issue.
