### ISSUE TITLE
Cursors not supported in iOS version of Love2D?

### ISSUE THREAD

**Issue by SugarRayLua** [love2d/love#1900]
Hello. I'm trying to run a .love file on the iOS 11.3 version of Love2D, and it gives me an error at when the project tries to create a create a cursor via love.mouse.newCursor() command:

"Cannot create cursor: cursors are not currently supported"

Is not being able to create cursors a limitation of love 11.3 on iOS? If so, does version 11.4 or will any newer versions support cursor functionality? 

Thanks.

**Comment by MikuAuahDark** [comment]
I don't think cursor is supported on iOS in general. You can use [`love.mouse.isCursorSupported()`](https://love2d.org/wiki/love.mouse.isCursorSupported) to check.

**Comment by SugarRayLua** [comment]
Thanks, @MikuAuahDark, you are correct. That check returns false on my iOS device. Perhaps could turn into a feature request for a future version? iPads specifically definitely have a cursor so would think that it might be programmable by love?

**Comment by slime73** [comment]
This would rely on SDL having support for that, and on iOS having APIs SDL could use to make a custom cursor image.

I briefly poked around the iOS cursor/pointer APIs just now, and I can see some for setting a few preset cursors (like a vertical beam). But I don't see any for creating one with a custom image. I'll keep looking but if Apple doesn't support it, then neither SDL nor love can.

**Comment by SugarRayLua** [comment]
Thank you very much for looking into this, @slime73, and for the follow-up.

**Comment by slime73** [comment]
I'll close this for now, but I'll keep an eye out in case Apple adds new cursor APIs in future iOS versions.
