### ISSUE TITLE
fullscreen config in `conf.lua` prevents setting initial orientation on iOS 16

### ISSUE THREAD

**Issue by ParticleG** [love2d/love#1903]
It seems this issue [love-android #196](https://github.com/love2d/love-android/issues/196) happens on iOS16 again. If you use the following configs:
```lua
t.window.width,t.window.height=1280,720
t.window.fullscreen=true
t.window.resizeable=false
```
Then launch the game with your phone standing portrait, the game would be in portrait mode even the `window.width` is greater than `window.height`.

This didn't happen on iOS 15. See discussions in our game's issue: [Techmino #847](https://github.com/26F-Studio/Techmino/issues/847)

Example project code on [Techmino/ci-ios-test](https://github.com/26F-Studio/Techmino/tree/ci-ios-test), result on 15 and 16:

![image](https://user-images.githubusercontent.com/38580644/220306287-9e4cc38c-6144-41f6-af27-5e0df1011939.png)

**Comment by MikuAuahDark** [comment]
Here's the commit for that Android fix: 9c4db00e9490742317d4a493f5c11d7f7e200124

If you could change the relevant codepath to also run on iOS, by changing the `#if` by adding `LOVE_IOS` define check too, does it solves the issue?

**Comment by ParticleG** [comment]
Would test with git patch and [love-actions-ios](https://github.com/love-actions/love-actions-ios) CI, because I have no mac dev env for now

**Comment by slime73** [comment]
I doubt that Android-specific change would affect much at all on iOS. The two platforms have radically different codepaths in SDL (which is meant to handle this stuff) - historically SDL's Android backend has sort of been its own thing, whereas the iOS backend behaves similarly to other platforms.

As a workaround, setting the available orientations via the Xcode project will probably work in the meantime. See `platform/xcode/love-ios.plist` if you want to edit the file that has that information (`UISupportedInterfaceOrientations` etc).

**Comment by ParticleG** [comment]
> I doubt that Android-specific change would affect much at all on iOS. The two platforms have radically different codepaths in SDL (which is meant to handle this stuff) - historically SDL's Android backend has sort of been its own thing, whereas the iOS backend behaves similarly to other platforms.
> 
> As a workaround, setting the available orientations via the Xcode project will probably work in the meantime. See `platform/xcode/love-ios.plist` if you want to edit the file that has that information (`UISupportedInterfaceOrientations` etc).

I've tried, but our game need to change orientation with in game settings

**Comment by ParticleG** [comment]
Actually it behaves weird, as if the game read the wrong width and length data

**Comment by ParticleG** [comment]
Launch portrait:
![F9F4FC9D-CC08-414F-A053-8FEC36EE1C1C](https://user-images.githubusercontent.com/38580644/220391562-125d1def-68ca-4d54-acea-bca1e6f6f333.png)

Launch landscape:
![3E94B503-36EC-4211-A56E-32F24C509C74](https://user-images.githubusercontent.com/38580644/220391743-4e525f6b-6f93-43dc-b561-58f91c8d2201.png)

Sorry but I can’t provide any debugging information, since my Mac is too old and keeps running out of memory.

**Comment by slime73** [comment]
This isn't something love's own source code can likely fix either way. There was a workaround recently for something similar inside SDL's source code (https://github.com/libsdl-org/SDL/issues/6289) but I don't think the workaround will necessarily fix this issue - you could try using the latest SDL2 release even so.

**Comment by bytemain** [comment]
is there any build script let me can build `SDL2.xcframework` library??
https://github.com/love2d/love-apple-dependencies/tree/main/iOS/libraries/SDL2.xcframework

I'm new to iOS develop, I think may it has a script like: https://github.com/love2d/love/blob/9963d1247c05b303caf7c61e8016315a1cd33465/platform/xcode/ios/luajit-iOS.sh#L10

**Comment by slime73** [comment]
> is there any build script let me can build SDL2.xcframework library?

The Xcode project in the latest SDL2 versions has an xcframework iOS target I believe. I haven't tested it myself yet but hopefully it'll work without needing to change anything. Otherwise you can build a static library and use the `xcodebuild -create-xcframework` command to generate one from one or more static libraries.

**Comment by bytemain** [comment]
the xcframework target in SDL2 framework's structure like this:
<img width="350" alt="CleanShot 2023-02-22 at 21 34 06@2x" src="https://user-images.githubusercontent.com/13938334/220634913-c3326837-f0e4-4fb8-8c19-9b25778a2633.png">

**Comment by bytemain** [comment]
Thanks for you second advice, I will try it later.

**Comment by bytemain** [comment]
looks like SDL2 2.26.3(latest) still have this problem.

---

you can use follow steps to create a new `SDL2.xcframework`

Firstly, build static library for iOS:

<img width="533" alt="CleanShot 2023-03-03 at 19 53 33@2x" src="https://user-images.githubusercontent.com/13938334/222713938-92ac9b47-a8d7-4e75-ae24-d09d45229a10.png">


then open the build folder and copy that path:
<img width="297" alt="CleanShot 2023-03-03 at 19 54 08@2x" src="https://user-images.githubusercontent.com/13938334/222714034-925bce6b-6519-4249-b02c-ba5565fe521c.png">


```sh
xcodebuild -create-xcframework -library {BUILD_PATH}/Products/Release-iphoneos/libSDL2.a -headers {SOURCE_DIR}/include -library  {BUILD_PATH}/Products/Release-iphonesimulator/libSDL2.a -headers {SOURCE_DIR}/include -output SDL2.xcframework
```

replace the `{SOURCE_DIR}` to source code path, replace the `{BUILD_PATH}` to the xcode build folder.

**Comment by slime73** [comment]
I've done some debugging and I have a potential fix for the issue in SDL, but I need to test it more.

However, setting fullscreen without setting *exclusive* fullscreen will use fullscreen-desktop mode. Fullscreen-desktop always uses the native screen resolution instead of changing it based on the requested dimensions. On iOS that means even if you request landscape or whatever via setting width and height it won't use it, and will likely default to portrait mode.

The bug still exists when you request exclusive fullscreen with landscape though, and that's what I'm fixing.

**Comment by slime73** [comment]
This is fixed in the version of SDL used with love 12.
