### ISSUE TITLE
love.dropbegan & love.dropcompleted not being called on windows 64

### ISSUE THREAD

**Issue by EngineerSmith** [love2d/love#1908]
Love 12; latest commit 4e86d45ffd377613d05c7299aae285e59cf9ba8c 

I wrote the following test script to try and use the new `love.dropbegan` and `love.dropcompleted` events. I assumed through reading the source and sdl's wiki that these are triggered when a file is held over a window; but they don't seem to. 

```lua
local files = { }

love.filedropped = function(file) -- works as it had in 11.4
  table.insert(files, { x = love.mouse.getX(), y = love.mouse.getY(), name = file:getFilename() })
  print("filedropped") -- prints
end
-- these do not print
love.dropbegan = function() print("dropbegan") end
love.dropcompleted = function() print("dropcompleted") end

local lg = love.graphics
love.draw = function()
  for _, file in ipairs(files) do
    lg.setColor(1,0,0,1)
    lg.circle("fill", file.x, file.y, 2)
    lg.setColor(1,1,1,1)
    lg.print(file.name, file.x + 4, file.y - 4)
  end
end
```

I also tried adding a print within `love.run` event polling and these events are never triggered on my system.  Also, I did confirm I was running love12 with `lovec --version`, so not sure what I'm doing wrong or if my understanding of these events is wrong.

**Comment by slime73** [comment]
It's working fine for me (on Windows 10, using `lovec.exe` to make sure the print statements are run.)

That being said, dropbegan and dropcompleted events happen when files are dropped, rather than when the mouse hovers over the window with the potential to drop files. The events surround a group of file drop events if the user has selected multiple files. But personally I'm not sure that's very useful, and the events are easily confused with something that would happen when the mouse hovers over the window with to-be-dropped files. So I wonder if those events should just be removed (or renamed).

**Comment by EngineerSmith** [comment]
Ah I see; it's not the behaviour I want. I'm also on windows 10 too, using this code below I still don't see the events firing (no window updates pending either)
```lua
function love.run()
  if love.load then love.load(love.arg.parseGameArguments(arg), arg) end

  if love.timer then love.timer.step() end

  local dt = 0

  return function()
    if love.event then
      love.event.pump()
      for name, a,b,c,d,e,f in love.event.poll() do
        if not string.find(name, "mouse") then -- remove mouse events to avoid lots of prints
          print("Event: "..tostring(name))
        end
        if name == "quit" then
          if not love.quit or not love.quit() then
            return a or 0
          end
        end
        love.handlers[name](a,b,c,d,e,f)
      end
    end

    if love.timer then dt = love.timer.step() end

    if love.update then love.update(dt) end

    if love.graphics and love.graphics.isActive() then
      love.graphics.origin()
      love.graphics.clear(love.graphics.getBackgroundColor())

      if love.draw then love.draw() end

      love.graphics.present()
    end
    
    if love.timer then love.timer.sleep(0.001) end
  end
end
```
I get the output of
```
Event: joystickadded
Event: visible
Event: focus
Event: textedited
Event: focus
Event: textedited
Event: filedropped -- single file
Event: filedropped -- this and below is multiple selected dropped
Event: filedropped
Event: filedropped
```
I assume there is no way to tell if the mouse is holding a file above the window using sdl then? I would love to have sections of my window for different files and text to popup to show that files can be accepted e.g. like discord does it when you hold a file over the window. I do agree that the names are a bit confusing; so I do vote for renaming if they're to be kept. Something like "multidropbegan", "multidropcompleted"

**Comment by slime73** [comment]
> I assume there is no way to tell if the mouse is holding a file above the window using sdl then? 

That's correct, SDL doesn't have that functionality yet.

**Comment by EngineerSmith** [comment]
Right, there's an issue for it https://github.com/libsdl-org/SDL/issues/5292 hopefully it makes it in to SDL sooner, rather than later. 
I'll leave this open since the callbacks don't work for on my system

**Comment by slime73** [comment]
I've removed love.dropbegan/dropcompleted in [c4aaab6](https://github.com/love2d/love/commit/c4aaab6bf0cb75f5da1825bac3847690e839b89d).
