### ISSUE TITLE
Feature - Foreground service

### ISSUE THREAD

**Issue by blogdron** [love2d/love#1909]
If this is possible, then it would be great in version 12 to add the ability to run a small piece of code in the Foreground Service on Android. Since the work in the Foreground Service should be independent and non-blocking, it is probably possible to expand love.thread specifying that the thread should be executed as a Foreground Service the pool of these threads will be executed in one Foreground Service. Like this

```lua
thread = love.thread.newThread( threadCode,foreground={foreground_table} )
```

* foreground_table is table contains 
  * icon
  * title
  * message
On PC and other just ignore foreground  table; 
On Android (and maybe other?) ` if foreground ~= nil` run thread in  `Foreground Service`  (push lua raw text to foreground Java code and call SDLthread from JNI for run lua VM :nesting_dolls:   or something like that :D )  

* For communication can use default `Channels` mechanism; 
* Android permissions may be worth limiting like , sound/microphone/network for only play music, download game additional resources and talks with teamates in game session

* https://developer.android.com/guide/components/foreground-services

Thus, the same code will work everywhere, but on android it will be possible to play background music, download content from the network or record a microphone when the application is minimized. 

Thank you for reading, I hope my idea is not stupid.
I wanted to do it myself, but I don't have enough experience :(
P.S. I'm sorry for my English, I used a translator ( (^.^) )

**Comment by MikuAuahDark** [comment]
Aren't `love.thread` in Android non-blocking by default? Of course, if the app is terminated in background by the system, the corresponding thread also gets terminated.

**Comment by blogdron** [comment]
> Aren't `love.thread` in Android non-blocking by default? Of course, if the app is terminated in background by the system, the corresponding thread also gets terminated.


Ohhhh Im stuuuuuuuuuuuuuuuuuuupid

for foreground just need

```lua
function love.conf(c)
    c.background=true
end
```

I just saw this in the documentation. In my modest application, I receive sound over the network from my PC (since my sound card is broken) and when I minimized the application on my phone, the sound was interrupted, I thought I needed to do something special to work in minimized mode, but it turns out that it wasn't!!

I'm really sorry, I'm really a fool :D Sorry. 
Probably this issue should be closed. Thank you so much for the wonderful love2d if it wasn't for him, I would be sitting without sound right now =)))))))

**Comment by blogdron** [comment]
I will close the issue, because to work in the background, you just need to set a configuration parameter and do not need to do anything else. I apologize again, damn, I'm so glad that everything is so simple, and before that I tried to make changes to the source code for two days.... that's what I'm stupid! :D

**Comment by MikuAuahDark** [comment]
LOVE automatically pauses all audio sources when the app is minimized to background. It's by design. You need to handle that case in your app.

**Comment by blogdron** [comment]
> LOVE automatically pauses all audio sources when the app is minimized to background. It's by design. You need to handle that case in your app.

Work fine for me in the expanded and minimized android window (android 6)
love.conf
```lua
function love.conf(c)
    c.audio.mixwithsystem = true
    c.background=true
end
```

main.love
```lua
local thread_code = 
[[
    require('love.audio');
    require('love.sound');

    local tcp = nil;
    local samplerate   =         44100 -- Hz
    local bits         =             16 -- 8 bits results in very low quality sound
    local channels     =             2 -- löve only supports mono or stereo
    local buffercount  =             2 -- don't need too many buffers
    local qsource      = love.audio.newQueueableSource(samplerate, bits, channels, buffercount)
    local samplepoints = 4   -- how many numbers does one buffer hold

    love.audio.setVolume(1)
    local socket = require("socket")
    tcp = socket.connect("192.168.0.100",8888);
    while true do
        local data = tcp:receive(22000);
        if data then
            qsource:queue( love.data.newByteData(data):getPointer(), 0, #data, samplerate, bits, channels)
            qsource:play()
        end
    end
]]

function love.load()
    thread = love.thread.newThread( thread_code )
    thread:start( )
end

function love.update()

end

function love.keypressed(key)
    if key == 'q' then
        love.event.quit()
    end
end

```

on my PC (Linux  + Pipewire + Pulseaudio modules) send PCM sound to network
```lua
#! /bin/env lua

------------------------------------------
-----Simple sound server over Network-----
------------------------------------------

command_start = "pactl load-module"
command_stop  = "pactl unload-module"
modules  = "module-simple-protocol-tcp"
rate    = "rate=44100"
format  = "format=s16le"
channel = "channels=2"
source  = "source=alsa_output.pci-0000_00_14.2.iec958-stereo.monitor"
record  = "record=true"
port    = "port=8888"

if arg[1] == "start" then
   os.execute(command_start.." "..modules.." "..rate.." "..format.." "..channel.." "..source.." "..record.." "..port);
elseif arg[1] == "stop" then
   os.execute(command_stop.." "..modules);
elseif arg[1] == "status"  then
   os.execute("pactl list | grep tcp");
end
```

Now if I minimize the window, the sound continues to go, this is what I need. Everything works fine. I brought this code so that the issue was not useless. Maybe it will come in handy if someone breaks the sound on the PC and will have to use the phone as a sound card by sticking headphones in =)

**Comment by MikuAuahDark** [comment]
That code only works in 11.4 and earlier. It's been fixed in the main branch. The whole audio thread will be suspended instead of pausing all sources.

**Comment by blogdron** [comment]
Ohhh. And how to turn the sound back on correctly if all sources are muted in minimized mode?

**Comment by MikuAuahDark** [comment]
You have to put the app back to foreground. The relevant change is 3c2b1b888e594e42612c9d58a216ffda8ef4bd3b.

**Comment by blogdron** [comment]
> You have to put the app back to foreground. The relevant change is [3c2b1b8](https://github.com/love2d/love/commit/3c2b1b888e594e42612c9d58a216ffda8ef4bd3b).

Thanks, I'll try to figure it out.

**Comment by blogdron** [comment]
For working sound in minimised mode need this
```lua
function love.focus(f)
  if f == false then
    love.event.push("focus",true)
  end
end
```
Looks like a crutch :) But maybe someone will need it, like me
