### ISSUE TITLE
add mousewheel event preciseX and preciseY values

### ISSUE THREAD

**Issue by akciom** [love2d/love#1910]
When trying to scroll using a touch pad, I'm getting multiple mousewheel move events but they're too small to register as anything, providing 0 for both x and y.

SDL version 2.0.18 added the values preciseX and preciseY, however love doesn't currently expose them.

https://wiki.libsdl.org/SDL2/SDL_MouseWheelEvent

**Comment by slime73** [comment]
SDL should be providing non-zero whole numbers for the non-precise x and y wheel values in that situation. If it doesn't, it's probably a bug in an SDL backend for your platform.

**Comment by akciom** [comment]
I'm running Love 11.4 x64 on Windows.

I do get the occasional non-zero whole number but only if I scroll quickly and even then it's maybe one out of every 10 events. Scrolling slowly simply emits 0, 0.

I was using 11.3 before I noticed this issue which was released long before the update to the wheelmoved event in 2.0.18.

Is it possible SDL made changes to how x and y are reported since they added preciseX and preciseY?

I'll check my code against previous love versions and run some tests against SDL and the Win SDL and post my findings.

**Comment by akciom** [comment]
I'm running Love 11.4 x64 on Windows.

I do get the occasional non-zero whole number but only if I scroll quickly and even then it's maybe one out of every 10 events. Scrolling slowly simply emits 0, 0.

Edit: I checked and eventually it does emit a value as it always did.

Either way, it would be nice to be able to have access to the preciseX and preciseY values for incremental scrolling.

**Comment by slime73** [comment]
[059d60b](https://github.com/love2d/love/commit/059d60b404a0e7925c034fb147baca80504de183) adds preciseX, preciseY, and direction enum parameters to love.wheelmoved.
