### ISSUE TITLE
When a file or directory is dropped into the window; the window remains out of focus

### ISSUE THREAD

**Issue by EngineerSmith** [love2d/love#1911]
Love 11.4 [Windows x64] issue/feature request

When a directory or file is dropped into the window - the window remains out of focus. Causing the user to click the window after they have dropped a directory or file to make the program gain mouse focus - and then continuing. I've got around this by calling `SDL_raiseWindow` whenever the events are triggered - might be something useful to slip into love12. This issue is more frustration of having to click focus, and then continue - it interrupts the flow as I expect the window to gain focus when a directory or file is dropped.
https://github.com/EngineerSmith/isdropping/commit/9b94ed37b1721ce5a5f7778593fcc6ae31f2de6a

```lua
love.filedropped = function(file)
  print(file:getFilename())
end

love.directorydropped = function(directory)
  print(directory)
end

love.focus = function(focus)
  if focus then
    print("Window is focused")
  else
    print("Window is not focused.")
  end
end
```
The code above will produce something like the following
```
Window is focused
Window is not focused.
C:\git\love-test-directory
C:\git\love-test-directory\icon.png
```
Expected:
```
Window is focused
Window is not focused.
C:\git\love-test-directory
Window is focused
Window is not focused.
C:\git\love-test-directory\icon.png
Window is focused
```

**Comment by slime73** [comment]
I don't know if I'm confident enough about OS behaviour on different platforms to say whether this should be done by love itself or not.

If love doesn't do it itself, and operating systems don't do it automatically, then people can choose whether to do it or not, right?

**Comment by slime73** [comment]
On macOS, it doesn't appear to be standard behaviour to automatically focus the window when a file is dropped. On Windows it seems to depend on the app - for example Visual Studio doesn't grab focus when that happens, but Chrome does.

I think even for situations where grabbing focus is desired, it shouldn't be done if the app doesn't actually want to handle the particular file, right? In that case maybe exposing `SDL_RaiseWindow` is the best way to address this.

**Comment by EngineerSmith** [comment]
I think that would be best; since with love12 it'll be harder to access the `SDL_Window *` like we can in 11.4 with `SDL_GL_GetCurrentWindow` so I won't be able to hack it in myself

**Comment by slime73** [comment]
I added the function (`love.window.focus`) in [2c3ea60](https://github.com/love2d/love/commit/2c3ea60c7960acfc2095c9f0e067d02d6490ba0d). I'm not totally sold on the name so I'm open to changing it, but it at least feels consistent with `love.window.hasFocus` (and `love.window.minimize` versus `love.window.isMinimized` etc.)
