### ISSUE TITLE
love.graphics.setScissors() pixel bug

### ISSUE THREAD

**Issue by Fnoop1** [love2d/love#1915]
![Knipsel](https://user-images.githubusercontent.com/45689068/229194005-834d176e-0c12-4887-956e-c464fb12221a.PNG)
![Knipsel2](https://user-images.githubusercontent.com/45689068/229194007-1514b04b-f78b-49c2-8376-1843dc6f6847.PNG)
[Data.zip](https://github.com/love2d/love/files/11124627/Data.zip)

As you are able to see in the first image: when setting scissors cutoff point has the exact same coordinates as the rectange is wide and high, while drawing multiple rectanges you can see it doesn't cut off one of the rectangles properly since there is a slight gap between the 2 rectangles (bottom of the blue and pink one). These rectangles are objects, and drawn at 99% of the screen height (look in the zip in GUI/View/Test [Obj] to see where I made the 3 rectangle objects), and in GUI/Containers [Obj] for the logic behind the containers. This is most certainly a bug, since without the scissors funtion encapsulating the draw rectangle in the Containers obj file this problem does not occur (rounding the pixels down with math.floor doesn't help either).

I am on the most recent Windows 10 version with an Nvidea graphics card with up to date drivers, and running Love 11.4

**Comment by slime73** [comment]
This is what the linked project looks like on my computer (Windows 10, with an nvidia 1070 GPU) - no pink/purple pixels at the bottom: 
![image](https://user-images.githubusercontent.com/2662/229302500-0489f454-59eb-474f-b8ae-d338423e2d08.png)

**Comment by slime73** [comment]
Also keep in mind scissors only operate on whole pixels, they aren't the same as rasterizing geometry to the framebuffer at subpixel precision.

**Comment by slime73** [comment]
I've updated the setScissor documentation a little bit to say something similar - fractional pixel values aren't something you should use with it.

**Comment by Fnoop1** [comment]
Thanks for the quick response, and the mention of stencil. With the correct use of math.floor or ceil this doesn't happen!
