### ISSUE TITLE
Cannot push love object to Lua: unexpected alignment 

### ISSUE THREAD

**Issue by Luckyoriginal** [love2d/love#1916]
I am on Debian 11 i386, the issue:

Error

[love "wrap_Math.lua"]:35: Cannot push love object to Lua: unexpected alignment (pointer is 0x00984ad8 but alignment should be 16)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function '_getRandomGenerator'
[love "wrap_Math.lua"]:35: in main chunk
[C]: at 0xb7aa6453
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by MikuAuahDark** [comment]
Are you compiling LOVE yourself or using what Debian provides?

If you compile it yourself, then `minalign` in here returns 16, but it should be 8. This indicates compiler or ABI issue.
https://github.com/love2d/love/blob/9963d1247c05b303caf7c61e8016315a1cd33465/src/common/runtime.cpp#L131-L153

If you use what Debian provides, please fill bug tracker there.

**Comment by Luckyoriginal** [comment]
I installed Love from Debian package, i got this error. So i tried to compile it from source but i got the same issue

**Comment by MikuAuahDark** [comment]
Then please report to Debian about the compiler issue. In your case, `LOVE_ALIGNOF(std::max_align_t)` must be 8.

**Comment by Luckyoriginal** [comment]
Ok, thank you.

**Comment by MikuAuahDark** [comment]
Hmm, on second thought, apparently getting alignment right pre-C++17 is hard. So I'll leave it open for possible workarounds.

**Comment by MikuAuahDark** [comment]
Hello, can you try compiling my test changes from source https://github.com/MikuAuahDark/love2d/tree/workaround_32bitalign and see if it runs on you?

**Comment by Luckyoriginal** [comment]
> Hello, can you try compiling my test changes from source https://github.com/MikuAuahDark/love2d/tree/workaround_32bitalign and see if it runs on you?



> Hello, can you try compiling my test changes from source https://github.com/MikuAuahDark/love2d/tree/workaround_32bitalign and see if it runs on you?

I'll try it

**Comment by Luckyoriginal** [comment]
@MikuAuahDark it doesn't work

**Comment by MikuAuahDark** [comment]
Still same alignment issue? Hmm, try this AppImage instead. https://cdn.discordapp.com/attachments/329400828920070144/1101343428723363900/love-workaround_32bitalign.AppImage

**Comment by Luckyoriginal** [comment]
@MikuAuahDark the appimage work
