### ISSUE TITLE
Lua Error I can't find online

### ISSUE THREAD

**Issue by Ryanbar6** [love2d/love#1920]
Hey guys. This is probably something really basic and/or stupid, but I'm brand-new to the software, so I haven't figured out what to do about it yet. Whenever I drag main.lua over to love, I get the following message:

Error

[love "boot.lua"]:276: Syntax error: conf.lua:1: '<name>' expected near '.'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'error'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by steveRoll-git** [comment]
GitHub issues are for reporting issues with löve itself, not issues in your code. If you want help with your code, ask in the [https://discord.gg/rhUets9](Discord server) or the [https://love2d.org/forums/](forums).
