### ISSUE TITLE
Misspelling in modules/keyboard/Keyboard.cpp

### ISSUE THREAD

**Issue by VoncreDev** [love2d/love#1925]
The keycode for: Keyboard::KEY_THOUSANDSSEPARATOR is misspelt.
![image](https://user-images.githubusercontent.com/89253016/235462772-3b7a6dee-7fa5-45f8-9f95-759a7d1c3050.png)
It should be: thousandsseparator

**Comment by zorggn** [comment]
actually, it should be `thousandsseparator`; you forgot the t.

**Comment by VoncreDev** [comment]
> actually, it should be `thousandsseparator`; you forgot the t.

my bad, fixed now

**Comment by slime73** [comment]
This is fixed now in [545db4b](https://github.com/love2d/love/commit/545db4b0b3e75cd5c88a312ba4e50bfe97a57b99) - it's part of 12.0 rather than 11.5 since it's technically a breaking change to something that's already documented with the old name.
