### ISSUE TITLE
Code signing a fused executable is unsupported

### ISSUE THREAD

**Issue by KayleMaster** [love2d/love#1929]
After code signing a working fused executable under windows, starting the exe, while now validated, returns a nogame screen.   
Apparently this is because the zip file footer is modified after signing, leading to physfs not recognizing the .love/zip file inside the fused executable.    
I hope I don't need to sell the idea of code signing and why it can be useful.

**Comment by slime73** [comment]
On other platforms, signing can apply to a whole app bundle, so a separate .love can be included in the signature. It might be very difficult to accommodate fused code-signed games on Windows if that's not possible there.

**Comment by pfirsich** [comment]
From my observation the signature is simply appended to the fused file and the zip data stays intact, so we can simply skip it. Just to close the loop and add some links I am writing this comment and mention the corresponding PR #1930
