### ISSUE TITLE
"displayindex" in love12 has no effect

### ISSUE THREAD

**Issue by Froyok** [love2d/love#1934]
The setting "display" has been renamed to "displayindex" in Love version 12 , according to the release notes:
> Renamed 'display' field to 'displayindex' in love.window.setMode/updateMode/getMode and love.conf.

However when using it in the conf file, it has no effect in my project.
If I use "display" instead of "displayindex" I get the deprecated message, but the window is located on the expected screen.

This looks like a bug to me, unless I missed something ? I looked around in the initial change of the commit but haven't seen anything special: https://github.com/love2d/love/commit/34f036f2e1032c77d023a51036910b4138724872

I'm using the following binaries: https://github.com/love2d/love/actions/runs/4929016420

My specs:

- Linux Manjaro (5.15.112-1)
- KDE Plasma (5.27.4)
- Mesa 23.0.3
- AMD Radeon RX 5600 XT
- Ryzen 9 3900X

My conf file:
```lua
function love.conf( Settings )
	local FFI = require("ffi")

	if FFI.os == "Linux" then
		FFI.cdef[[
			int setenv(const char*, const char*, int);
		]]

		FFI.C.setenv( "SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR", "0", 1 )
		-- FFI.C.setenv( "MESA_GLX_DEPTH_BITS", "32", 1 )
	end

	local VersionMajor = love.getVersion()

	Settings.highdpi = true
	Settings.window.usedpiscale  = false

	Settings.console = true
	Settings.gammacorrect = true

	Settings.window.title = ""
	Settings.window.icon = "icon.png"

	Settings.window.width = 1280
	Settings.window.height = 720
	Settings.window.minwidth = 256
	Settings.window.minheight = 256
	Settings.window.resizable = true

	Settings.window.borderless = false
	Settings.window.fullscreen = false
	Settings.window.fullscreentype = "desktop"

	Settings.window.vsync = 1
	Settings.window.msaa = 0

	Settings.window.displayindex = 3 --Doesn't work unless I use "display"

	Settings.window.depth = 24 -- 16/24/32
	Settings.window.stencil = nil
	Settings.modules.touch = false
	Settings.modules.video = false
	Settings.modules.physics = false
end
```

**Comment by slime73** [comment]
This is fixed now in [48326a0](https://github.com/love2d/love/commit/48326a026d13e8a0b0ff292964ec59702d4263df). Thanks!
