### ISSUE TITLE
Second use of setGamepadMapping does not work

### ISSUE THREAD

**Issue by Sketchwhale** [love2d/love#1936]
I'm currently trying to map an "8BitDo Ultimate wireless for PC", since it isn't recognised as a controller. The `loadGamepadMappings` was giving me an invalid mappings error when I tried to use the `gamecontrollerdb.txt` file everyone seems to use.

Instead I tried to use the manual `setGamepadMapping` function. I'm experiencing that no matter what I set secondly, does not work, so whether I set the y button first, and the the left analog stick's x axis, or if I set the right analog stick's y axis first and then the a button, the second setting does not respond.

I'm running 11.4 on Apple Silicon, running Mac OS 11.6

**Comment by slime73** [comment]
I've fixed the `setGamepadMapping` issue in commit [df7a559](https://github.com/love2d/love/commit/df7a55911df5e84bd6eb46cebd48220b7305c62a) for love 11.5. I couldn't reproduce a problem with `loadGamepadMappings` using the latest gamecontrollerdb.txt on my system, but if you still have the issue and can make a small test project which reproduces it, opening a new issue report about that would be appreciated.
