### ISSUE TITLE
RTL fonts are not supported when used as a fallback in LÖVE 12.0

### ISSUE THREAD

**Issue by 0azizi0** [love2d/love#1937]
In LÖVE 12.0 RTL fonts when set as a new font, it works well. But when used as a fallback with LTR fonts, not so well. The results are different depending if the RTL fonts are the primary font or the fallback font.

When RTL used as the primary font:

![as_main](https://github.com/love2d/love/assets/7659180/43f6982f-b35f-467c-9255-30264a242608)

When RTL used as the fallback font:

![as_fallback](https://github.com/love2d/love/assets/7659180/a0af663f-775b-43f2-bf52-5af276e2e4fb)

There is other issues with the integration of harfbuzz I pointed out in #1687, not sure if I should open new issue for them.

**Comment by slime73** [comment]
Thanks for the report and test code - this should be fixed now in [8efcf27](https://github.com/love2d/love/commit/8efcf27a6e4e4a2d237eccbf102bb8dc5200c15a).
