### ISSUE TITLE
Tracker music files sometimes load incorrectly

### ISSUE THREAD

**Issue by spindlebink** [love2d/love#1939]
LÖVE 12 (built from commit 8efcf27a, running on Manjaro) seems to occasionally fail to detect tracker modules as such and plays them as a glitched buzz. LÖVE 11.5 plays them correctly.

I pared the original affected song to the snippet included in the ZIP here. You can run the ZIP in either version of LÖVE.

[xm_bug.zip](https://github.com/love2d/love/files/11655297/xm_bug.zip)

**Comment by MikuAuahDark** [comment]
d28b30736fdcd3351d782e5432fd4fa65ab9e15c
