### ISSUE TITLE
a new physics engine under dev box2d

### ISSUE THREAD

**Issue by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [love2d/love#1940]
just wanted to point out that the developer of box2d is making a new physics engine called box2c, it is still wip.

https://github.com/erincatto/box2c

**Comment by slime73** [comment]
Yeah, I've been keeping an eye on it a little bit. There are a couple interesting new things in it, we'll evaluate moving to it once it's ready to be used in shipping games.

That being said, the discord server or forums are a more appropriate place for discussion topics, the issue tracker is just meant for bug reports and feature requests.
