### ISSUE TITLE
love.mouse.setRelativeMode ignores right click after using it

### ISSUE THREAD

**Issue by Sin-tel** [love2d/love#1948]
The following things have to happen for this bug to occur:
* Left mouse butten enables relative mode.
* left mouse button release disables relative mode again.
* if the mouse has *not moved* after this, and the user right clicks, this is not registered (neither press nor release).

MWE:
```lua
function love.mousepressed(x, y, button)
	print("press", button)
	if button == 1 then
		love.mouse.setRelativeMode(true)
	end
end

function love.mousereleased(x, y, button)
	print("release", button)
	if button == 1 then
		love.mouse.setRelativeMode(false)
	end
end
```

Run this and do a left click drag, then immediately right click and it will not print anything.
I am on Windows 10.

**Comment by slime73** [comment]
I haven't been able to reproduce this so far on my own Windows 10 system, tested with both love 11.4 and the latest 11.5 prerelease.

Maybe some third-party software is interfering, or there's a bug in your mouse driver? I'm not really sure what could cause it to happen on one system and not another.

**Comment by badduck32** [comment]
I was able to reproduce this on my system, Windows 10 and LÖVE 11.4. I was even able to replicate it using my laptop's mousepad, but I don't know if that makes any difference.

**Comment by slime73** [comment]
I just updated SDL2 to the latest version on Windows - can you try a new build of love 11.5 to see if it changed anything? Here's a 64 bit build: https://ci.appveyor.com/project/slime73/love/build/job/mtahai38s10qr5yh/artifacts

**Comment by Sin-tel** [comment]
This fixes it!

**Comment by slime73** [comment]
Great, thanks for testing!
