### ISSUE TITLE
NOT AN ISSUE! But will there be native MoonScript support soon?

### ISSUE THREAD

**Issue by Thetest-1** [love2d/love#1949]
**btw** MoonScript is a scripting language by Leafo (the maker of itch.io) which transpiles to lua and I would really like native moonscript in love2d and I'm sorry that I made an issue of this but I don't know where to suggest features (sorry)

**Comment by slime73** [comment]
The discord server or forums are a more appropriate place to ask - we don't have any plans for more MoonScript integration in the future than what already exists now, but there might be existing ways to make your workflow nicer with it?

**Comment by HDPLocust** [comment]
> MoonScript

You can easilly add a loader for .moon files that converts it to Lua on-the-fly. Something like this, and `require` will work with .moon files:
![image](https://github.com/love2d/love/assets/13125395/f016999a-a8de-4ba4-8b97-d0ad06fdc5a3)
