### ISSUE TITLE
UVs for love.graphics.rectangle

### ISSUE THREAD

**Issue by nowakf** [love2d/love#1951]
love.graphics.rectangle doesn't produce a rect with UVs. Is this the normal user expectation?

(I just spent about forty minutes trying to debug a shader before reading the line on the wiki :100: )

**Comment by HDPLocust** [comment]
Why not try texture with a quad?

**Comment by nowakf** [comment]
That's what I did in the end - I was just thinking that maybe having no UVs for rectangles will trip other users up in the future, because I don't think it's what you'd expect.
