### ISSUE TITLE
Windows 11 forcing fullscreen

### ISSUE THREAD

**Issue by TimeyDingo** [love2d/love#1956]
In my conf.lua I have fullscreen set for false and this works on windows 10, on my windows 11 laptop though no matter what I set it starts and continues to operate in fullscreen. Even with love.window.setmode it remains in fullscreen. I'm unsure if this is a love issue or a windows 11 issue. 

Love 11.4
Windows 11 22H2 X64

**Comment by MikuAuahDark** [comment]
If you're setting your width and height dimension equal to your desktop resolution and you set borderless to true, certain drivers may pick that as "fullscreen".

**Comment by TimeyDingo** [comment]
> 

I also tried with borderless true and false, and even with resolutions that were drastically different from my actual monitors resolution it still forced full screen

**Comment by MikuAuahDark** [comment]
If it also forces fullscreen when launching the no-game screen (simply launch `love.exe`) then a 3rd-party app might interfere with LOVE.

**Comment by TimeyDingo** [comment]
just booted my windows 11 laptop and tested, the love.exe launches windowed as it would on my windows 10 device

**Comment by MikuAuahDark** [comment]
Can you send a minimal reproducible example project?

**Comment by TimeyDingo** [comment]
What do you mean by that? Sorry I'm new to collaborating on github with other people just sorta use it for my own stuff

**Comment by MikuAuahDark** [comment]
A minimal LOVE project, zipped, that reproduce the issue.

**Comment by TimeyDingo** [comment]
yeah one sec

**Comment by TimeyDingo** [comment]
[Testing project.zip](https://github.com/love2d/love/files/12209701/Testing.project.zip)

**Comment by MikuAuahDark** [comment]
I'm unable to reproduce said issue in my laptop with 1080p display, running Windows 11. Game launches windowed as expected.

**Comment by TimeyDingo** [comment]
so its my laptops issue okay good to know lol. Glad its not a love issue

**Comment by TimeyDingo** [comment]
I should close the issue now right? This is my first issue post that went anywhere
