### ISSUE TITLE
100% disk usage

### ISSUE THREAD

**Issue by zzgames** [love2d/love#1957]
While working on a Love2D game, I noticed that my PC always slows down after running the game. I thought the problem was in my game but after running the "nogame" I was having the same problem. Then I checked Task Manager and there I found that my C drive (both my game and love2d are on the D drive) is in 100% usage. I tried to compile Love2D myself, but nothing changed.

https://github.com/love2d/love/assets/84251288/21322f6f-c44f-4b84-beff-09b6d6b6c9e6

**Comment by slime73** [comment]
If you go to the Processes section of Task Manager you can see what program is using your HDD. My first guess is some antirvirus program or driver.

**Comment by zzgames** [comment]
It was Windows Defender. Thanks!

That guide helped me turn it off:
https://windowsreport.com/sysmain-high-disk-usage/
