### ISSUE TITLE
Writing byte data to file produces unexpected results in love 12

### ISSUE THREAD

**Issue by Bauumm** [love2d/love#1962]
When writing byte data into a file the output is something random instead of the actual data starting with love 12 (using the latest appimage from github actions (commit: 6e80d85110c8f8c085d2d2307feb76b358887b04) on arch linux)

Reproduce with this code snippet:
```lua
local original_data = love.data.newByteData("Hello World!!!")
local file = love.filesystem.newFile("somefile")
file:open("w")
file:write(original_data)
file:close()
file:open("r")
local data = file:read("data")
file:close()
print("data after saving in file:", data:getString())
print("original data: ", original_data:getString())
```
In love 11.4 it produces the expected output:
```
data after saving in file:	Hello World!!!
original data: 	Hello World!!!
```
But in love 12 it prints this:
```
data after saving in file:	PЗ
original data: 	Hello World!!!
```
(It is not an issue with reading as the actual file contents are wrong if you check that as well.)

**Comment by slime73** [comment]
Fixed in [b0e3246](https://github.com/love2d/love/commit/b0e3246ba8716d3ee2a35f85809fb0ef0e59603e). Thanks!
