### ISSUE TITLE
Memory can not be freed newImage() then set nil and calling GC

### ISSUE THREAD

**Issue by jakitliang** [love2d/love#1963]
### Situation

First of all, my project dir is:
./main.lua
./res/wallpaper1.jpg
./res/wallpaper2.jpg
./res/wallpaper3.jpg
./res/wallpaper...(etc)

### Code

And main.lua:
```
function love.load()
  myWallpapers = {}
end

function love.keypressed(key)
 if key == "f8" then
    for i = 1, 5 do
      table.insert(myWallpapers, love.graphics.newImage("res/wallpaper"..i..".jpg"))
    end
  elseif key == "f3" then
    myWallpapers = nil -- clean the wallpapaers loaded in memory
    collectgarbage("collect") -- Calling GC to clear memory
    myWallpapers = {} // Reset Array table
  end
end
```

#### Program Start

When start the program, no wallpapaers loaded. So the memory usage is `80MB`.

#### Load wallpapaers as love image texture

Press `F8` to load my wallpaper JPEG files and insert them into a table `myWallpapers`.

And now, the memory usage is up to `290MB`

#### Free images and Clean up memory

Press `F3` to clean up all the images stored in `myWallpapers`.

Now, the memory usage is about `114MB` ~ `130MB`

**Why memory usage can not free onto the origin `80MB`.**

**IS THERE SOMETHING NOT FREED?**

### Expected Result

Press `F3` to clean up all the images stored in `myWallpapers`.

The memory usage should be `80MB` as while this program was started.

**Comment by HDPLocust** [comment]
This model of working with memory worked a long time ago.
Currently, all modern operating systems are equipped with a memory scheduler that will NOT immediately release memory allocated to the application until all RAM begins to run out. This is done for the reasons that "if an application has requested so much memory, then there is no reason that it will not do so again."
So direct management of memory consumption no longer exists for operating system reasons.

**Comment by flamendless** [comment]
Instead of nil-ing. Iterate the wallpapers and call :release() in each one and then collect garbage

**Comment by jakitliang** [comment]
> Instead of nil-ing. Iterate the wallpapers and call :release() in each one and then collect garbage

Let me have a try

**Comment by slime73** [comment]
Yep, as stated above graphics drivers (and the OS) may use memory pools they own, which makes tracking memory leaks by looking at whether memory is marked as used by the driver or app after deleting the objects in your app not accurate.

I did some quick tests and found no memory leaks in newImage.
