### ISSUE TITLE
Remove limit of 1 from setColor

### ISSUE THREAD

**Issue by mateuskreuch** [love2d/love#1967]
Oversaturation can be used to great effect in games; making sprites white when an enemy takes damage, for example. Is there any backend that doesn't result in oversaturation when increasing colors past 1, in which case this change would be a problem? If not I can make a pull request as it seems it would be quite simple to do.

**Comment by mateuskreuch** [comment]
I see that there was some discussion on this already. Maybe a separate function would be appropriate, then?

**Comment by slime73** [comment]
> Is there any backend that doesn't result in oversaturation when increasing colors past 1, in which case this change would be a problem? 

Yes:
* When gamma-correct rendering is enabled, color values are internally converted from sRGB to linear RGB after they're passed into setColor. This is only really valid for the [0, 1] range.
* Several different APIs internally use normalized bytes or other data types for those color values, which can't go outside of the [0, 1] range.

You can use a shader to do what you want, which will also be way more flexible than any built-in function love could provide. For example:
```Lua
shader = love.graphics.newShader[[
uniform float intensity;

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords)
{
    vec4 c = Texel(tex, texture_coords) * color;
    c.rgb *= intensity; // you could add instead of multiply, or whatever other operation you want
    return c;
}
]]

function love.draw()
    love.graphics.setShader(shader)
    shader:send("intensity", 10)
    love.graphics.draw(image, x, y)
    love.graphics.setShader()
end
```

**Comment by mateuskreuch** [comment]
@slime73
The effect I'm trying to achieve is the white-on-damage I mentioned. I've considered using a shader, but my game only uses spritebatches for performance reasons as it draws a lot of sprites. So, I've thought of a few workarounds to filter which sprites should be treated differently, but the most reasonable one (and cheapest) is calling setColor(0, 0, 0) and remap via shader pure black to pure white.

This seems very hackish, which I understand is the reality of game development, but I'd avoid it if possible. Is there any better solution? Thank you for the fast reply, by the way. I know this sort of stuff can get annoying.

**Comment by radgeRayden** [comment]
If you don't mind, the [LÖVE discord server](https://discord.gg/hHDfpP4a2w) would be a better place for questions.

**Comment by slime73** [comment]
You can use https://love2d.org/wiki/SpriteBatch:attachAttribute to have custom per-sprite data in a SpriteBatch (each set of 4 vertices in the mesh you attach would have the same values, and it'd be available in the vertex shader which can be passed down to the pixel shader).

As radge says, the discord server or forums are better places for support questions.
