### ISSUE TITLE
Full window Transparency not working on Linux

### ISSUE THREAD

**Issue by VMGuy23** [love2d/love#1968]
Anything meant to be transparent appears black instead

**Comment by slime73** [comment]
This isn't a feature that is supported in love (or in SDL2, which love uses for windowing).

love will eventually use SDL3 when it's ready, which does support that via a flag during window creation. But it won't be ready for a while.

**Comment by VMGuy23** [comment]
alright, thanks for your answer, i guess i will have to do without for the time being
