### ISSUE TITLE
ps vita

### ISSUE THREAD

**Issue by kiruhasas22** [love2d/love#1969]
how to port the game to ps vita (if possible)

**Comment by slime73** [comment]
LÖVE doesn't support PS Vita and there aren't plans to in the future. To add support yourself, you'd need to write C++ backend code for different modules (e.g. love.graphics) that works with the PS Vita APIs. I'm not very familiar with the Vita but it seems like it'd be a huge amount of work, and the system probably isn't capable of supporting large portions of love.graphics either.
