### ISSUE TITLE
Bug: rgba8 pixel format generate srgb8 buffer in Love12

### ISSUE THREAD

**Issue by Froyok** [love2d/love#1973]
Hi,

As mentioned on [Discord](https://discord.com/channels/329400828920070144/329404715521802241/1155974966597144706), in Love 12.0 doing the following:
```lua
local Settings = {
	["type"] = "2d",			
	["format"] = "rgba8",		-- Pixel Format
	["readable"] = true,		
	["msaa"] = 0,			
	["mipmaps"] = "none",
}

local Canvas = love.graphics.newCanvas( Width, Height, Settings )
```
will generate a canvas in the format `srgb8` instead of the expected `rgb8`.
(The setting `gammacorrect` is set to `true` in my conf file.)

A workaround is to use the new linear parameter to produce the expected rgb8 buffer:
```lua
local Settings = {
	["type"] = "2d",			
	["format"] = "rgba8",		-- Pixel Format
	["readable"] = true,		
	["msaa"] = 0,			
	["mipmaps"] = "none",
	["linear"] = true
}
```

**Comment by slime73** [comment]
Fixed with [3865868](https://github.com/love2d/love/commit/386586835851c586c5482b73898b5eb7249d7670).
