### ISSUE TITLE
Love for Android doesn't work on recent Android(Android 11)

### ISSUE THREAD

**Issue by SnowdenAvian** [love2d/love#1976]
The official Love for Android doesn't work for Android 11 as play store shows a "This application was made for a older version of Android'![Screenshot_2023-10-05-17-35-52-18_b5a5c5cb02ca09c784c5d88160e2ec24.jpg](https://github.com/love2d/love/assets/146569981/07b80e6e-0231-4111-8032-71eeadf89a84)

**Comment by MikuAuahDark** [comment]
Unfortunately the play store version is outdated. Use the APK from love2d.org instead.
