### ISSUE TITLE
[Feature suggestion] Add text ligatures on `love.graphics.print()` and `love.graphics.printf()`

### ISSUE THREAD

**Issue by alejandro-alzate** [love2d/love#1978]
maybe adding and disabled by default (this ensures that doesn't messes with games that didn't asked it for)
and enable it by calling along the lines of `love.graphics.setTextLigatures(bool)`
and apply after being called

```lua
function love.draw()
    --Enable text ligature
    love.graphics.setTextLigatures(true)

    --Draw cool text
    --The font will make an arrow when sees "->"
    love.graphics.print("hello world! Welcome to -> Player!")

    --Disable ligatures to leave non in-game text  alone
    love.graphics.setTextLigatures(false)
    love.graphics.print(love.time.getFPS().." Fps")
end
```

**Comment by slime73** [comment]
Text ligatures are part of a font (so having a toggle for it doesn't make sense IMO). This is automatically supported in love 12 since it uses harfbuzz to do text shaping.

**Comment by alejandro-alzate** [comment]
i suppose that v12 is still in beta right?
also could you refer me to where i can find where print resides
my take is if is not compile dependent i could choose what function use
I mean implement the "legacy" one on my code and use either depending of the context.
that's possible?

**Comment by alejandro-alzate** [comment]
> I think it'd be way simpler to just externally edit the font file you have to remove that ligature.

How i could that though?
is print compile dependent?
what about a shader?

**Comment by slime73** [comment]
You'd get a program that can edit truetype / opentype font files, and use that to edit your font. It doesn't have to do with editing love - since love just renders what's in the font file.

**Comment by alejandro-alzate** [comment]
ok, i'll try that way.
also you have a mild date of when v12 goes live?

**Comment by slime73** [comment]
There's no release date, but there's a mostly up to date changelog on the wiki: https://love2d.org/wiki/12.0 and automatically built binaries for Windows/Mac/Linux in the github actions section of this repository.

**Comment by alejandro-alzate** [comment]
ok, thanks for the time and also the insight.
also i found a bug but don't worry about it. is consistent but convoluted, please prioritize other's bugs.
