### ISSUE TITLE
Can't open/execute love projects on mobile

### ISSUE THREAD

**Issue by Antonygamergod** [love2d/love#1981]
/I downloaded the apk of the LÖVE app to create my games, but when I run or open the app to run the code, the app only shows the "no game" screen, and this happens even when I open the code itself in the app, Does this happen because I downloaded the apk or am I doing something wrong?

**Comment by akkartik** [comment]
I've noticed some flakiness as well in opening .love files. The place that has worked most reliably for me is the download dialog of my web browser. The file app in particular has been hit or miss.

**Comment by MikuAuahDark** [comment]
Unfortunately this is caused by Android restriction. There's nothing we can do to make file manager recognize `.love` file to be opened by LOVE.

The next version should have separate app icon which allows you to pick `.love` file, at least.

**Comment by Antonygamergod** [comment]
Thanks for letting me know, but the "file" or "code" I'm talking about is main.lua and not .love

I've tried several tutorials and they all said to create a folder called "lovegame" and that I should put the .lua file in there, and even though I do that, when I open LÖVE the file doesn't work

**Comment by Antonygamergod** [comment]
I only downloaded the apk because the play store version is incompatible with my cell phone (probably because my cell phone is Android 10)

**Comment by MikuAuahDark** [comment]
> Thanks for letting me know, but the "file" or "code" I'm talking about is main.lua and not .love

Yeah, it's also same restriction. The fact you mentioned Android 10 renders the "lovegame" method effectively useless.

**Comment by Antonygamergod** [comment]
Oh ok thank you
