### ISSUE TITLE
setIdentify with fused games

### ISSUE THREAD

**Issue by 2dengine** [love2d/love#1983]
We need to disable setIdentify when running code in fused games as it may lead to security issues in the future where one game script can access the data of other Love2D games.
File locking is another fundamental feature missing from love.filesystem.

**Comment by zorggn** [comment]
You mean `setIdentity` with a t; and you can always write your script loading code to sandbox user code so it doesn't do that; in my opinion that would be a step back considering the steps 12.0 implemented for less sandboxing with love.filesystem.

Also can you expand on what you mean by file locking?

**Comment by MikuAuahDark** [comment]
I don't think this is solvable problem for now. 2 games with same identity means they'll share same save directory. Unfortunately this means rogue game with same identity can alter other games. The only way to solve this is to sandbox everything (which mobile already does, but desktop does not).

As for file locking, PhysFS does not support the feature.
