### ISSUE TITLE
[Love 12.0][Feature request] Ability to provide debug name for buffer/texture resources generated by Love

### ISSUE THREAD

**Issue by Froyok** [love2d/love#1992]
Hi,

When using a graphic debugger (like [RenderDoc](https://renderdoc.org/)) to inspect a frame made with Löve, the canvas and buffers generated by Löve have generic names (ex: `Texture 471`). 

This makes things a bit difficult sometimes to track bugs or even resources across multiple drawcalls.

I imagine that currently those names are automatic, defined by the graphic API when it creates the objects. It seems however that debug names can be provided, which could help identify more easily those resources: https://renderdoc.org/docs/how/how_annotate_capture.html#application-provided-object-names

Would it be possible to expose a way to specify this debug name on the Lua side ?
Maybe something like `Texture:setDebugName()` and `Texture:getDebugName()`.

**Comment by slime73** [comment]
This is implemented now. love's built-in/default textures and buffers don't have unique names yet, but that's partly because they aren't represented by actual Texture and Buffer objects on all backends. I already want to clean that up for unrelated reasons, so I'll add debug names to those when I do that.

**Comment by Froyok** [comment]
Looking at the review (haven't tried it yet), and not being familiar enough with the sources, does it works as well with `love.graphics.newImage` for example ? Or is it only canvas/buffers ?

**Comment by nikeinikei** [comment]
It works for any texture, image and canvas got merged into one in Löve 12.

**Comment by Froyok** [comment]
Great, thank you for confirming. :)

**Comment by Froyok** [comment]
Can confirm, it works really well ! Thank you both ! :heart: 
![2023-12-14__20-28-59](https://github.com/love2d/love/assets/6290387/c6b194b1-fdc3-44da-becb-80213e745a53)
