### ISSUE TITLE
bizarre error reporting if error happens during return statement

### ISSUE THREAD

**Issue by ncrecc** [love2d/love#1993]
here's a ``main.lua`` with some broken code:
```lua
hero = {}

function hero:isKeyDown(key)
	print(love.keyboard.isDown(key))
end

function hero:update()
	self:isKeyDown(nil)
end

function love.update()
	hero:update()
end
```
it gives us a reasonable enough error:
```
Error

main.lua:4: bad argument #1 to 'isDown' (string expected, got nil)


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'isDown'
main.lua:4: in function 'isKeyDown'
main.lua:8: in function 'update'
main.lua:12: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'
```
but if i change line 4 to ``return love.keyboard.isDown(key)``, then we get this instead:
```
Error

main.lua:8: calling 'isKeyDown' on bad self (string expected, got nil)


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'isKeyDown'
main.lua:8: in function 'update'
main.lua:12: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'
```
and if i change line 8 to ``return self:isKeyDown(nil)``, we get this (at which point the original error on line 4 becomes a distant memory):
```
Error

main.lua:12: calling 'update' on bad self (string expected, got nil)


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'update'
main.lua:12: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'
```

if i change ``hero:isKeyDown()`` and ``hero:update()`` to be normal functions instead of methods (``.`` instead of ``:``), something similar still happens where the error is reported as being one level higher than it actually is - intended, maybe? - but without the mention of calling on a "[bad self](https://youtu.be/fWAaABVOHO8)". the example demonstrated here with "bad self" is closer to what i actually stumbled upon, and much more confusing.

also, i get a reasonable error again, correctly pointing to a bad argument to isDown, if i change line 4 to ``return (love.keyboard.isDown(key))``, wrapping the value returned by love.keyboard.isDown in parens.

**Comment by slime73** [comment]
I think this is Lua's [tail call feature](https://www.lua.org/pil/6.3.html) combined with LuaJIT's optimizations to it. I don't believe there's much love can do to affect this.
