### ISSUE TITLE
love.filesystem.setCRequirePath doesn't work under Linux

### ISSUE THREAD

**Issue by KayleMaster** [love2d/love#1998]
I've made a minimum reproducible example:  
[requirePathTest.zip](https://github.com/love2d/love/files/13749165/requirePathTest.zip)  

main.lua
```lua
local https
local os = love.system.getOS()
if os == "Windows" then
    love.filesystem.setCRequirePath("windows/??")
    https = require("https")
elseif os == "Linux" then
    love.filesystem.setCRequirePath("linux/??")
    https = require("https")
else
    print("os is not windows, not loading https")
end
print(https)
```

And then have the https.dll under the folder windows and the https.so under the folder linux. You can probably use empty files, if you don't want to download the zip. Just make sure you get the right error (not found).   
This code works on windows but not on linux.    
If you move the https.so in root dir, it will work, even though we've set the requireCPath to a subfolder.   
```
Error

main.lua:8: module 'https' not found:
no field package.preload['https']
no 'https' in LOVE game directories.
no file 'https' in LOVE paths.
no file './https.lua'
no file '/usr/share/luajit-2.1.0-beta3/https.lua'
no file '/usr/local/share/lua/5.1/https.lua'
no file '/usr/local/share/lua/5.1/https/init.lua'
no file '/usr/share/lua/5.1/https.lua'
no file '/usr/share/lua/5.1/https/init.lua'
no file './https.so'
no file '/usr/local/lib/lua/5.1/https.so'
no file '/usr/lib/x86_64-linux-gnu/lua/5.1/https.so'
no file '/usr/local/lib/lua/5.1/loadall.so'


Traceback

[C]: in function 'require'
main.lua:8: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```  
  
Love2D version: 11.3 and 11.5 (probably 11.4 as well)

**Comment by MikuAuahDark** [comment]
I cannot reproduce this in WSL2 running Debian 12.

Can you try if loading the `https.so` standalone using LuaJIT works?

**Comment by MikuAuahDark** [comment]
Place breakpoint in this line and see what is `filepath` and the resulting `handle`.

https://github.com/love2d/love/blob/0df51cf74376c7bf0e8479c276041e5c8e0f7b6b/src/modules/filesystem/wrap_Filesystem.cpp#L836

**Comment by slime73** [comment]
Keep in mind operating systems cannot directly load dll / .so files that are inside a zip (or .love file). You can copy them to the save directory in that situation.

**Comment by slime73** [comment]
Does it work if you specify the folder name when running the game instead of using `.`?

**Comment by MikuAuahDark** [comment]
If the Windows 10 machine happen not to have VS2022 redistributable installed, that explains everything.

**Comment by MikuAuahDark** [comment]
LOVE 11.5 uses VS2013 runtime compiled through AppVeor. GitHub Actions only provides VS2019 as their oldest toolchain. In Linux, it's likely that your glibc is too old.

**Comment by MikuAuahDark** [comment]
Because [`SDL_LoadObject`](https://wiki.libsdl.org/SDL2/SDL_LoadObject) (which LOVE uses for its C loader) doesn't provide neat way to tell if the file doesn't exist or fails to load.

**Comment by slime73** [comment]
The dll load function (SDL_LoadObject in this case) is called for every viable extension (e.g. both `.dylib` and `.so` on macOS) and for every search path specified in setCRequirePath. That'd be a lot of error messages to sort through - most of them useless information - if it dumped them all out.

**Comment by slime73** [comment]
Did you figure out the Linux issue?

**Comment by slime73** [comment]
love for windows is bundled with the C/C++ redistributable DLLs that it needs to run on its target platforms, it doesn't need a separate download. For example the official love 11.5 downloads for Windows include VS2013's `msvcp120.dll` and `msvcr120.dll`, since it's build with VS2013.

The love appimage is similarly self-contained, it has all the C/C++ library dependencies it needs in order to run on target systems down to the minimum supported one, inside the AppImage container.

On the other hand if you're using someone's build of love from a package manager on Linux, usually it's not drop-in runnable on other systems because it might depend on libraries that are elsewhere on your computer. Similarly if you're using an unofficial or otherwise custom packaged build on Linux you'll need to make sure it's runnable where you want on your own.

**Comment by MikuAuahDark** [comment]
If it's glibc issue then there's no way other than updating your distro.

**Comment by learn-more** [comment]
Running `ldd https.so` should show any dependency errors that cause `https.so` to not be loaded.

**Comment by MikuAuahDark** [comment]
At long last, since this is Linux distribution issue trying to load shared library compiled for newer glibc than the user Linux distro, this in turns a system configuration issue.
