### ISSUE TITLE
winget package is broken

### ISSUE THREAD

**Issue by griffi-gh** [love2d/love#2005]
`winget install --id Love2d.Love2d` fails due to invalid checksum, can only be installed with `--ignore-security-hash`

**Comment by slime73** [comment]
We don't control that package or package manager. We definitely wouldn't name it Love2d.Love2d if we did. :) 

The windows package manager probably has its own locations to troubleshoot and debug, and to report bugs if necessary.

**Comment by griffi-gh** [comment]
ah, i assumed it was official.

**Comment by slime73** [comment]
In general most app/library package managers control their contents rather than individual developers providing official packages.
