### ISSUE TITLE
LÖVE not rendering

### ISSUE THREAD

**Issue by CreepercraftYT** [love2d/love#2006]
LÖVE isn't rendering properly in my computer, however, text does render
![image](https://github.com/love2d/love/assets/69971786/1e2dad3e-84be-45b1-8221-5e561d3fba6f)
![image](https://github.com/love2d/love/assets/69971786/3bb02dd2-8d44-466e-ad26-e20e7b00f96b)
here are my specs:
![image](https://github.com/love2d/love/assets/69971786/10317771-3863-45d2-91fe-4c057305c4d2)
![image](https://github.com/love2d/love/assets/69971786/6211638b-b136-49f6-b6e4-76ca04568161)

**Comment by slime73** [comment]
Can you make sure your graphics driver version is as up to date as possible? There was a bug in AMD's 22.7 drivers that caused this sort of issue with love, and it was fixed in later releases.

**Comment by CreepercraftYT** [comment]
umm, i think it is
![image](https://github.com/love2d/love/assets/69971786/581bba7f-accb-4346-965f-fb9602b97f74)

**Comment by CreepercraftYT** [comment]
btw, the LÖVE version is 11.5

**Comment by slime73** [comment]
Yes, that looks like it's probably the buggy AMD driver version because it came out around summer 2022. You should be able to update it by downloading a new driver from AMD's website or via update tools on your computer.

**Comment by CreepercraftYT** [comment]
i updated the drivers, now it works!, thanks :3

**Comment by slime73** [comment]
You're welcome!
