### ISSUE TITLE
love.data.hash container output typed for love 12.0

### ISSUE THREAD

**Issue by EngineerSmith** [love2d/love#2015]
To match other functions within the `love.data` module. I'll like to see `love.data.hash` accept an enum for if it should return `Data` or a `String`. Right now, it only return a string with no option for data.

This will be a breaking change, but it "shouldn't be too difficult"™ to add.

Why should this be implemented? Well, having to create a separate bytedata when I want it in data form isn't easy to make the code readable. Plus, it doesn't following the other conventions of `love.data`. Considering that the returned value cannot be logged, or printed without being encoded to base64 - doesn't really suit being stored as a string.

If you wanted to save it? File supports writing data. 
If you wanted to send it across threads? Variant supports data.
If you wanted to log it? Encoder supported data input

I have no idea why you'd want it to be a string, but it should still have the option to be a string.

```lua
ld = love.data
data = love.data.newByteData(...)

hashed = ld.newByteData(ld.hash("sha512", data))
-- vs
hashed = ld.hash("data", "sha512", data)

-- and it's compliment
hashed = ld.hash("string", "sha512", data)
```

https://github.com/love2d/love/blob/12.0-development/src/modules/data/wrap_DataModule.cpp#L323

**Comment by slime73** [comment]
Addressed in [483237e](https://github.com/love2d/love/commit/483237e).
