### ISSUE TITLE
Keyboard and mouse button states are lost when love.window.setMode() is called (11.5 on Windows)

### ISSUE THREAD

**Issue by AverniteDF** [love2d/love#2017]
I've been noticing some buggy keyboard and mouse behavior occurring after love.window.setMode() is called (this is with 11.5 on Windows). What happens is that Love2D 'forgets' all of the keys and mouse buttons that were being held down at the time setMode() was called. I know that the window gets a new Windows handle when setMode() is called--could that be the cause? It's problematic because Love2D invokes love.keyreleased() for all the keys that were being held down (even though they're still being held down). This issue also causes problems with the mouse buttons, Love2D gets confused because it doesn't know the correct state of the buttons and it doesn't invoke the pressed/released callbacks as it should. Mouse setGrabbed() also fails to confine the pointer to the window client area if you hold down any of the mouse buttons during setMode(). Again, could the change of the window's hWnd be the root cause of all these issues? I know a lot of Win32 API calls rely on that handle.

**Comment by slime73** [comment]
You'll run into a bunch of issues if you recreate the window inside an input press event. I recommend doing it on release instead.

**Comment by HDPLocust** [comment]
It might also be a good idea to separate the creation and execution of events.
I can try to advise using an event bus, for example:
```
function love.changescreenmode(width, height)
  love.window.setMode(width, height)
end

function love.update(dt)
  if love.keyboard.isDown("lctrl") and love.keyboard.isDown("f") then
    love.event.push("changescreenmode", 800, 600)
  end
end```

**Comment by AverniteDF** [comment]
I think SDL assumes that all keys/buttons are in an unpressed state when it creates a window because any keypress that happened prior to the window being created is considered to be outside the scope or "jurisdiction" of the window. The input event system ignores keypresses and mouse clicks that happen outside the window and the isDown() states need to correspond with the events received. However, in the case of subsequent windows being created (such as toggling fullscreen) maybe the handover from one window to another could be handled better because even though it's a new window there is (or should be) continuity in the application.

Something that might not be too difficult to fix: When you hold down a mouse button in relative mode (with grabbed pointer) during a love.window.setMode() call the grab stops functioning and the pointer can leave the confines of the newly created window. I think this can be solved by re-grabbing the new window. I tried this using Win32 API calls and it worked. I'm not sure if this is an issue for Love2D or SDL.

**Comment by slime73** [comment]
love 12 doesn't destroy and recreate the window when setMode is called, so this shouldn't be an issue anymore with that version.
