### ISSUE TITLE
Request: ability to bind a texture to a shader at specific mipmap level

### ISSUE THREAD

**Issue by Froyok** [love2d/love#2022]
With the current API available on Love 12.0, the only way to write into the mipmap of a Canvas/Texture is to call `setCanvas()` with the target mip level. This requires to perform several copies or having multiple Canvas at hand when wanting to generate multiple mipmap levels (for example downsampling an image with a custom kernel).

Now that compute shaders are available, it would be nice to be able to bind a canvas to a compute shader at a specific mipmap level (which i think is doable in [OpenGL too](https://www.khronos.org/opengl/wiki/Image_Load_Store) - in addition to Vulkan/Metal), this way we could render each mipmap with the same source texture and even within the same drawcall (with the use of barriers, like [in this example](https://gpuopen.com/fidelityfx-spd/)). 

In my case, this would allow me to:

- Downsampling my bloom passes slightly faster.
- Generate/manage only a single canvas instead of several (requiring only one bind later one as well).
- Blur/Downsample with custom kernels (depth downsample for HZB, screen-space blur for refraction, SSR).

Right now the example I just mentioned can be tedious to setup and manage currently in love.

Please note that my request is based on my current understanding of Love API, it's likely that I overlooked some details.

**Comment by slime73** [comment]
love 12 does support image load/store in compute shaders (using the `image2D` types etc.) but it always uses the first mipmap right now. I think it should be possible to add support for binding a specific mipmap level - the Vulkan and Metal backends will have to use texture views for that, internally.

Or... I've been thinking about whether texture views are useful to expose in general. Maybe it makes more sense to do that instead of using them behind the scenes.

**Comment by Froyok** [comment]
I have read about `imageView` as well, but I didn't request that directly because I felt it was too low level given Love API. 
However having that `imageView` object/function would maybe help to check its support on platform that don't ? Like via `love.graphics.isSupported` ?

**Comment by slime73** [comment]
I was thinking of something pretty simple like:
```Lua
texture = love.graphics.newTextureView(basetexture, texturetype, pixelformat, startmip, mipcount, startlayer, layercount)
```
So it wouldn't add a new type, and the new API would be close to love.data.newDataView. It'd be gated by `glsl4` support.

**Comment by Froyok** [comment]
No new type, so it would return a "regular" texture ?

**Comment by slime73** [comment]
Yeah, its properties (like pixel format or mip count or size) would just reflect its internal view's properties.
