### ISSUE TITLE
Bug: File:read() returns empty string instead of nil when past end of file

### ISSUE THREAD

**Issue by lolbinarycat** [love2d/love#2025]
```lua
local f1 = love.filesystem.newFile("test123", "r")
f1:seek(1000)
print(f1:read(10))
```

seems like a case of using `==` instead of `>=` to detect end of file.

i originally encountered this when a file got truncated while i was reading it.

**Comment by slime73** [comment]
I don't think the documentation says it will return nil in that situation, does it?

**Comment by lolbinarycat** [comment]
you are correct, i was confusing love2d read() with liblua read(), i didn't realize they were that incompatible.
