### ISSUE TITLE
Low FPS on certain monitor

### ISSUE THREAD

**Issue by jarrraxxus** [love2d/love#2027]
My CPU is 7800X3D and the graphics card is 7900XTX. Recently, I've been taking a game development course and trying a very simple demo. The only possible reason for the demo running under 300 frames per second might be some software restrictions.

I have 3 display devices connected to my computer:

An LG UltraGear GP95R, which is a 4K 144Hz monitor, connected via DisplayPort.
An MSI mag274qrf-qd, which is a 2K 165Hz monitor, also connected via DisplayPort.
And an LG C1, using an HDMI connection.
When I simultaneously connect and enable all three display devices and then launch the demo, the frame rates vary on all three devices. The demo runs at over 500 frames per second on the C1, 144 frames per second on the MSI, and less than 60 frames per second on the GP95R, and it's extremely unstable.
Later, I tried connecting only the GP95R, but the result was the same.

Normally, when playing games like BG3, such significant differences in frame rates or GPU usage among different devices wouldn't occur.

**Comment by slime73** [comment]
> The only possible reason for the demo running under 300 frames per second might be some software restrictions.

vsync is enabled by default in LÖVE. If your demo's code doesn't turn it off, that'd be a reason for things running at lower than 300 frames per second.

> less than 60 frames per second on the GP95R, and it's extremely unstable.

Assuming vsync is enabled, which version of LÖVE are you using? If you're using 11.4 or older maybe try 11.5. Or if you are using 11.5, see if it behaves any differently with [11.4](https://github.com/love2d/love/releases/tag/11.4).

That being said, the results of what you've tested so far could be a system display configuration issue on your end (for example if vsync is on in your project, your graphics driver settings on your computer may be overriding it in some situations). It's hard to guess from the info you've provided.

**Comment by jarrraxxus** [comment]
> > The only possible reason for the demo running under 300 frames per second might be some software restrictions.
> 
> vsync is enabled by default in LÖVE. If your demo's code doesn't turn it off, that'd be a reason for things running at lower than 300 frames per second.
> 
> > less than 60 frames per second on the GP95R, and it's extremely unstable.
> 
> Assuming vsync is enabled, which version of LÖVE are you using? If you're using 11.4 or older maybe try 11.5. Or if you are using 11.5, see if it behaves any differently with [11.4](https://github.com/love2d/love/releases/tag/11.4).
> 
> That being said, the results of what you've tested so far could be a system display configuration issue on your end (for example if vsync is on in your project, your graphics driver settings on your computer may be overriding it in some situations). It's hard to guess from the info you've provided. The forums or discord server or subreddit may be more appropriate places to figure that sort of thing out.

The 11.4 version works fine on both of my monitors and the demo could easily reach 500 fps.

**Comment by slime73** [comment]
Thanks for testing. Can you confirm whether you have vsync enabled or disabled in your demo project? And whether you have vsync or adaptive sync overridden in your graphics driver settings? Also uploading your demo project or a test project that reproduces the issue for you here would be helpful.

**Comment by jarrraxxus** [comment]
You can find the demo here. https://github.com/games50/pong 
I have tried enabling or disabling vsync in the demo, but the frame rate performance did not show significant changes.

> And whether you have vsync or adaptive sync overridden in your graphics driver settings? 

I’m not quite sure about this. Here are the screenshots of my AMD software panel.

![display1](https://github.com/love2d/love/assets/47963792/ae7d1edb-9d57-4729-9205-73069825d114)
![display2](https://github.com/love2d/love/assets/47963792/1f79e17a-35df-423c-82f3-1409da7b6559)

**Comment by slime73** [comment]
If you turn freesync off for the LG display, does love 11.5 behave more consistently there?

Either way it's super weird that vsync doesn't affect things for you, unless you've forced it off in a driver setting somewhere else.

**Comment by slime73** [comment]
I think commits [1d9d33](https://github.com/love2d/love/commit/1d9d3346c52f7f3138be49125afed534a85dd2c7) (12.0) and [60d90e](https://github.com/love2d/love/commit/60d90e03a42a057d1bd7466e6a5683c6f7ae93b9) (11.5) will fix this - I uploaded new builds of 11.5 which include that change, if you want to try.
