### ISSUE TITLE
love.data.compress causes a segfault on macOS Big Sur (LOVE 11.5)

### ISSUE THREAD

**Issue by 143mailliw** [love2d/love#2029]
## Reproduction Steps
- Download a fresh copy of LOVE 11.5 from the LOVE website.
- Create a folder next to the copy of LOVE.
- Inside the folder, create a new file called "main.lua" and place `love.data.compress('string', 'deflate', 'aaaaaa', 1)` in the file.
- Navigate back to the folder with LOVE in it and run `./love.app/Contents/MacOS/love ./<my_folder_name>`
- Observe that the program immediately segfaults.

## Notes
This is a regression from 11.4, which did not have this issue. This issue happens on both ARM and x86 macOS.

**Comment by slime73** [comment]
Does this only happen on macOS 11 in particular, for you? I just tried running that code with love 11.5 on macOS 14 and didn't crash.

**Comment by 143mailliw** [comment]
> Does this only happen on macOS 11 in particular, for you? I just tried running that code with love 11.5 on macOS 14 and didn't crash.

Yes. It works on Ventura and Sonoma, at the very least, but I know for a fact that Big Sur and Catalina (at least) have this problem.

**Comment by slime73** [comment]
In that case I wonder if it's an Apple bug where app references to the system `zlib` library APIs aren't compatible with an older deployment target version when a newer SDK is used to compile, or something.

**Comment by qubitter** [comment]
I can add that the segfault trace looks like this (thanks to MacOS's really remarkably good error tracing):

```
Thread 22 Crashed:: @engine/save_manager.lua
0   ???                               000000000000000000 0 + 0
1   love2d.love                       0x00000001047b8e8d love::data::zlibCompressor::compress(love::data::Compressor::Format, char const*, unsigned long, int, unsigned long&) + 429
2   love2d.love                       0x000000010474dc16 love::data::compress(love::data::Compressor::Format, char const*, unsigned long, int) + 70
```
With the following error flags set:

```
Crashed Thread:        22  @engine/save_manager.lua

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [36532]
```

**Comment by qubitter** [comment]
Update: when compiling 11.5 from scratch on 11.7.10 (20G1427) and attempting to reproduce the program functions completely normally. So it appears to be yet another compiler bug.

**Comment by slime73** [comment]
I wonder if this Xcode update fixes it: https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes#Linking

I can try uploading a rebuilt version of 11.5 using Xcode 15.2 later, if you want to try.

**Comment by 143mailliw** [comment]
> I wonder if this Xcode update fixes it: https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes#Linking
> 
> I can try uploading a rebuilt version of 11.5 using Xcode 15.2 later, if you want to try.

Seems like the issue. I can't get to compiling LOVE today but if a build was made I can certainly report if the issue's been resolved.

**Comment by 143mailliw** [comment]
@slime73 I'm not sure if it was upgrading to Xcode 15.2, or building with `MACOSX_DEPLOYMENT_TARGET=10.13` (I got a warning about 10.11 not being valid anymore), but I was able to build a version of LOVE that works correctly on Big Sur.

**Comment by slime73** [comment]
I've updated the 11.5 macOS build in the releases section after recompiling with Xcode 15.2. That should fix it, but let me know if you still run into issues.
