### ISSUE TITLE
Feature request: more performant anti-aliasing. Like FXAA or TAA.

### ISSUE THREAD

**Issue by simonpuravida333** [love2d/love#2058]
MSAA works great, but it's an expensive brute-force algorithm.

Thanks a lot.

**Comment by MikuAuahDark** [comment]
You have to implement that yourself. FXAA can be look at here: https://github.com/mattdesl/glsl-fxaa

TAA is more complex though.

**Comment by simonpuravida333** [comment]
Ok thanks a lot.

I'm using Love2D for creating a work tool (in a live-rendered environment). If it should be liked by people, they may spend hours (writing) in front of widescreen. It's an ecological concern (energy consumption) that is on my mind.

I understand your design decision of how post-processing is entirely handed to the user.
Just wanted add that Love2D is fantastic. I've been using it now for 6 months daily almost. It's all the things I want a 2D engine to be, and none of the things I don't want it be.

Happy Weekend
