### ISSUE TITLE
symbol not found in flat namespace (___PHYSFS_platformCalcBaseDir)

### ISSUE THREAD

**Issue by ryandesign** [love2d/love#2063]
I was able to build love 11.5 on macOS using the autotools build system:

```
platform/unix/automagic -11
./configure --disable-sdlframework --disable-silent-rules --enable-osx --with-lua=lua --with-luaversion=5.1
make -j8
sudo make install
```

but it failed to run:

```
% love-11
dyld[34850]: symbol not found in flat namespace (___PHYSFS_platformCalcBaseDir)
zsh: abort      love-11
```

0.10.2 did not have this problem because it used an external copy of physfs which has been built correctly. 11 includes a bundled copy of physfs that fails to compile physfs_platform_apple.m on Macs.

I see that the CMake build system does include this file:

https://github.com/love2d/love/blob/9473c8d710d17b20ef4127760592aae4a24642b7/CMakeLists.txt#L1684-L1687

Maybe something similar could be added to the autotools build.

**Comment by slime73** [comment]
autotools isn't a supported build system for love on macOS. If you want to build love for macOS yourself instead of using the prebuilt app you can use the xcode project, via a command line if you want - here's an example: https://github.com/love2d/love/blob/11.x/.github/workflows/main.yml#L100-L105

**Comment by ryandesign** [comment]
> autotools isn't a supported build system for love on macOS.

It seemed to be after I spent lots of time submitting bugs about it in 2013.

**Comment by slime73** [comment]
Someone was willing to help debug issues over a decade ago, but that doesn't mean it was an officially supported configuration - and it definitely isn't now (in fact love 12 / the main branch removes building with autotools entirely).
