### ISSUE TITLE
setColor and setBackgroundColor color component values don't work when using ranges 0-255

### ISSUE THREAD

**Issue by rafaeljacov** [love2d/love#2073]
![image](https://github.com/love2d/love/assets/110229646/8bbc08f0-7695-4c3b-95f6-94a084dd7e1f)
![image](https://github.com/love2d/love/assets/110229646/047b482f-a78e-47cb-b813-8d3a0bfd941a)
I'm using version 11.5

**Comment by JasperKr** [comment]
all colors in löve are in the 0 to 1 range

**Comment by rafaeljacov** [comment]
> all colors in löve are in the 0 to 1 range

The docs says otherwise:
![image](https://github.com/love2d/love/assets/110229646/26255f59-ef89-4bb8-94ee-72439568de4c)

**Comment by slime73** [comment]
As the image you posted says, colors are 0-1 in love 11 and newer, and 0-255 in love 0.10 and older.
