### ISSUE TITLE
love.graphics.drawLayer() does not work.

### ISSUE THREAD

**Issue by GeroChuu** [love2d/love#2074]
```lua
local kevin
function love.load()
    kevin = love.graphics.newArrayImage({
        "assets/images/kevin/eye_1.png",
        "assets/images/kevin/eye_2.png", 
       "assets/images/kevin/eye_3.png"
    })
end

function love.draw()
    love.graphics.drawLayer(kevin, 1)
end
```

![love](https://github.com/love2d/love/assets/156046341/0b9f9e79-40d8-4cf4-9983-dc8e4b5ba0ee)

**Comment by EngineerSmith** [comment]
Have you checked if your system supports array images? [love.graphics.getTextureTypes](https://www.love2d.org/wiki/love.graphics.getTextureTypes)

**Comment by GeroChuu** [comment]
Oh, sorry i didn't read about that's...

**Comment by GeroChuu** [comment]
Thanks btw, i'll just us lua table then
