### ISSUE TITLE
Differences between repository and *-linux-src.tar.gz

### ISSUE THREAD

**Issue by davidebeatrici** [love2d/love#2075]
For example, the tagged release contains a CMake project, but `love-11.5-linux-src.tar.gz` doesn't. Why's that?

**Comment by slime73** [comment]
The linux source download for love 11.x has its configure/make setup pregenerated based on `automagic`, so it doesn't need the automagic script. CMake is not the primary officially supported build setup system in love 11, but it is in love 12 (the main branch).

**Comment by davidebeatrici** [comment]
Alright, thank you!
