### ISSUE TITLE
BUG: Increased scaling on windows

### ISSUE THREAD

**Issue by rafaeljacov** [love2d/love#2076]
I have a game that runs and displays fine on my linux machine. But when I tried building and running it for windows the scale of all elements including the window increased and I cannot move the window at all. Some elements of the game is only partially visible or not at all because the game window is larger than the screen.

Here's the release page of the game repo:
[v1.0.1](https://github.com/rafaeljacov/tictactoe_minimax/releases/tag/v1.0.0)

**Comment by radgeRayden** [comment]
LÖVE on Linux X11 doesn't take into account desktop scaling at all, whereas on windows if you're not dpi aware (hidpi flag in love.conf) the system will scale your window by multiplying the window size by the scale factor while stretching the backbuffer. Consider asking for support in the discord server or forums for further help on this.

**Comment by rafaeljacov** [comment]
> LÖVE on Linux X11 doesn't take into account desktop scaling at all, whereas on windows if you're not dpi aware (hidpi flag in love.conf) the system will scale your window by multiplying the window size by the scale factor while stretching the backbuffer. Consider asking for support in the discord server or forums for further help on this.

are you referring to t.window.highdpi?

**Comment by radgeRayden** [comment]
Correct.

**Comment by MikuAuahDark** [comment]
LOVE 11 on Windows is not manifested to support high DPI, thus the OS will upscale the window resulting in blurry images. You need to either change the application properties to force "Application" scaling or use 100% DPI scaling.

**Comment by rafaeljacov** [comment]
> LOVE 11 on Windows is not manifested to support high DPI, thus the OS will upscale the window resulting in blurry images. You need to either change the application properties to force "Application" scaling or use 100% DPI scaling.

how can I force application scaling?

**Comment by MikuAuahDark** [comment]
Open LOVE executable properties (not the shortcut) -> Compatibility Tab -> Change High DPI settings -> tick "Override high DPI scaling behavior" and select "Application" for the dropdown.

Ok on everything. You need to restart LOVE (or your game) afterwards though. You also need to tell everyone who have your game about this too.

![gambar](https://github.com/love2d/love/assets/7500438/ebae2f42-70de-483d-9261-84d603c8b4f2)

**Comment by rafaeljacov** [comment]
Thanks but the game is distributed in a zip file so there's no love.exe. Is it possible to do it with the game.exe instead?

**Comment by MikuAuahDark** [comment]
Yes, love.exe or the fused one.

**Comment by rafaeljacov** [comment]
> Yes, love.exe or the fused one.

How can I do it also with linux? I'm using wayland

**Comment by radgeRayden** [comment]
> > Yes, love.exe or the fused one.
> 
> How can I do it also with linux? I'm using wayland. Or can I do it through love2d directly?

On wayland the highdpi flag _does_ work (I just tested it), but love does not use wayland by default. You need to force it (at your own risk) with the `SDL_VIDEODRIVER=wayland,x11` (note the x11 fallback) environment variable, which you can add to a wrapper script.
