### ISSUE TITLE
When I boot up love2d it just shows an duck balloon with an rope saying "no game".

### ISSUE THREAD

**Issue by Blazindude365** [love2d/love#2077]
When I boot up love2d for android it just shows an duck balloon with an rope saying "no game". Is there any way to make an game on love2d for Android?

**Comment by slime73** [comment]
https://love2d.org/wiki/Getting_Started

The forums, discord server, or subreddit are more appropriate places to ask for help about using love - this issue tracker is mainly for bugs and changes within love's source code.
