### ISSUE TITLE
"love.keyboard.isDown" can't detect single letter key input

### ISSUE THREAD

**Issue by wjx-xin** [love2d/love#2080]
if love.keyboard.isDown("right") then
        player.x = player.x + 3
    end

    if love.keyboard.isDown('d') then
        player.x = player.x + 3
    end`

The code detect right arrow is ok，but it can't detect 'd' after pressed. After pressing a letter key, the detection for "right" will also fail regardless of whether the code for the single letter key exists.

**Comment by slime73** [comment]
Are you running into this keyboard hardware limitation? https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo

It's a little hard to tell from your description.

**Comment by wjx-xin** [comment]
This code runs correctly:
```
if love.keyboard.isDown("right") then
    player.x = player.x + 3
end
```
The following code does not taken effect：
```
if love.keyboard.isDown('d') then
    player.x = player.x + 3
end
```
@slime73 Sorry,the details are as above.This is not a key combination problem。

**Comment by slime73** [comment]
The code works fine on my computers. Can you use `love.keypressed` and log all its parameters to see what does happen when you press that key?

**Comment by wjx-xin** [comment]
```
function love.keypressed(key, scancode, isrepeat)
   print(key)
end
```
This code cannot detect the a~z letter keys. It can print the number keys and arrow keys.

**Comment by slime73** [comment]
Does it print nothing at all for the letter keys, or "unknown"? If the latter, can you try including the scancode in the print (like `print(key, scancode)`) as well and see what it says?

Also, some details about your system might be useful:
* Which OS are you using?
* Which language/region do you have keyboard input set to?
* If you're using Linux, are you using love installed from a package manager/source or are you using the AppImage?
* If you are using Linux and aren't using the AppImage, can you try it and see if there's a difference?

**Comment by wjx-xin** [comment]
When I run the program with the command "love", the input language setting changes, which results in the inability to detect letter key input. Thank you for your help.

**Comment by wjx-xin** [comment]
When I run the program with the command "love", the input language setting changes, which results in the inability to detect letter key input. Thank you for your help.

**Comment by CtrlAltDana** [comment]
> When I run the program with the command "love", the input language setting changes, which results in the inability to detect letter key input. Thank you for your help.

I apologize for what might be a dumb question, but is there a workaround for this? I'm just starting to learn love and I have the same issue when starting it from the terminal.
