### ISSUE TITLE
Android: `love.window.getSafeArea()`: returns same dimensions on a display with cutouts

### ISSUE THREAD

**Issue by hhhapz** [love2d/love#2081]
Hey, I'm running love2d in fullscreen mode on a Google Pixel 6a (Android) device which has a pinhole camera at the top of the screen.

I'm using the default template available at https://github.com/love2d/love-android as my base, so perhaps I can modify it there if this is an upstream SDL issue.

Here's the code I'm using to test:

```lua
Fullscreen.w, Fullscreen.h = love.graphics.getDimensions()
local x, y, w, h = love.window.getSafeArea()

print('reg', 0, 0, Fullscreen.w, Fullscreen.h)
print('safe' x, y, w, h)
```

```
I SDL/APP : [LOVE] reg	0	0	375	834
I SDL/APP : [LOVE] safe	0	0	375	834
```

**Comment by slime73** [comment]
Do the reported dimensions or safe area ever change during your app's lifetime?

**Comment by hhhapz** [comment]
Added them to my `update` loop, seems not, sadly:
![image](https://github.com/love2d/love/assets/29532600/d9e47d35-9827-41ac-be31-4e2de8bd53f3)

I will try allowing display orientation changes and see how that interacts

**Comment by MikuAuahDark** [comment]
Is the notification bar visible (not running fullscreen)? If so then the OS will handle the cutouts. Otherwise, try debugging around this function https://github.com/love2d/love-android/blob/b09380d98bc6522bff309d6a580b34d1f58e65ba/app/src/main/java/org/love2d/android/GameActivity.java#L247

**Comment by hhhapz** [comment]
I'm using full screen/immersive mode. I'll investigate this and see what I find :)
