### ISSUE TITLE
how to create virtual joystick for a love2d simulator

### ISSUE THREAD

**Issue by andy380743909** [love2d/love#2083]
I have developed an iOS App that can create and run Love2D games. It has a code editor and some documentations about love2d and lua programming language. I made this app for people who want to learn lua on their iPhone/iPad.
There are 500+ public testers on testflight. I have received some feedback, most of the testers are just using it to run games but not develop games. Maybe writing code on a mobile device is really not a requirement of most people.
They run some love2d games written for pc, the games are all designed to work with keyboard and mouse input or joystick, not the touchscreen.
I want to add a on-screen control to mimic the keyboard mouse or joystick, so people do not need to modify the love2d game code to receive input events.
I see many game emulators have this feature, ![Delta](https://user-images.githubusercontent.com/705880/115471008-203aa480-a1ec-11eb-8aba-237a46799543.png)

I have read the SDL and love2d joystick source code, I know the joystick module supports iOS accelerometer as joystick.
The joystick module init joysticks using a driver array, if I want to implement a virtual joystick driven by touchscreen, do I need to implement my driver, or just using the existing code?

**Comment by slime73** [comment]
You don't need to use love.joystick for that – but this is a place for bug reports and changes to LÖVE's source code. The forums, discord server, or subreddit are more appropriate places for help with game code.

**Comment by andy380743909** [comment]
What I want to do is to implement a virtual joystick or gamepad or keyboard on iOS, so we DO NOT need to modify game code that does not support touchscreen input.

**Comment by slime73** [comment]
One option is to overwrite love.joystick functions (in Lua) and push custom data to love.event. By 'game code' I meant your app code.

**Comment by andy380743909** [comment]
Found this PR: https://github.com/libsdl-org/SDL/pull/9746, this is exact what I need.
I need to port these codes to SDL2, so Love2D can use it.

**Comment by MikuAuahDark** [comment]
What you're looking for is virtual joystick. This is supported since SDL 2.0.14, but LOVE does not expose the functionality of it (and probably never will). You may able to call the appropriate function through LuaJIT FFI (https://wiki.libsdl.org/SDL2/SDL_JoystickAttachVirtual) but considering your target platform is IOS, it may not work there.

**Comment by andy380743909** [comment]
>What you're looking for is virtual joystick. This is supported since SDL 2.0.14
Yes, I found this API in SDL3, and I checked it in SDL2 too, but the SDL2 version virtual joystick API does not have any params about the touchpad or something else related to touchscreen.
Or maybe I am wrong, the touchscreen related params are not indeed, what I need to do is create a gamepad UI and handle touch events and update the virtual joystick states using the existing APIs. I don't need to modify love2d API, I can call SDL API directly from my app.

**Comment by MikuAuahDark** [comment]
Yes you still have to modify your code to translate touchscreen input to virtual joystick states.

**Comment by andy380743909** [comment]
Yes, the touchscreen UI part is not very hard. 
And I found some repos that use the virtual joystick API. https://github.com/search?q=SDL_JoystickAttachVirtual%28SDL_JOYSTICK_TYPE_GAMECONTROLLER&type=code
Some of them are emulator projects too.

**Comment by slime73** [comment]
The FFI does work on iOS, although I'm not positive whether those C APIs will be stripped out of the app because SDL is statically linked.

So you can do my first suggestion (write replacements in Lua that overwrite the joystick APIs), or if those C APIs exist then you can also try that with the [FFI](https://luajit.org/ext_ffi.html) without needing to compile any C code.
