### ISSUE TITLE
System error - The code executioncannot proceed beacuse love.dll was not found

### ISSUE THREAD

**Issue by prime678988** [love2d/love#2084]
reinstalling the program may fix the problem

Please help ;D

I get this error evertime i try to run my lua file ;-;

i tried reinstalling the program as it was advised

so any solutions?????

image - 

![Screenshot (504)](https://github.com/love2d/love/assets/146484064/990c76b2-29c4-4cdc-9a4c-4d68a5ba9fc5)

**Comment by slime73** [comment]
You can't move the love exe somewhere without also moving the dll files that were next to it. I recommend making a shortcut if you want the exe visible on your desktop.

**Comment by prime678988** [comment]
Sorry but am a beginner could you please explain a bit more?

**Comment by prime678988** [comment]
Thanks admin I got it working :D
