### ISSUE TITLE
Built in mechanism to access SDL hints?

### ISSUE THREAD

**Issue by expikr** [love2d/love#2085]
I can use ffi to call SDL directly, but I think setting hints would be a sufficiently constrained use case that it might make sense for Love to expose them, whether via config or a love.config namespace. This would also enable them to be accessed on platforms without ffi support.

**Comment by MikuAuahDark** [comment]
SDL hints can also be set using `setenv` call. I wonder if exposing `setenv` under `love.system` is sufficient?

**Comment by slime73** [comment]
love isn't just meant to be a SDL wrapper, I'd rather decide on an individual basis what functionality to expose in an API. The FFI is also available on all desktop and mobile platforms (i.e. every platform that love officially supports right now).
