### ISSUE TITLE
[Bug] Sequence animation rendering failed on Raspberry Pi

### ISSUE THREAD

**Issue by long568** [love2d/love#2087]
Love Version: 11.5 / 11.x
Hardware: Mac book pro M2 / Raspberry Pi Zero 2 W

I tried to merge multiple sequence frame images into one image. 
The program ran fine on Mac.
But when running on Raspberry Pi, an exception similar to buffer pollution occurred. The program did not crash, but the expected sequence animation was displayed as white.
I tried some smaller sequence animations and no issues occurred on Raspberry Pi.
Here is my sprite.lua and image
```
local classic = require("classic")
local helper = require("helper")

local obj = classic:extend()

local function setRotateStep(self, rotate)
    local step = 3
    if rotate < 0 then
        self.rotate.step = -step
        self.rotate.start = 360
        self.rotate.ending = step
        rotate = -rotate
    else
        self.rotate.step = step
        self.rotate.start = 0
        self.rotate.ending = 360 - step
    end
    return rotate
end

function obj:init(name, framePath, frameNum, frameWidth, frameHeight, x, y, rotate, fps)
    self.name   = name or "Nobody"

    self.frames = love.graphics.newImage(framePath)
    self.width  = frameWidth
    self.height = frameHeight
    self.index  = 1
    self.angle  = 0
    self.number = frameNum

    self.rotate = {}
    if rotate == nil or rotate == 0 then
        self.rotate.run = false
    else
        rotate = setRotateStep(self, rotate)
        self.rotate.speed = 1 / rotate
        self.rotate.timer = 0
        self.rotate.run = true
    end

    self.loop = {}
    if fps == nil or fps == 0 then
        self.loop.run = false
    else
        self.loop.speed = 1 / fps
        self.loop.timer = 0
        self.loop.run = true
    end

    self.x = x or 0
    self.y = y or 0
end

function obj:update(dt)
    if self.loop.run then
        self.loop.timer = self.loop.timer + dt
        if self.loop.timer >= self.loop.speed then
            self.loop.timer = self.loop.timer - self.loop.speed
            if self.index == self.number then
                self.index = 1
            else
                self.index = self.index + 1
            end
        end
    end

    if self.rotate.run then
        self.rotate.timer = self.rotate.timer + dt
        if self.rotate.timer >= self.rotate.speed then
            self.rotate.timer = self.rotate.timer - self.rotate.speed
            if self.angle == self.rotate.ending then
                self.angle = self.rotate.start
            else
                self.angle = self.angle + self.rotate.step
            end
        end
    end
end

function obj:draw(x, y)
    local index = self.index
    local frames = self.frames
    local r = math.rad(self.angle)
    local w = self.width
    local h = self.height
    local fx = x + self.x
    local fy = y + self.y
    local quad = helper.getQuad(frames, w, h, index)
    love.graphics.draw(frames, quad, fx, fy, r, 1, 1, w / 2, h / 2)
end

function obj:setIndex(i)
    if i > 0 and i <= self.number then
        self.index = i
    end
end

function obj:setRotate(rotate)
    if rotate == nil or rotate == 0 then
        self.rotate.run = false;
    else
        rotate = setRotateStep(self, rotate)
        local speed = 1 / rotate
        if self.rotate.speed == nil then
            self.rotate.timer = 0
            self.rotate.speed = speed
        else
            local ratio = self.rotate.timer / self.rotate.speed
            self.rotate.timer = ratio * speed
            self.rotate.speed = speed
        end
        self.rotate.run = true
    end
end

return obj
```
"blink" works fine on Mac, but not on Raspberry Pi
![face-blink](https://github.com/user-attachments/assets/5bace275-052f-4e46-843f-b4658b2c17d9)
"battery" works fine on Mac and Raspberry Pi
![battery](https://github.com/user-attachments/assets/0235493a-9a90-44ef-8e91-924a9d77a3f2)

**Comment by slime73** [comment]
GPUs have maximum limits on the dimensions of an image. The limit on desktop GPUs tend to be 8k x 8k (for a really old GPU) to 16k x 16k for a newer one - for the raspberry pi it's likely 2k x 2k. You can use [love.graphics.getSystemLimits](https://love2d.org/wiki/love.graphics.getSystemLimits) to check.

love 12 will also cause an error instead of replacing the image with an 'invalid image' texture in that situation.

**Comment by long568** [comment]
> GPUs have maximum limits on the dimensions of an image. The limit on desktop GPUs tend to be 8k x 8k (for a really old GPU) to 16k x 16k for a newer one - for the raspberry pi it's likely 2k x 2k. You can use [love.graphics.getSystemLimits](https://love2d.org/wiki/love.graphics.getSystemLimits) to check.
> 
> love 12 will also cause an error instead of replacing the image with an 'invalid image' texture in that situation.

Thanks
By the way, I test love12 on raspberry pi zero 2 with videocore4 supported opengles 2 but not opengles 3. love12 give the error says it only support opengles 3. Can love12 running in opengles 2？

**Comment by MikuAuahDark** [comment]
LOVE 12 no longer support OpenGL 3.2 and OpenGLES 2.0.
