### ISSUE TITLE
[Windows] Audio quality regression on LÖVE 11.3+

### ISSUE THREAD

**Issue by qixils** [love2d/love#2091]
In working on updating Mari0 and its community mods to LÖVE 11, I heard a couple reports from the community that the audio quality was worse than in prior versions, so I set out last night to try to diagnose this.

This testing was performed on the game [Mari0 CE](https://github.com/Mari0-CE/Mari0-Community-Edition) (cloned from git master) as it supports LÖVE 0.9.0 and above all in one executable. The following video demonstrates the raw audio captured from the game (from OBS Studio 30.1.2) of Mario collecting a power-up. For Windows, with one exception (more on that later), these are captured from the `win64.zip` executables attached to each [GitHub release](https://github.com/love2d/love/releases) on Windows 11. For Linux, each was compiled from source from the corresponding git tag, and run under WSL2. (I was not immediately able to compile Linux versions prior to 11.0, hence their omission.) I have not been able to perform any testing on macOS.

https://github.com/user-attachments/assets/8341bdf3-2d89-4d83-b88e-b00a3986006b

And here is the raw audio, in case GitHub compresses the audio. The differences are easier to hear outside the browser, anyway. [love2d-audio-regression.zip](https://github.com/user-attachments/files/16564538/love2d-audio-regression.zip)

The audio quality and volume has clearly changed over time but the change from 11.2 to 11.3 does appear to be quite a downgrade over prior versions, especially compared to the raw OGG file. It makes the sound much more hollow, as if the high ends have been cut off or the pitch lowered.

So, on the Windows exception. I had a Linux build environment already setup under WSL2 so I started trying to bisect the issue there, but quickly realized it was not present. So I moved to setting up [megasource](https://github.com/love2d/megasource/tree/11.5) on tag 11.5 and started trying to bisect there when I realized that no matter which tag I checked out in `libs\love`, the issue was present, suggesting this may be an issue introduced by revisions to the megasource (further corroborated by it not existing on Linux builds). Unfortunately, I was unable to get the 11.2 tag of megasource to compile to be able to bisect, as 1. I was not able to find the Visual Studio 2013 Express installer, 2. the 2013 Build Tools appear to be missing the required C++ components, and 3. the project no longer appears to compile on VS2019 or 2022.

I have not performed any testing on LÖVE 12.

**Comment by qixils** [comment]
So the LÖVE 12 binaries from [GitHub Actions](https://github.com/love2d/love/actions/runs/10311398898) and megasource appear to be missing the new https module which causes imports of `socket.http` to fail, but I was able to get the game to run with a couple warnings after removing all HTTP code and the issue no longer appears to be present, despite no mention of it in the changelog... oops? A backport may be nice but I understand it is *very* late in the v11 development cycle so no worries about whatever the outcome of this may be...

**Comment by slime73** [comment]
The most likely place to look for the cause of the issue is in OpenAL-Soft, which uses a newer version in love 12 (the newer versions of that library don't support the Visual Studio compiler version used in love 11). 

So it's not an issue in LÖVE's own source and there's no way to backport it to LÖVE 11 without using a different VS setup from the official builds, unfortunately.

> So the LÖVE 12 binaries from [GitHub Actions](https://github.com/love2d/love/actions/runs/10311398898) and megasource appear to be missing the new https module which causes imports of socket.http to fail

I don't know what this means. The new https module is completely independent from luasocket/socket, both work fine as far as I know but they have separate APIs and are `require`'d separately.

**Comment by qixils** [comment]
Thanks for the explanation, unfortunate but reasonable.

I'm likely misunderstanding the error but I was seeing `[string "socket.http"]:39: module 'ssl.https' not found` when trying to use LuaSocket in 12.0. It's irrelevant anyhow. Thank you for the help!
