### ISSUE TITLE
Notarization for stock macOS build

### ISSUE THREAD

**Issue by mahalis** [love2d/love#2092]
Up through macOS 14 it’s been possible to direct players just to right-click-Open LÖVE to bypass the Gatekeeper mechanism. In macOS 15 (Sequoia), that’s going to get much more complicated—they’ll have to go to their Security settings, find the section where it says the app was blocked from launching, and then authenticate themselves to open it. If LÖVE were [notarized](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution), this wouldn’t happen and people would be able to open the main app without security warnings. Is that something you’ve considered? I realize it requires paying Apple’s $99/year fee for a developer account if y’all don’t have one already, but there might be community members excited enough to see better Mac support to make donations that would defray the cost of that.

**Comment by slime73** [comment]
Since people can run arbitrary code with LÖVE, from what I understand notarizing it means we're on the hook if someone makes a .love that's malware and Apple flags the app because of it (https://github.com/love2d/love/issues/1554#issuecomment-593211537) – so every copy of love would stop working simultaneously if that happens, and we couldn't guarantee that it won't happen.

Aside from that and the developer fee, we'd also probably need to distribute a second unsigned app people can use for distributing their own games as well. 

Overall Apple has put tools like LÖVE between a rock and a hard place with these changes.

**Comment by mahalis** [comment]
Ah dang, I guess that makes sense. At least for the second point, it’s possible to remove a signature (it’s all just in a _CodeSignature folder inside the bundle in any case) and re-sign it… but that doesn’t help if someone does distribute something malicious.

I donated a bit anyway, just out of appreciation for y’all making such a great engine. I can live with giving people the elaborate run instructions. Thanks for the quick response.

**Comment by slime73** [comment]
Thank you! I'm kind of hoping for a secret third option to appear that works well for us because I'm not happy with either possibility right now...

**Comment by HanKruiger** [comment]
>  [...] it means we're on the hook if someone makes a .love that's malware and Apple flags the app because of it ([#1554 (comment)](https://github.com/love2d/love/issues/1554#issuecomment-593211537)) [...]
 
I would be shocked if this is indeed the way Apple would handle this.

Wouldn't that mean that *any* interpreter for a programming language would be on the hook if someone created a malicious program in that language?

**Comment by slime73** [comment]
I don't believe most standalone programming language interpreters are shipped as pre-built macOS app bundles with GUIs.

We ship a runtime that other people are expected to redistribute.

**Comment by HanKruiger** [comment]
Ah, I see! Thanks for clearing that up.
And apologies for commenting on this dead issue.

I am just getting into LÖVE so I wasn't really aware of the distribution methods.

Anyway, thanks for working on LÖVE, it looks very interesting!
