### ISSUE TITLE
Love 12: newImage return type fails typeOf(Image) check, claims it's Texture

### ISSUE THREAD

**Issue by turbo** [love2d/love#2095]
Comparing the output between Love 11.4 (downloaded from the site) and 12 (compiled from source, commit `ccdd7897f2999a7ed144beaa08919566e655b1ea`) on macOS 15.

```lua
function love.load()
	bunny = love.graphics.newImage("crown.png")
  print(bunny:type())
  print(bunny:typeOf("Object"))
  print(bunny:typeOf("Drawable"))
  print(bunny:typeOf("Image"))
  print(bunny:typeOf("Texture"))
  print(bunny:typeOf("MouseJoint"))
end

function love.draw()
	love.graphics.draw(bunny, 0, 0)
end
```

For Love 11.4:

```text
Image
true
true
true
true
false
```

For Love 12:

```text
Texture
true
true
false
true
false
```

The image is the same.

What's weird is that [in the Love Wiki, for `type()`](https://love2d.org/wiki/Object:type), `Texture` is the expected return value, though I'm not sure why. The behavior of 11.4 seems correct to me.

<details>
  <summary>Image file</summary>
  <img src="https://github.com/user-attachments/assets/26daf82d-ed48-4b39-b81f-f664c5807a4a">
</details>

**Comment by slime73** [comment]
That's working as expected. Image and Canvas subclasses are merged into Texture in love 12, as per the changelog: https://love2d.org/wiki/12.0

**Comment by turbo** [comment]
Thanks, missed that 🙂
