### ISSUE TITLE
libluajit.so filepath is too long

### ISSUE THREAD

**Issue by mds2000713** [love2d/love#2096]
Saw an error log about this already https://github.com/love2d/love-android/issues/247
I had the same issue until I remade the project in a different folder.
I think that the issue lies with the file path towards libluajit.so; starting from love-android, it is 86 characters and I think that the limit is 128. The original project I had made the file path 143 characters, my new one (C:\1\love-android...) is 90 characters.
Have fixed this already, but wanted to bring attention to this. Thanks!

**Comment by MikuAuahDark** [comment]
What exactly does the error message says? If you're compiling in Windows, there's default 260 character limit to paths which [can be removed](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry).

**Comment by mds2000713** [comment]
<img width="896" alt="image" src="https://github.com/user-attachments/assets/99650506-698c-4369-8233-13b3d2f85a0e">

dlopen failed libluajit.so not found, this was in android studio.

I'm not familiar enough with lua, love or android studio to diagnose the problem, so it may be another issue. All I know is that the issue was resolved by having the project closer to the main drive, i.e. reducing the number of folders I need to navigate through to reach the love-android project. Sorry I couldn't be of more help. Thanks!

**Comment by MikuAuahDark** [comment]
Yeah, sadly this is platform-specific issue mainly hitting Windows users due to paths being limited to 260 characters by default.

Unfortunately there's not we can do.
