### ISSUE TITLE
Latest XCode (15.4) segfaults when building love 11.5

### ISSUE THREAD

**Issue by ImpleLee** [love2d/love#2099]
XCode 15.4 segfaults when we run [the following command](https://github.com/love-actions/love-actions-macos-portable/blob/d2b37ce2d43a812f42ef60c408722b297f8a9ee7/action.yml#L378) [in our CI](https://github.com/26F-Studio/Techmino/actions/runs/10696703827).
```
xcodebuild -exportArchive -archivePath ${{ env.ARCHIVE_PATH }} -exportPath ./love-actions-macos-portable/
```

XCode 15.3 [runs properly](https://github.com/26F-Studio/Techmino/actions/runs/10697752564). There is [a similar post on Apple forum](https://forums.developer.apple.com/forums/thread/757398) (there is also [a reproducing repo for ios app](https://github.com/darrarski/ios-app-export-unsigned-ipa-example) in that post), so we think it is a bug in XCode itself.

This issue can remain open and serves as a tracking issue, so that we can close this issue when we know we don't need to use XCode 15.3 for building. Other developers can also find this issue when facing this problem.

**Comment by ImpleLee** [comment]
We are using `macos-latest` in our GitHub CI (spec: https://github.com/actions/runner-images/blob/3926b864c36dbf6eecb879b096df5884abcf5b4a/images/macos/macos-14-arm64-Readme.md ).

**Comment by slime73** [comment]
What's the reason for needing to build 11.5 from source every time instead of grabbing the prebuilt .app?

**Comment by slime73** [comment]
The latest 11.x branch is building fine for macOS locally and with Github Actions (both using xcode 15.4) for me. Example: https://github.com/slime73/love-experiments/actions/runs/10701723455/job/29668298506

**Comment by ImpleLee** [comment]
> What's the reason for needing to build 11.5 from source every time instead of grabbing the prebuilt .app?

Because we follow [your wiki](https://love2d.org/wiki/Game_Distribution#Official_Distribution_and_the_App_Store).



> The latest 11.x branch is building fine for macOS locally and with Github Actions (both using xcode 15.4) for me. Example: https://github.com/slime73/love-experiments/actions/runs/10701723455/job/29668298506

Our CI builds fine when we don't sign it ( https://github.com/26F-Studio/Techmino/actions/runs/10702673275/job/29673932064 ), but segfaults when we sign it ( https://github.com/26F-Studio/Techmino/actions/runs/10702673275/job/29671632440 ). Maybe it only segfaults when you sign it?

**Comment by slime73** [comment]
I believe you can codesign love without building if you want, since love isn't codesigned already.

> Maybe it only segfaults when you sign it?

Possibly. If so I don't think that's an issue with this repository though, we don't usually do tracking issues here especially for things that aren't part of the normal flow of the repository.

**Comment by slime73** [comment]
You might also want to investigate whether there are specific parts of your codesign configuration or build setup that are causing the crash.

**Comment by ImpleLee** [comment]
> You might also want to investigate whether there are specific parts of your codesign configuration or build setup that are causing the crash.

Generally that is possible, but since I have found a usable and not-too-bad solution (using XCode 15.3), I have kind of lost my motivation and maybe I will just wait for Apple to fix the bug on the post or release a new version of XCode.
