### ISSUE TITLE
Include BitOp

### ISSUE THREAD

**Issue by slime73** [love2d/love#210]
**[Original report](https://bitbucket.org/rude/love/issue/205) by Anonymous.**

----------------------------------------

I think Love should include the BitOp library, so that we can have fast bitwise operations in our games (you need 'em from time to time).

**Comment by MrZ626** [comment]
Sorry for replying this issue after 11 years. But can we have `~ & | << >>` to use? I found a library with tons of bitOP (a hashing library) but I cannot use it easily by simply requiring it

**Comment by MikuAuahDark** [comment]
That bitwise operators are Lua 5.3 and I don't think we'll use Lua 5.3 for our official builds mainly due to compatibility and performance reasons.

**Comment by MrZ626** [comment]
> love uses LuaJIT which provides this - all you need to do is `require` it: https://web.archive.org/web/20220820165604/https://bitop.luajit.org/api.html

thanks, though I meant using bitOP like `a&b`, not `bit.and(a,b)`, that library has thousands of them

**Comment by slime73** [comment]
Operators are language features. LuaJIT doesn't support that.
