### ISSUE TITLE
Issues with .lua files path

### ISSUE THREAD

**Issue by RandomDude101Offical** [love2d/love#2105]
hello,

for some reason Löve2D does not open/recognize lua files that are in folders, and it only recognize lua files that aren't in any folder (expect project ones)

**Comment by MikuAuahDark** [comment]
If you run `love path/to/project`, it can only load Lua files in `path/to/project` and its subdirectories. Any Lua files that are in `path/to` are not recognized. This is intentional.

**Comment by slime73** [comment]
If you need additional help, the discord server, forums, or subreddit are good places for that.
