### ISSUE TITLE
unpack can't see full list when nil inside

### ISSUE THREAD

**Issue by AldieNightStar** [love2d/love#2106]
* This code can't see `7` at index `7` if there is not another element
```lua
local x = {unpack({1, nil, nil, 4, 5, nil, 7})}
print(x[7]) -- nil
```

* This code works fine
```lua
local x = {unpack({1, nil, nil, 4, 5, nil, 7, 8})}
print(x[7]) -- see '7'
```

* Why `nil`? I working on capturing arguments for functions for later defer call. And some functions could have `nil` arguments. This is buggy.

__LUA: 5.1__

**Comment by slime73** [comment]
This issue tracker is for problems and changes with love's source code, rather than Lua behaviour.

That being said, [select](https://www.lua.org/manual/5.1/manual.html#pdf-select) is probably a better fit for what you want to do.

**Comment by slime73** [comment]
love uses LuaJIT 2.1.
