### ISSUE TITLE
Virus detected Error while downloading the LOVE 64-bit installer on Windows.

### ISSUE THREAD

**Issue by chinnu8055** [love2d/love#2108]
![Screenshot 2024-09-29 203144](https://github.com/user-attachments/assets/9606ec02-f2eb-4c76-9ec2-b749ae8b5da0)

**Comment by slime73** [comment]
I'm not sure there's much we can do about poor antivirus software that's overly aggressive and flags things that are actually safe. Maybe it has a way for you to report it as safe? Or you could use a better product.

**Comment by Asporez** [comment]
false positive, common with external antivirus software. Windows Defender is more than sufficient.

If you want to be 100% sure that it's a false positive you can submit for review here.
https://www.microsoft.com/en-us/wdsi/filesubmission
