### ISSUE TITLE
Hardware cursor immediately disappears unless assigned to global variable

### ISSUE THREAD

**Issue by simonpuravida333** [love2d/love#2109]
like the title says, if there's any table in between _G and Cursor object, the graphic is not being shown and the mouse graphic defaults to Windows user setting.
It does not get silently garbagecollected, the Cursor object is still there after any while, it's just not rendered.

Love 11.5 / Win 10

To recreate:
collectgarbage("stop")
local mouseArt = love.image.newImageData('Content/Graphics/mouse.png')

_-- WILL DISPLAY:_
cursor = love.mouse.newCursor(mouseArt, 4, 4)
love.mouse.setCursor(cursor)

_-- WILL NOT DISPLAY:_
self.cursor = love.mouse.newCursor(mouseArt, 4, 4)
anyTable.cursor = love.mouse.newCursor(mouseArt, 4, 4)
...
love.mouse.setCursor(self.cursor)

Kind regards

**Comment by slime73** [comment]
Can you post a full standalone bit of code or .love/zip that reproduces the issue?

At first glance from the little bit of code you posted so far, it sounds like `self.cursor` is nil (i.e. it's not the same value as the previously created cursor object).

**Comment by simonpuravida333** [comment]
Oh no my bad.
In the update loop where it checks whether it should switch to another cursor object, there was a referencing error which ultimately led to setCursor with a nil argument.
Should have found it before starting to hallucinate. Sorry, it's a silly mistake.
