### ISSUE TITLE
love.graphics.clear effect outside of scissor area (love12)

### ISSUE THREAD

**Issue by zhengying** [love2d/love#2110]
```
function love.draw()
        love.graphics.setScissor(10, 10, 300, 300)
        love.graphics.clear(0,0,1)  -- this clear should only effect the scissor area
        love.graphics.setScissor()
end
```
my environment is : iMac macOS 13.4 intel chip Radeon Pro 570 4 GB
this code in love12 will be a blue square, but all window cleared with blue color.

love12:
<img width="796" alt="Screenshot 2024-10-20 at 08 38 28" src="https://github.com/user-attachments/assets/1b07a5d6-617f-4fd9-9fef-6d7e49e1fc5d">
love11.5:
<img width="794" alt="Screenshot 2024-10-20 at 08 41 02" src="https://github.com/user-attachments/assets/113332c5-54ef-43aa-9cd6-d4d2407addf4">

**Comment by Endaris** [comment]
That is a documented change:
https://www.love2d.org/wiki/12.0
> Changed [love.graphics.clear](https://www.love2d.org/wiki/love.graphics.clear) to no longer be affected by [love.graphics.setScissor](https://www.love2d.org/wiki/love.graphics.setScissor) or [love.graphics.setColorMask](https://www.love2d.org/wiki/love.graphics.setColorMask).

**Comment by zhengying** [comment]
> That is a documented change: https://www.love2d.org/wiki/12.0
> 
> > Changed [love.graphics.clear](https://www.love2d.org/wiki/love.graphics.clear) to no longer be affected by [love.graphics.setScissor](https://www.love2d.org/wiki/love.graphics.setScissor) or [love.graphics.setColorMask](https://www.love2d.org/wiki/love.graphics.setColorMask).

Oh, great. 
that make sense. thank.
