### ISSUE TITLE
Weird Results with love.graphics.clear After canvas draw in Scissor Area

### ISSUE THREAD

**Issue by zhengying** [love2d/love#2112]
I have observed an unexpected result when performing a love.graphics.clear operation after drawing on a canvas within a scissor area. This behavior is not a corner case; it can easily be triggered in scenarios involving scrollable views or similar UI elements where a canvas is drawn within a restricted area.

this is a simple demo:
```
local canvas = love.graphics.newCanvas(100, 100)

function love.draw()
        love.graphics.setScissor(0, 0, 300, 300)
        love.graphics.clear(0,0,1)
        love.graphics.setCanvas(canvas) -- this cavnas do nothing
        love.graphics.setCanvas()
        love.graphics.clear(1,0,0)
        love.graphics.setScissor()
end
```
a canvas do nothing here, it effect after a clear, the result it like this:

<img width="793" alt="Screenshot 2024-10-21 at 07 22 53" src="https://github.com/user-attachments/assets/f6a84c24-fff4-4560-b5ca-7427dc3f399b">

my environment is : iMac macOS 13.4 intel chip Radeon Pro 570 4 GB
love 11.5

**Comment by slime73** [comment]
Looking at the code, it seems to be an order of operations problem inside the OpenGL backend implementation of setCanvas (it reapplies the scissor using out of date information about whether a canvas is active).

love 12 won't have the same issue with love.graphics.clear since it isn't affected by scissors anymore, but I think the bug may still affect other things.

**Comment by zhengying** [comment]
great!.when will it be a new release?

**Comment by slime73** [comment]
We don't have a release date for love 12, but you can always download a nightly build from Github Actions - here's the latest: https://github.com/love2d/love/actions/runs/11867071430#artifacts

**Comment by zhengying** [comment]
> We don't have a release date for love 12, but you can always download a nightly build from Github Actions - here's the latest: https://github.com/love2d/love/actions/runs/11867071430#artifacts

but this bug is found in love11.5. It's severe in some cases.

**Comment by slime73** [comment]
We aren't planning another 11.x release.

The bug only happens if you keep the exact same scissor active when switching between a canvas and the screen, so one (of several) simple workarounds is to set a new scissor in that situation.
