### ISSUE TITLE
No change when set t.window.title in love.conf

### ISSUE THREAD

**Issue by kimiko88** [love2d/love#2113]
In version 11.5 (on windows 11) when I try to change the title with `t.window.title` in `love.conf`, the title doesn't change.
The only way that I find to change the window title is using `love.window.setTitle(  )`.

**Comment by steveRoll-git** [comment]
This is most likely not a bug in love. Are you sure you have your `conf.lua` file in the same location as your `main.lua`, and that `love.conf` is defined properly?

**Comment by kimiko88** [comment]
My bad, I was trying to use love.conf inside main.lua and not in conf.lua. 
Now it works.

Thanks for the help.
