### ISSUE TITLE
[12.0] Graphics Adapter Selection When Using Vulkan Renderer

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d/love#2127]
LOVE currently tries to use the strongest graphics adapter available with Vulkan graphics backend. However this not always what the user wants. There are 2 cases where the strongest GPU adapter is not what user wants:

1. When the user want to use low-power GPU (mainly for laptops with dual-GPU setup) to conserve battery life.
2. When the user have multiple GPUs with different vendor (this can mean more than 2 GPUs) and want to test a potential graphics driver bug by cross-referencing the result between other GPUs.

In Windows with the OpenGL renderer, Windows decides the actual GPU to use. However in Vulkan it's entirely up to the app to pick the GPU to use.

**Comment by slime73** [comment]
This could also be used by the Metal backend.
