### ISSUE TITLE
Add an open-file popup dialog function

### ISSUE THREAD

**Issue by slime73** [love2d/love#990]
**[Original report](https://bitbucket.org/rude/love/issue/985) by Eliter Scripts (Bitbucket: [EliterScripts](https://bitbucket.org/EliterScripts), GitHub: [EliterScripts](https://github.com/EliterScripts)).**

----------------------------------------

can there be something like love.graphics.UserSearch(Arg1,Arg2) can everyone who is looking at this go into Google Chrome (a web browser, look it up), type in "Chrome://settings" in the address bar, scroll down all the way to "Show advanced settings..." and click that. Then to the left of the "Download location:" there is a box, click it. See that window that popped up? can you guys put that into love2d, so like a User Avatar picture would be EASY for the user to locate. It would be so awesome. 
Now, for love.graphics.UserSearch(), the first Argument, being what directory to be looking first (Like, in chrome, it's probably at, by default, looking at "C:\USERNAME\Downloads"), the Second argument could be nil, OR a string. The second argument, if it is nil, then ALL the directories and files will be displayed. When the second argument is a string, it will look at ALL the directories, but will only view the file extension that is the same as the string that is Arg2.

That make sense?

**Comment by steveRoll-git** [comment]
This is something that I was thinking about for a long time, and just now found an issue for it.
Are native file dialogs planned in any way for future versions of löve?

**Comment by MikuAuahDark** [comment]
This has been brought recently too and the idea is to use Zenity or KDialog in Linux.

The next question is how would the API look like? On what module it should belong? Should it be in `love.window` because it deals with window, `love.system` because it's system-specific feature? or `love.filesystem` as it deal with paths?

**Comment by steveRoll-git** [comment]
`love.system` makes the most sense imo, because it already has one function to show a system window (`love.system.showMessageBox`).
